### ISSUE TITLE
Implement control onNextPressed()

### ISSUE THREAD

**Issue by Nem2s** [PaoloRotolo/AppIntro#102]
Hi, i'm currently working on AppIntro, but i have to show a Dialog message when i press **NextButton** in the first fragment **if** i haven't selected any RadioButtons into it before going on the Second one.
Is possible to do or i must implement something in the Fragment?

**Comment by Betobit** [comment]
You could try getting the pager and capture the event with a custom click listener. Here is the idea.

```java
private ViewPager pager;
pager = getPager();

customNextButton.setOnClickListener(new View.OnClickListener() {
    @Override
     public void onClick(@NonNull View v) {
        /* If radio buttons are empty
              then showDialog();
          else
              pager.setCurrentItem(pager.getCurrentItem() + 1);
        */
     }
 });
```

**Comment by Nem2s** [comment]
Same idea: but the "**CustomNextButton**" is already a class inside the repo?

**Comment by Betobit** [comment]
CustomNextButton is the button on the view

CustomNextButton = (Button)findViewById(R.id.yourButtonId);

**Comment by Andrew-Quebe** [comment]
Is this resolved @Nem2s?

**Comment by Nem2s** [comment]
Sorry for delay but i don't understand: through the *getPager()* can I extract the **CustomNextButton**? I'm using the "integrated" one, i don't have any buttons in my layout.

**Comment by Nem2s** [comment]
EDIT: solved, I implemented the @Betobit solution! Thanks a lot

**Comment by Andrew-Quebe** [comment]
@Nem2s glad you got it working :)

**Comment by Betobit** [comment]
@Nem2s (: Nice! And sorry for my hurry answer I was in the U :P
