### ISSUE TITLE
My app "AlarmSMS" is using Appintro

### ISSUE THREAD

**Issue by Quentin330** [PaoloRotolo/AppIntro#103]
You can find my app here https://play.google.com/store/apps/details?id=com.qhutch.alarmsms
I think Appintro is a really great library, and I think I will use it in all my next apps, I will also recommand it to all my friends =)

**Comment by brunano21** [comment]
@Quentin330 what did you use for material stuff? any library or everything from scratch?
However well done!

**Comment by Quentin330** [comment]
I used just use the appcompat library 'com.android.support:appcompat-v7:23.1.0'

**Comment by Andrew-Quebe** [comment]
@Quentin330 glad you find the library useful :) Nice app too!

The readme has been updated.
