### ISSUE TITLE
Question: show Done button from fragment

### ISSUE THREAD

**Issue by albertogarrido** [PaoloRotolo/AppIntro#104]
Hello! thanks for this library, it's great. 

This is what i need to achieve:

- By default I have showDoneButton(false)
- I have 3 slides with some instructions
- in the 4th (the latest one) I show 2 options to the user choose current location or a city
- When the user chooses location I hide all the elements (with animations and stuff) and i'm trying to show again the done button to dismiss the intro. I'm calling ((TutorialActivity) getActivity()).showDoneButton(true); from the fragment but it's not working. Also I've created a function on my activity to toggle the button from there but it's not working either.

What am I missing?

Thanks again :)

**Comment by albertogarrido** [comment]
I found why:

```
public void showDoneButton(boolean showDone) {
        this.showDone = showDone;
        if (!showDone) {
            TextView done = (TextView) findViewById(R.id.done);
            done.setVisibility(View.GONE);
        }
    }
```
Above code should be: 

```
public void showDoneButton(boolean showDone) {
        this.showDone = showDone;
        TextView done = (TextView) findViewById(R.id.done);
        if (!showDone) {
           done.setVisibility(View.GONE);
        } else {
           done.setVisibility(View.VISIBLE);
        }
    }
```
I will try to add and test that code this weekend and submit a pr.

**Comment by danluong** [comment]
Hi, I believe this case is handled by the pull request I have submitted (#100). Although, admittedly it's a pretty big pull request, so I'm not sure how long it will take to get incorporated.

**Comment by Andrew-Quebe** [comment]
@danluong it's been pulled :) Will incorporate into the lib soon.

**Comment by albertogarrido** [comment]
Cool. I will check later and if is not maybe I will wait to your pull merged to change it.

Anyway the designers decided to dismiss the tutorial after showing a message for one second :) so no hurry

**Comment by Andrew-Quebe** [comment]
@albertogarrido I really just have to figure out how to release this lib onto Maven and I'll be good :)
