### ISSUE TITLE
Use with Android Annotations

### ISSUE THREAD

**Issue by rohanmahale** [PaoloRotolo/AppIntro#105]
Android Annotations generates it's underscore classes for you when you use enhanced Activities or Fragments and these generated classes automatically have OnCreate overriden. Is there a work around for this?

**Comment by Andrew-Quebe** [comment]
I've never worked with something like this. Will investigate.

**Comment by rohanmahale** [comment]
Hi Andrew. Any updates or feedback on this particular issue? I would love to integrate the lib in my app. Hopefully there is a way around this.

**Comment by rohanmahale** [comment]
Hi @Andrew-Quebe  and @PaoloRotolo. Is there any way around the issue I am facing?

**Comment by HeinrichReimer** [comment]
This would be solved when #119 will be solven.

**Comment by rohanmahale** [comment]
Yeah ..figured. Thanks.

**Comment by avluis** [comment]
Looks like this no longer applies after the recent changes on the library, please reopen this issue if still affected by this issue.
