### ISSUE TITLE
How to apply a custom typeface.

### ISSUE THREAD

**Issue by whitehawks** [PaoloRotolo/AppIntro#108]
How do I apply a custom font store in my assets folder to the title of the sliders.

**Comment by stripathi669** [comment]
Any answers? The deault font is not good. I really want to change it.

**Comment by Andrew-Quebe** [comment]
See the example for one way to change fonts. https://github.com/PaoloRotolo/AppIntro/blob/master/example/src/main/res/layout/intro.xml#L16

You can also Google it and I'm sure you'd find some pretty good answers.

**Comment by stripathi669** [comment]
@Andrew-Quebe My point was user should be able to change font without having to create a new fragment. The slide (fragment) could take font path as optional parameter.

**Comment by ameykshirsagar** [comment]
I think this question can be solved by this solution. I created a fragment class based on [SampleSlide](https://github.com/PaoloRotolo/AppIntro/blob/master/example/src/main/java/com/github/paolorotolo/appintroexample/SampleSlide.java)
Here is my solution
`public class SliderFragment extends Fragment {
    public SliderFragment(){}
    private static final String ARG_LAYOUT_NUM = "layoutNum";
    private static final String ARG_LAYOUT_RES_ID = "layoutResId";
    private static final String ARG_LAYOUT_TYPE = "layoutType";
    private static final String ARG_IMAGE = "imageResId";
    private static final String ARG_TITLE = "title";
    private static final String ARG_STITLE = "stitle";
    private static final String ARG_DESC = "desc";
    private static final String ARG_COLOR = "color";
    private static final String ARG_BTNTEXT = "btnText";
    private static View.OnClickListener onclklstnr;
    private static Boolean isBitmap;
    private static Bitmap img;
    public static SliderFragment newInstance(int layoutNum,int layoutResId, int imageResId, String ttl, String sttl, String btn_text , View.OnClickListener oncl,String clr, int layoutTypeInt) {
        SliderFragment sampleSlide = new SliderFragment();

        Bundle args = new Bundle();
        args.putInt(ARG_LAYOUT_NUM, layoutNum);
        args.putInt(ARG_LAYOUT_RES_ID, layoutResId);
        args.putInt(ARG_LAYOUT_TYPE,layoutTypeInt);
        args.putInt(ARG_IMAGE,imageResId);
        onclklstnr = oncl;
        isBitmap = false;
        args.putString(ARG_TITLE,ttl);
        args.putString(ARG_STITLE,sttl);
        args.putString(ARG_BTNTEXT,btn_text);
        args.putString(ARG_COLOR,clr);
        sampleSlide.setArguments(args);

        return sampleSlide;
    }
    
    public static SliderFragment newInstance(int layoutNum,int layoutResId,int imageResId, String ttl, String sttl, String desc,String clr,int layoutTypeInt) {
        SliderFragment sampleSlide = new SliderFragment();

        Bundle args = new Bundle();
        args.putInt(ARG_LAYOUT_NUM, layoutNum);
        args.putInt(ARG_LAYOUT_RES_ID, layoutResId);
        args.putInt(ARG_LAYOUT_TYPE,layoutTypeInt);
        args.putInt(ARG_IMAGE,imageResId);
        isBitmap = false;
        args.putString(ARG_DESC,desc);
        args.putString(ARG_TITLE,ttl);
        args.putString(ARG_STITLE,sttl);
        args.putString(ARG_COLOR,clr);
        sampleSlide.setArguments(args);

        return sampleSlide;
    }
    public static SliderFragment newInstance(int layoutNum,int layoutResId,Bitmap image, String ttl, String sttl, String desc,String clr,int layoutTypeInt) {
        SliderFragment sampleSlide = new SliderFragment();

        Bundle args = new Bundle();
        args.putInt(ARG_LAYOUT_NUM, layoutNum);
        args.putInt(ARG_LAYOUT_RES_ID, layoutResId);
        
        args.putString(ARG_DESC,desc);
        args.putString(ARG_TITLE,ttl);
        args.putString(ARG_STITLE,sttl);
        args.putString(ARG_COLOR,clr);
        sampleSlide.setArguments(args);

        return sampleSlide;
    }
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View v = inflater.inflate(layoutResId, container, false);
        overrideFonts(getContext(),v);
        return v;
    }

    private void overrideFonts(final Context context, final View v) {
        try {
            if (v instanceof ViewGroup) {
                ViewGroup vg = (ViewGroup) v;
                for (int i = 0; i < vg.getChildCount(); i++) {
                    View child = vg.getChildAt(i);
                    overrideFonts(context, child);
                }
            } else if (v instanceof TextView) {
                ((TextView) v).setTypeface(FontCacheHelper.get(getResources().getString(R.string.light_font),context));
            }
        } catch (Exception e) {
        }
    }
}`

Here is the class FontCacheHelper to [prevent memory leaks caused by Typeface class](http://www.google.com/url?q=http%3A%2F%2Fandroiddevelopmentguide.blogspot.com%2F2016%2F06%2Fmemory-leaks-with-custom-font-in-android.html&sa=D&sntz=1&usg=AFQjCNHbwmPKo62IFlyfGrgoIimok_b0sQ). Don't know why Google has not fixed it yet. Initially you need to create a Typeface object for specific font then whenever you need a certain Typeface you just need to pass the assets URL of the font file which can be statically saved in strings.xml

`
public class FontCacheHelper {
    private static Hashtable<String,Typeface> fCache = new Hashtable<String,Typeface>();
    public static Typeface get (String tfn, Context ctx){
        Typeface tf = fCache.get(tfn);
        if (tf==null){
            //Log.i("font add","Adding new font -> "+tfn);
            try {
                tf = Typeface.createFromAsset(ctx.getAssets(),tfn);
                if (tf!=null){
                    fCache.put(tfn,tf);
                }

                return tf;
            }catch (Exception e){
                return null;
            }

        }else{
            //Log.i("font exist","Getting cached font -> "+tfn);
            return tf;
        }


    }
}
`
This solution is being used in production projects by me and I can assure you it wont create much of a performance overhead on the app.
@PaoloRotolo you can add this solution in the wiki. @stripathi669 this solution can solve your problem.

**Comment by avluis** [comment]
The solution posted above by @ameykshirsagar is essentially what developers should be doing instead of relying on the library to do it all for you (you don't want a do it all library, learn JAVA one day :smile_cat: ).

**Comment by ameykshirsagar** [comment]
@avluis : I would like to contribute in making the Wiki for issues & questions like this. And also in using this library to make Wizards & Intros. I have played enough around to do so. 
What do you think??

**Comment by avluis** [comment]
I believe the wiki is open for public editing if you want to build a Q & A section.
So you are free to add as you see fit as long as you follow a similar format to what is already there.
How familiar are you with working on wikis? Let me know if you need any clarification.

**Comment by Andrew-Quebe** [comment]
@ameykshirsagar you're free to make contributions to the Wiki, but they will be reviewed by the collaborators, and if anything isn't correct, it will be edited or removed. If you're familiar with forking the Wiki, go ahead. You'll be able to submit your changes in the form of a pull request just like editing the main project.

If you have any questions, let myself or @avluis know and we can assist you.

**Comment by ameykshirsagar** [comment]
@avluis @Andrew-Quebe 
Yes I do have experience in writing wikis. I have forked the repository and I shall also provide some of the features related to custom Typeface to the default view of slide.
Also will it be OK to add a wizard mode where we can add a back button instead of skip button in both the AppIntro & AppIntro2. So that we can expand the scope of this library beyond just Intro builder library.
I have the plan and it wont be much a hassle.

**Comment by Andrew-Quebe** [comment]
@ameykshirsagar if you can implement this, then by all means, feel free to do so. @avluis has been doing a good job at keeping tabs on the issues in this project, but I've been working on some other stuff, so I haven't had time to contribute to this project.
