### ISSUE TITLE
change "skip" and "done" text?

### ISSUE THREAD

**Issue by TheLoyalCruel** [PaoloRotolo/AppIntro#109]
I'm using SampleSlide...
how to change the "skip" and "done" text within slides?
What about applying custom typeface to them?
thanks...

**Comment by gleristoncavalcante** [comment]
call setSkipText(String text) and setDoneText(String text) in method init.

**Comment by Andrew-Quebe** [comment]
@gleristoncavalcante is right. I didn't realize the library had this option until now :P
