### ISSUE TITLE
Manually moving to next slide

### ISSUE THREAD

**Issue by VigneshPT** [PaoloRotolo/AppIntro#110]
Is there a way to manually move to next slide from any slide? I have custom slides, and on the first slide I have placed a button and on clicking that button the intro should slide to the second slide.

**Comment by Andrew-Quebe** [comment]
The library automatically makes these buttons for you...theoretically, you shouldn't have a button that moves to the next slide if the library provides one already.

**Comment by VigneshPT** [comment]
Ok. Anyways, I solved it by putting `getPager().setCurrentItem(indexOfSlideToMove)` on click event in my class which extended `AppIntro`

**Comment by Andrew-Quebe** [comment]
@VigneshPT great! Glad you found what you were looking for :)

**Comment by androidovshchik** [comment]
It's much better with smoothing scroll
```
pager.setCurrentItem(1, true)
```
