### ISSUE TITLE
How to load an Image into a slide

### ISSUE THREAD

**Issue by brunano21** [PaoloRotolo/AppIntro#112]
hello,

I have the necessity to load an image downloaded from internet into an slide. I'm using [Ion](https://github.com/koush/ion) for that.
However, I realized that the `onCreate` and `onCreateView` methods of any slides are never called. 
How can I address that?
Any suggestion or snippet?
Thanks.

**Comment by Andrew-Quebe** [comment]
@brunano21 as specified in the Readme, you can override init() and run any code you need to there. Let me know if you run into trouble.
