### ISSUE TITLE
I'm using AppIntro in my ChineseDictionary app:)

### ISSUE THREAD

**Issue by jnshey** [PaoloRotolo/AppIntro#113]
Hi,

Thanks for the great `AppIntro` library. It allows me to include professional-looking introduction screens to my app. I have used it in my ChineseDictionary app. Its link is https://play.google.com/store/apps/details?id=com.jonasng.chinesedictionary.

Its Chinese name is: `粵韻漢典離線粵語普通話發聲中文字典`.
Or if that is too long, its English name is `ChineseDictionary`. Or feel free to use any description you like, since it does not really have an English name.

**Comment by Andrew-Quebe** [comment]
Readme updated! Glad you found the library useful :)
