### ISSUE TITLE
Ripple bug in layout 2

### ISSUE THREAD

**Issue by HeinrichReimer** [PaoloRotolo/AppIntro#116]
The ripple for the next page button has incorrect ripple bounds. The ripple effect is shown for its parent container instead of the small round button

**Comment by Andrew-Quebe** [comment]
What do you propose as a fix for this?

**Comment by HeinrichReimer** [comment]
Here's a screenshot of the bug: http://imgur.com/h0RY2Sy

**Comment by HeinrichReimer** [comment]
I think the main issue is that the done icon used in [`R.layout.intro_layout2`](https://github.com/PaoloRotolo/AppIntro/blob/master/library/src/main/res/layout/intro_layout2.xml) itself is a static graphic.

We can remove the ripple background and replace [`R.drawable.ic_done_white_24px`](https://github.com/PaoloRotolo/AppIntro/blob/master/library/src/main/res/drawable-xxxhdpi/ic_done_white_24px.png) with a new Drawable to fix this:

**intro_layout2.xml (New code for done button)**

    <ImageButton
        android:layout_width="wrap_content"
        android:layout_height="fill_parent"
        android:id="@+id/done"
        android:layout_gravity="right"
        android:layout_marginRight="16dp"
        android:visibility="gone"
        android:src="@drawable/ic_done_white" />

**button_done.xml (API < 21):**

    <?xml version="1.0" encoding="utf-8"?>
    <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
        <item>
            <shape android:shape="oval">
                <size android:height="48dp" android:width="48dp"/>
                <solid android:color="@color/background_color_selector" />
            </shape>
        </item>
        <item android:drawable="@drawable/ic_done_"/>
    </layer-list>

`R.color.background_color_selector` should be a color selector as described [here](http://developer.android.com/guide/topics/resources/color-list-resource.html).

**button_done.xml (API >= 21):**

    <?xml version="1.0" encoding="utf-8"?>
    <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
        <item>
            <ripple
                android:color="@color/ripple_color">
                <item>
                    <shape android:shape="oval">
                        <size android:height="48dp" android:width="48dp"/>
                        <solid android:color="#8A000000" />
                    </shape>
                </item>
            </ripple>
        </item>
        <item android:drawable="@drawable/ic_done"/>
    </layer-list>

`R.drawable.ic_done` could be the default done icon using the Vector Assets Generator from Android Studio.

Same goes for back button...

I didn't test this but I hope this approach helps to fix this bug :)

**Comment by mntgoat** [comment]
I'm still seeing this bug, any idea when a fix might be released?

**Comment by HeinrichReimer** [comment]
f you still have troubles with the ripple background you may take a look at [HeinrichReimer/material-intro](https://github.com/HeinrichReimer/material-intro). It has some other cool improvements too.
