### ISSUE TITLE
Feature request: animated pager indicator

### ISSUE THREAD

**Issue by HeinrichReimer** [PaoloRotolo/AppIntro#117]
An animated pager indicator as in "Plaid" would be nice.

**Comment by Andrew-Quebe** [comment]
This is a work in progress. It is *possible* that this library will be merged with Alexandre Piveteau's [library](https://github.com/cadialex/MaterialTutorial). Strong emphasis on possible. We're not confirming or denying that this is a possibility just yet. We still need to work a few things out before we'll know for sure.

**Comment by HeinrichReimer** [comment]
Shouldn't be closed until it's clear this feature won't be implemented or it is actually implemented...

**Comment by HeinrichReimer** [comment]
Take a look at this: https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/ui/widget/InkPageIndicator.java
