### ISSUE TITLE
Readme Update : IntroActivity needs to be the launcher activity

### ISSUE THREAD

**Issue by nisrulz** [PaoloRotolo/AppIntro#118]
Readme.md should mention that the new activity created should be the launcher activity with below intent filters

```xml
 <intent-filter>
       <action android:name="android.intent.action.MAIN"/>
      <category android:name="android.intent.category.LAUNCHER"/>
 </intent-filter>
```

**Comment by Andrew-Quebe** [comment]
With this declaration, the intro would launch every time the app runs. It would be what shows up every time the launcher is set. You would then have to do some hacky launching of the actual main activity through the intro which is incorrect.

What you should do is declare the intro as a standard activity:

``` xml
<activity android:name="com.example.example.intro"
    android:label="@string/app_intro" />
```

Then in your MainActivity class, launch the intro once using a SharedPreference and be done with it. The intro will launch over the main activity and when the user completes the intro, or presses the back button, the intro will close and the main activity will be shown.

I'll update the readme to explain what I just said...but declaring your intro as the main launcher is a bad idea unless you want the intro to show EVERY time the app runs. But I think that would defeat the purpose of the intro library.
