### ISSUE TITLE
Let developers override onCreate()

### ISSUE THREAD

**Issue by HeinrichReimer** [PaoloRotolo/AppIntro#119]
I personally think it is a bad practice to block `onCreate()` so that other developers aren't able to override it anymore.

The only reason I can see you are blocking it is to call this code after `init()` but before the `Activity`lifecycle goes on:

    
    slidesNumber = fragments.size();

    if (slidesNumber == 1) {
        setProgressButtonEnabled(progressButtonEnabled);
    } else {
        initController();
    }

What's the reason for not moving this somewhere later in the lifecycle e.g. in `onStart()` or `onPostCreate()`?

**Comment by Andrew-Quebe** [comment]
There's no need for developers to override onCreate(). If they did, they would be responsible for how the activity is built. By using init(), developers get a simple, narrowed down set of methods to apply to the intro (animations, adding slides, asking for permissions, etc.) but they don't need to do anything else. 

If you're looking for more customization, consider building your own intro where you can do whatever you want in onCreate. But for the library, it would make things more complicated for the developers and deem the library useless.

**Comment by HeinrichReimer** [comment]
I hink you misunderstood me.
It's a common way to override `onCreate()` and then calling `super.onCreate()` as first method call in the overridden method. Every developer does already do that if he's using `Activity` or `AppCompatActivity`. It would just be more common to reuse this pattern.
I don't meant to change any functionality of the library. Actually a developer would only rename his `init()` override to `onCreate()`.
Hopefully you can understand me now.

**Comment by Andrew-Quebe** [comment]
@HeinrichReimer riiigghhhtt...excuse my total lapse of memory of how Java works! I'll talk to @PaoloRotolo and see what he wants to do...I don't want to overstep my editing rights.

**Comment by HeinrichReimer** [comment]
@Andrew-Quebe Great :smiley:

**Comment by danluong** [comment]
I agree with @HeinrichReimer, developers should be able to override onCreate() with a call to super.onCreate() as per standard practice.
