### ISSUE TITLE
Request: GIF image support

### ISSUE THREAD

**Issue by Ayysir** [PaoloRotolo/AppIntro#120]
would be great to have the ability to add gif or animation pictures to the slides

**Comment by HeinrichReimer** [comment]
@Ayysir That's a perfect case for implementing your own `Fragment` for that. As *GIF*s are not the most common images for intros that would not be worth putting another dependency in this library only for handling them.

**Comment by Andrew-Quebe** [comment]
@Ayysir so second what @HeinrichReimer said, you could also put vector assets or other animated stuff in your own custom fragment too. However, I think it would be cool if the library had native support for GIFs. I'll see what I can do.

**Comment by avluis** [comment]
Closing this, as I believe this is outside of the scope of what an `AppIntro` library should focus on.
The tools are already there, make use of them and extend the provided fragments to add support for what you need.
