### ISSUE TITLE
setProgressButtonEnabled on AppIntro class doesnt work

### ISSUE THREAD

**Issue by srihari1988** [PaoloRotolo/AppIntro#122]
I am trying to hide Next button on First Slide and show it on the Second Slide. I set setProgressButtonEnabled(false) on the AppIntro class as well as First Slide. On the Second Slide, I set setProgressButtonEnabled(true). However, I observe that the next button is hidden on second slide. I even tried to use ((AppIntro) getActivity()).findViewById(R.id.next).setVisibility(View.GONE). Even this doesn't work. 

However, ((AppIntro) getActivity()).findViewById(R.id.vuew_pager).setCurrentItem(1) moves to the next slide. 

Please help me on this issue.

**Comment by danluong** [comment]
Can you try building and looking at DisableSwipeIntro1.java for an example? 

To try your example, I changed the following in it:

    @Override
    public void onSlideChanged() {
        if(pager.getCurrentItem() == 1){
            Toast.makeText(getApplicationContext(), "currently item 1", Toast.LENGTH_SHORT).show();
            setProgressButtonEnabled(true);
        }
    }

and

    public void toggleProgressButton(View v) {
        setProgressButtonEnabled(false);
    }

Otherwise if it's still not working, can you post your code/configuration somewhere so I can look at it? It's working for Android 4.4 through 6.0 for me.

**Comment by Andrew-Quebe** [comment]
@srihari1988 did @danluong's suggestion work for you?

**Comment by ParitoshBh** [comment]
Trying to achieve a similar functionality. Though 
`((AppIntro2) getActivity()).setProgressButtonEnabled(false);` works but the button is disabled (or hidden) for all the slides. And with @danluong 's suggested code, I am getting NullPointerException.

Moreover, what I am trying to achieve is ability to have the next button disabled for 2nd (out of 3) slide and enable that button once user confirms a particular action.

**Comment by danluong** [comment]
Again, if you guys are having issues with this, please post a sample project so I can investigate why this is occurring. I'd be happy to look into it, but need more info.

**Comment by srihari1988** [comment]
The issue with my implementation was that the Viewpager was loading multiple pages at once and the code from last fragment gets executed last, thereby affecting my requirement. I overrided the setUserVisibleHint method on the fragment to ensure that the code is running (hiding next button) only when the fragment is visible (active).

@Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);

        if (isVisibleToUser) {
            getActivity().findViewById(R.id.next).setVisibility(View.INVISIBLE);
	}
}

**Comment by avluis** [comment]
Looks like this no longer applies after the recent changes on the library, please reopen this issue if still affected by this issue.
