### ISSUE TITLE
Android 6.0 permission dialog won't show when swiping

### ISSUE THREAD

**Issue by keton** [PaoloRotolo/AppIntro#123]
Hi,

I've noticed that when you're using askForPermissions() on Android 6.0 it works only when you're using next button. When swiping permission popup doesn't show up. For reference here are contents of my init() method:

```java
addSlide(AppIntroFragment.newInstance("First slide", "slide description", R.drawable.ic_slide1, bgColor));
addSlide(AppIntroFragment.newInstance("Permission slide", "slide description", R.drawable.ic_slide2, bgColor));
//here we ask for location and bt admin
askForPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.BLUETOOTH_ADMIN}, 2);

addSlide(AppIntroFragment.newInstance("Third slide", "slide description", R.drawable.ic_slide3, bgColor));
setSwipeLock(false);
```

**Comment by Andrew-Quebe** [comment]
This is intended. The swiping causes weird behavior and doesn't perform properly. Due to swipe listeners, every pixel that the pager is swiped, the request is made. By using askForPermissions, you're disabling swipe automatically.
