### ISSUE TITLE
Hide the tittle bar

### ISSUE THREAD

**Issue by josehdez01** [PaoloRotolo/AppIntro#124]
I'm trying to use this module, but I cant hide the tittle bar.

**Comment by Andrew-Quebe** [comment]
I'm not sure what you mean by title bar. Can you elaborate?

**Comment by josehdez01** [comment]
![screenshot_2015-12-10-14-34-42](https://cloud.githubusercontent.com/assets/16244725/11727904/55c8000a-9f4c-11e5-9482-378aaa8a73d0.png)

**Comment by Andrew-Quebe** [comment]
Ah! I see...that's not good. Can you show me me where you've defined your intro activity in the manifest?

**Comment by josehdez01** [comment]
<activity
            android:name="com.norden.movilride.Intro"
            android:label="@string/app_intro" />

**Comment by josehdez01** [comment]
< activity
            android:name="com.norden.movilride.Intro"
            android:label="@string/app_intro" />

**Comment by StanislavZakharov** [comment]
You should add your theme to styles.xml

Like this: 

<style name="FullscreenTheme" parent="Theme.AppCompat.Light.NoActionBar">

And declare this theme in your theme in manifest in your activity.

**Comment by Andrew-Quebe** [comment]
@josehdez01 which version of Android are you running?

**Comment by Andrew-Quebe** [comment]
@StanislavZakharov in my experience and use of the library, I didn't need to define any theme attrs in the manifest. The library's activity automatically requests that the toolbar be hidden. However, I think this is dependant on the Android version. Support for said Android version might need to be added as a special case.

**Comment by twoh** [comment]
I have this issue too... Xiami Note running on KitKat. How to fix?

**Comment by janakagamini** [comment]
@StanislavZakharov 's suggestion worked for me on Android 6.0, but I @Andrew-Quebe is right, I didn't have to do this before.

**Comment by plopd** [comment]
I have same issue. I have tested it both on pre-/post-lollipop Android. Below is a screenshot which shows that there is some content on top. The layout file of the fragment is:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:paddingTop="0dp"
    android:layout_marginTop="0dp"
    android:paddingBottom="16dp"
    android:paddingLeft="16dp"
    android:paddingRight="16dp"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/tour_imageview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true"/>

</LinearLayout>`

As you can see there is no margin or padding on top, nevertheless the picture clearly shows some content between status bar and fragment.
![example](https://cloud.githubusercontent.com/assets/1534513/16004192/861f43f2-3160-11e6-9ee1-fafb42c34944.PNG)

**Comment by Prawesome** [comment]
I had the same issue and using `getSupportActionBar().hide()` removed it for me

**Comment by clevertrevor** [comment]
I was stuck on this issue and tried `getSupportActionBar().hide()`, along with several other solutions, but none of them worked. My app does not use AppCompat, but changing the theme of the activity that used AppIntro to `Theme.AppCompat.NoActionBar` successfully removed the ActionBar.

**Comment by lykmapipo** [comment]
@josehdez01 

This works perfect

```xml
 <style name="AppFullScreenTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>
    </style>
```

**Comment by avluis** [comment]
Looks like this no longer applies after the recent changes on the library, please reopen this issue if still affected by this issue.
