### ISSUE TITLE
Adding common elements to all slides?

### ISSUE THREAD

**Issue by jlubeck** [PaoloRotolo/AppIntro#125]
Hi, I'm trying to add some elements that should stay in place while you swipe through the slides.

How can I do that?

Thanks!

**Comment by jlubeck** [comment]
Ok, I already did it with this inside init:

        FragmentManager fragmentManager = getFragmentManager();
        FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();

        CustomFragment fragment = new CustomFragment();
        fragmentTransaction.add(android.R.id.content, fragment);
        fragmentTransaction.commit();

If there is a better way, I'd love to know!

**Comment by Andrew-Quebe** [comment]
What elements are you talking about?

**Comment by girish3** [comment]
@jlubeck you are trying to add the fragment to the root view of the activity which is a bad practice. There do not seem to be any provision for that in the library, instead you can directly tweak and add elements in intro_layout.xml inside the library itself.

**Comment by avluis** [comment]
Looks like this no longer applies after the recent changes on the library, please reopen this issue if still affected by this issue.
