### ISSUE TITLE
How can I move the position of the Pager dots?

### ISSUE THREAD

**Issue by jlubeck** [PaoloRotolo/AppIntro#126]
O had to add some elements to the bottom of the screen that appear on top of the dots. Is there a way to  move them up?

Thank you!

**Comment by Andrew-Quebe** [comment]
Currently, the library doesn't support moving the dots around.

To clarify, you're talking about the dots on the AppIntro2 class correct? If you're talking about the AppIntro class, you're not only referring to the dots, but that entire bottom bar. Which do you want?

**Comment by Andrew-Quebe** [comment]
@jlubeck closing this issue until clarification is provided for the above questions.

**Comment by jlubeck** [comment]
I´m talking about these dots:
![Alt text](https://monosnap.com/file/n5McMDnIdD25tRbpZFIKqvmaDBAhsr.png)

(sorry about taking this long to respond)
