### ISSUE TITLE
Error:(42, 66) error: cannot find symbol variable skip

### ISSUE THREAD

**Issue by Heromine** [PaoloRotolo/AppIntro#13]
in MyIntro.java i got this error:
Error:(42, 66) error: cannot find symbol variable skip

the code is: 

    @Override
    public void onSkipPressed() {
        loadMainActivity();
        Toast.makeText(getApplicationContext(),getString(R.string.skip), Toast.LENGTH_SHORT).show();
    }

line:
        Toast.makeText(getApplicationContext(),getString(R.string.skip), 

what's the problem?

**Comment by ikrum** [comment]
Maybe you imported wrong R file !

**Comment by Heromine** [comment]
Already fixed thanks
