### ISSUE TITLE
colorprimarydark is not working when i extend appintro2, it show greys color.

### ISSUE THREAD

**Issue by 123pankaj** [PaoloRotolo/AppIntro#132]
this is my theme, which i am using in this activity in manifest.

  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

![device-2015-12-22-180544](https://cloud.githubusercontent.com/assets/3352489/11955293/ad6d3d3c-a8d6-11e5-8326-ed411a446570.png)

**Comment by nicopasso** [comment]
Same problem here.
If I use 
```java
setIndicatorColor(Color.GREEN, Color.BLUE);
```
all works fine.

However if I try to use my custom colors (e.g. R.color.color_primary or R.color.my_custom_color) the indicators' color is wrong.

**Comment by firetrap** [comment]
Same here :(

**Comment by flavio20002** [comment]
I add this in my Intro Activity Class
`
public class MyIntro extends AppIntro {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            getWindow().getDecorView().setSystemUiVisibility(
                    View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
        }`
