### ISSUE TITLE
Change onSlideChanged signature or remove it. 

### ISSUE THREAD

**Issue by tasomaniac** [PaoloRotolo/AppIntro#134]
I've looked at your samples, `onSlideChanged` method is not used at all.

It is not logical to use it because it does not give anything in the parameters. It should give the page position information in the parameters.

**Comment by Andrew-Quebe** [comment]
@tasomaniac this is scheduled to be fixed in the next release. It wasn't something I realized until after we released 3.30 and decided to fix it in the next one.

**Comment by tasomaniac** [comment]
Thank you for the comment. I looked for but couldn't find a related issue. If you have the issue somewhere else, please feel free to close this.

**Comment by Andrew-Quebe** [comment]
@tasomaniac you're the first to mention it here...even though it's on my list of things to fix, I'll probably keep it open so someone else doesn't come along and make a new issue :)

**Comment by avluis** [comment]
Closing -- issue addressed in prior commit.
