### ISSUE TITLE
Overdraw in AppIntro layouts. 

### ISSUE THREAD

**Issue by tasomaniac** [PaoloRotolo/AppIntro#142]
Layouts have lots of unnecessary background colors. 

You have theme color + couple of background colors + AppIntroFragment's `bgColor`.

I can count 4 useless backgrounds in `intro_layout.xml` file.

**Comment by avluis** [comment]
Closing -- addressed with prior commit.

**Comment by tasomaniac** [comment]
Would be great to mention the commit here.
