### ISSUE TITLE
how to hide skip , done and dot buttons in the library.

### ISSUE THREAD

**Issue by ashokslsk** [PaoloRotolo/AppIntro#148]
Hi how to hide the done and next skip buttons ...

**Comment by girish3** [comment]
You can use the following methods to hide next(done is on the last page) and skip button

```java
showSkipButton(false)
showDoneButton(false) // this method is deprecated though instead use 
setProgressButtonEnabled(false)
```

If by dot button you mean dot indicator then there is no any provision for hiding it but you can use the
progress indicator or your own custom indicator.

```java
setCustomIndicator(IndicatorController controller)
setProgressIndicator()
```

**Comment by Andrew-Quebe** [comment]
As @girish3 already said, you can use the showSkipButton() and showDoneButton() methods to hide them. Please consider fully reading the README and/or the Wiki before opening a new issue.
