### ISSUE TITLE
Push Notification is Displayed Before Intro is Done

### ISSUE THREAD

**Issue by agnanzakariya** [PaoloRotolo/AppIntro#149]
Currently I developing app news for online media. Maybe this issue is suitable as internal problem in developing my MainActivity. Since I got a lot problem to implement this, but finally i did it, slides works well. However, the issue still exist. I have a Push Notification Service here. Previously, before I implement Appintro, when my app start and showing splash page. Later, push notification service will start (Notification for recently added new posting). 

Now after adding Appintro, my push notification conflict with Appintro, after splash page disappear and slides intro show, push notification triggering at the same time and getting crash my app. However, when I start again my app, is ok no problem because the slides just show once appearance when application literally start. For temporary I shutdown the trigger.

 According your code : Show the Intro Once
```
@Override
protected void onCreate(Bundle savedInstanceState) {

    ...

    //  Declare a new thread to do a preference check
    Thread t = new Thread(new Runnable() {
        @Override
        public void run() {
            //  Initialize SharedPreferences
            SharedPreferences getPrefs = PreferenceManager
                    .getDefaultSharedPreferences(getBaseContext());

            //  Create a new boolean and preference and set it to true
            boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

            //  If the activity has never started before...
            if (isFirstStart) {

                //  Launch app intro
                Intent i = new Intent(MainActivity.this, DefaultIntro.class);
                startActivity(i);

                //  Make a new preferences editor
                SharedPreferences.Editor e = getPrefs.edit();

                //  Edit preference to make it false because we don't want this to run again
                e.putBoolean("firstStart", false);

                //  Apply changes
                e.apply();
            }
        }
    });

    // Start the thread
    t.start();

    ...
}
```

And this is my push notification trigger :
```
//Starting the Service for Push/Status Notification
            startService();
```
The condition what I want is, the slides can hold my push notification service before I click skip or done. Here full my MainActivity code http://pastebin.com/0czBr837 
Kindly suggest for this problem?

Thanks in advance.

**Comment by Andrew-Quebe** [comment]
The answer here is simple. You're declaring a new intent and creating a new activity over your main activity. There are no errors in your code...however, you're calling everything in the onCreate method of your MainActivity. Basically, an activity is created, and your service and all that other code is running on the other activity thread. Meanwhile, the user sees the new intro activity thread. 

My solution: start your notification service after the intro has been completed. This will combat both the first time your app is launched as well as when a user returns. Check out the onDonePressed() method. I'm sure you can do some service starting from it instead...services can be launched from anywhere in your app's UI. Ensure you start your service BEFORE you call finish() in the intro class.

**Comment by avluis** [comment]
Looks like this no longer applies after the recent changes on the library, please reopen this issue if still affected by this issue.
