### ISSUE TITLE
Create 2 apps

### ISSUE THREAD

**Issue by Heromine** [PaoloRotolo/AppIntro#15]
I added this intro to my app but when i install it to may mobile phone i get two apps:
My Intro and My App name.

So if i open my intro i will have the slides and after the My App Name.
If i open My App Name i will not have My Intro.

if i unistall My Intro, i will unistall both, same if i unistall My App Name

So how can i hide the My Intro (apk) that will only exists in My App Name?

scusa ma sono noob

**Comment by PaoloRotolo** [comment]
Hi,
you don't have to create another App for the intro.
Just put the lines of code (see README) in a new **Activity**. 

If you're new in Android Development, read this tutorial :)
http://developer.android.com/training/basics/firstapp/starting-activity.html

**Comment by Heromine** [comment]
I know but this is an issue. I didn't want it.
Should i link the intro activity in on create of the main?

**Comment by PaoloRotolo** [comment]
Look the example app. Create an activity that extends AppIntro, for example name it "IntroActivity".
Then, in MainActivity, start IntroActivity when you want to show the intro.

**Comment by Heromine** [comment]
ok i fixed by starting the activity on Main's onCreate firstrun
