### ISSUE TITLE
Resources$NotFoundException while setting setNavBarColor

### ISSUE THREAD

**Issue by hoseinit** [PaoloRotolo/AppIntro#153]
Hi, 
I face the below error while I add `setNavBarColor(Color.parseColor("#3F51B5"));` to my `AppIntro` Activity.
`java.lang.RuntimeException: Unable to start activity ComponentInfo{net.myapp.app/net.myapp.app.activity.WelcomeActivity}: android.content.res.Resources$NotFoundException: Resource ID #0xffff0000
`

**Comment by Andrew-Quebe** [comment]
Which version of the library are you using?

**Comment by avluis** [comment]
I just took a look at this method on `AppIntro` and `AppIntro2` since I made use of it not that far back.

```
public void setNavBarColor(String Color) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            getWindow().setNavigationBarColor(android.graphics.Color.parseColor(Color));
        }
    }
```

You need to pass in a String, so remove `Color.parseColor()` and you'll be golden.

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.
