### ISSUE TITLE
New release on maven, but not on github

### ISSUE THREAD

**Issue by SandroMachado** [PaoloRotolo/AppIntro#157]
There is any reason why the new release (`3.4.0`) is already on maven, but it is not created on github? There are some issues that need to be addressed before the `official` release?

**Comment by Andrew-Quebe** [comment]
3.4.0 was a bit of an emergency release as one developer needed a function to work properly. 3.4.1 will address the issues on Github.

**Comment by SandroMachado** [comment]
Ok, great, just as well. I was one of the developers who was really excited waiting to the new features. Thanks
