### ISSUE TITLE
Android Studio Can't resolve dependency

### ISSUE THREAD

**Issue by hossein73** [PaoloRotolo/AppIntro#160]
hi,
when i try to add your AppIntro to my project in Android Studio,i see this error :
Error:(34, 13) Failed to resolve: com.github.PaoloRotolo:AppIntro:v3.3.0

**Comment by girish3** [comment]
See if you are missing this in project gradle file
```
repositories {
        jcenter()
    }
```
or else I cannot know the problem for sure, so paste your gradle file here

**Comment by hossein73** [comment]
tnx bro, it's fixed by adding jcenter()
repositories {
    jcenter()
    maven {
        url "https://jitpack.io"
    }
}

**Comment by Andrew-Quebe** [comment]
@hossein73 glad you  got it working.
