### ISSUE TITLE
How to call AppIntro at any time I need?

### ISSUE THREAD

**Issue by diskzzokejs** [PaoloRotolo/AppIntro#161]
Situation: 

I have **MainActivity** and onCreate(Bundle savedInstanceState) I'm calling:
`appManual myAppManual = new appManual();
        myAppManual.init(savedInstanceState);`

But my app crashes on launching MainActivity.
What I'm doing wrong?

**Comment by diskzzokejs** [comment]
Im getting error:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{APP.PACKAGE.NAME/APP.PACKAGE.NAME.MainActivity}: java.lang.NullPointerException`

**Comment by diskzzokejs** [comment]
And other one:

` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.paolorotolo.appintro.PagerAdapter.notifyDataSetChanged()' on a null object reference`

**Comment by Andrew-Quebe** [comment]
If you've read the readme, you need to build an intent that launches the intro activity. In the activity's init method, you can add your slides and decide animations. The way your initializing your intro is what your problem is.
