### ISSUE TITLE
AppIntro takes too much memory?

### ISSUE THREAD

**Issue by t4deon** [PaoloRotolo/AppIntro#163]
While playing around with AppIntro I noticed that the Intro allocated up to 20MB RAM for the first slide and around 10 MB RAM for the next ones. It's obvious that this causes an OutOfMemoryError very quickly.   
I add the slides like this: ``` addSlide(AppIntroFragment.newInstance(title, description, image, background_colour));```    
All slides just contain some text and one image. Every image is just around 10kb.
Can you help me with this please?

EDIT:
This is my Intro class:
```
public class Intro extends AppIntro {

    @Override
    public void init(@Nullable Bundle bundle) {

        addSlide(AppIntroFragment.newInstance("title", "some description",
                R.drawable.intro1, android.R.color.white));
        addSlide(AppIntroFragment.newInstance("title", "some description",
                R.drawable.intro2, android.R.color.white));
        addSlide(AppIntroFragment.newInstance("title", "some description",
                R.drawable.intro3, android.R.color.white));
        addSlide(AppIntroFragment.newInstance("title", "some description",
                R.drawable.intro4, android.R.color.white));


        showSkipButton(false);


    }

    @Override
    public void onSkipPressed() {

    }

    @Override
    public void onNextPressed() {

    }

    @Override
    public void onDonePressed() {
        finish();
    }

    @Override
    public void onSlideChanged() {

    }
    }
```

**Comment by ParitoshBh** [comment]
Similar thing happened. Try adding android:largeHeap="true" attribute in application tag and see if it works.

**Comment by t4deon** [comment]
OK, I think this is not an AppIntro issue. According to [this answer on Stackoverflow](http://stackoverflow.com/a/29728695/4909414) it is a general issue when working with images on Android.   
I use [Android Universal Image Loader](https://github.com/nostra13/Android-Universal-Image-Loader) now for loading my images into the image view and everything works fine.

**Comment by ParitoshBh** [comment]
Agreed. It might be an android issue rather than library, I didn't have time to look into library code. Anyway, just my 2 cents :)
