### ISSUE TITLE
How posible translate skip and done

### ISSUE THREAD

**Issue by webserveis** [PaoloRotolo/AppIntro#164]
Set support globalization string in addSlide(AppIntroFragment.newInstance() button SKIP and DONE

**Comment by Andrew-Quebe** [comment]
You can define local translations of your app strings and then pass them into the addSlide method. The library supports this automatically.

**Comment by voghDev** [comment]
Can you specify a bit more how to do that please? I'd be interested in customizing/translating skip and done button.

Am using version `3.3.0`

**Comment by webserveis** [comment]
I solved add strings.xml

	<string name="skip_button">SKIP</string>
	<string name="done_button">GO!</string>

**Comment by voghDev** [comment]
Good, @webserveis solution worked with version `3.3.0` of the library

Thanks!

**Comment by Andrew-Quebe** [comment]
@voghDev translations can always be submitted in the form of a pull request like #291 if you want to not have to overwrite anything.

**Comment by voghDev** [comment]
Oh sure, if there are no spanish translations for the buttons, I'll submit them

**Comment by avluis** [comment]
There aren't any -- will you be using `omitir` or `pasar` for `skip` and `salir` or `hecho` for `go (done)`?
