### ISSUE TITLE
Transparent navigation bar

### ISSUE THREAD

**Issue by djslin99** [PaoloRotolo/AppIntro#165]
I'm using a transparent navigation bar in my app. But I have the problem, that AppIntro controls are under the navigation drawer. Can you add an option to add margin at the bottom?

Thank you ;)
djslin99
![device-2016-02-01-213302](https://cloud.githubusercontent.com/assets/5816305/12730295/9c826482-c92b-11e5-8c2e-ea32a6b947fa.png)

**Comment by mntgoat** [comment]
I've just started having this issue all of the sudden. Wondering when the next release is scheduled?
Thanks.

**Comment by avluis** [comment]
@djslin99 
Can you create a styles.xml for v21 and add the following:

```xml
<item name="android:windowTranslucentStatus">true</item>
<item name="android:windowTranslucentNavigation">true</item>
<item name="android:fitsSystemWindows">true</item>
```

Please reply with results.

**Comment by avluis** [comment]
Looks like this no longer applies after the recent changes on the library, please reopen this issue if still affected by this issue.
