### ISSUE TITLE
Adding slide after init

### ISSUE THREAD

**Issue by DHM47** [PaoloRotolo/AppIntro#168]
In my app I'm using this library as Introduction/tutorial.
In one case the user is presented with two options, what he selects will determine  what the next slides will be.
For now I'm using reflection in order to do that, because the page indicator and next/done button are not updated. 

This is what I'm using
```java
private void updateSlideNumber(int slidesNumber){
        try {
            final Class<?> clazz = AppIntro.class;

            //Update "slidesNumber" so Next/Done behaves correctly
            final Field field = clazz.getDeclaredField("slidesNumber");
            field.setAccessible(true);
            field.set(getActivity(),slidesNumber);

            //Remove the old page indicator
            FrameLayout indicatorContainer = (FrameLayout) getActivity().findViewById(com.github.paolorotolo.appintro.R.id.indicator_container);
            indicatorContainer.removeAllViews();

            //Add new page indicator which represents the new amount of slides 
            Method method = clazz.getDeclaredMethod("initController");
            method.setAccessible(true);
            method.invoke(getActivity());

        } catch (final Exception ignored) {}
    }
```

**Comment by Andrew-Quebe** [comment]
What is your point here? I don't see what your question is. Could you elaborate?

**Comment by DHM47** [comment]
In the method "init" I add a slide with two buttons 
When button 1 is clicked slides A and B are added (addSlide(new A)....) 
When button 2 is clicked slide C is added. 

If I call "addSlide" from the button's on click listener the slides are added but the problem is the indicator stays showing that there is only one slide (only one dot) and the Done button stays Done.
 
What should happen is that the indicator should update and show either 2 or 3 dots depending on user's choice. 
Add after clicking on the button even though there are new slide the "Done" only shows up on the last slide that was added in init. 

If this is still not clear I'll make a before and after screen recording.

**Comment by DHM47** [comment]
Should I do the fix and make a pull request of it ?
Would that clarify it?

**Comment by mveroukis** [comment]
Hey DHM47, I ran into the same problem. The intro to my app requires the user does some setup before they can get to the last slide. However, when I make the call to addSlide() outside of the intro() method, it adds the slide but the dots on the bottom don't reflect that, neither does the "Done" button. I haven't had time to look at the code but I might do that. Has there been any progress with this issue?

**Comment by DHM47** [comment]
@mveroukis use the method I wrote "updateSlideNumber" after adding the slides. But you'll need to know the number of slide after adding and pass it to the method.

**Comment by mveroukis** [comment]
I see, slideNumber is protected, so I can bump that number after I call addSlide() from a derived class. Perhaps even better would be to override addSlide() and have it bump the number whenever a slide is added.

**Comment by DHM47** [comment]
@mveroukis How would you do that exactly ?
I'm going to fork the project and implement my fix. If the library author likes it. He can merge it.

**Comment by mveroukis** [comment]
Like I said I only glanced at the code, so I'm not sure what's required. However, I noticed that in addSlide() a call is made to mPagerAdapter.notifyDataSetChanged() BUT the _slidesNumber_ member variable is set AFTER the call to init() from onCreate(). What if instead we made addSlide() increment the slidesNumber member variable every time a slide is added? Then we wouldn't need to to set the slideNumber after the call to the fragmetns.size() after the call to init(). We could then also create a removeSlide() method that could allow for the dynamic removal of a slide outside of the init() method. Does that make sense? Do you have to make any calls after updatng the slideNumber member to make it all work?

**Comment by mveroukis** [comment]
I have a fork with what works for me: https://github.com/mveroukis/AppIntro

It's not a general purpose fix which is why I decided against creating a pull request. What I've done is two things: AppIntro2.addSlide() increments slidesNumber and DefaultIndicatorController.initialize() calls removeAllViews(). This allows for calling addSlide() outside of init(), however, you'll need to also call initialize() on the indicator controller. It's a fix that puts all the changes into the DefaultIndicatorController which means it's a bit of a side-effect, ideally we'd add methods to the IndicatorController interface to enforce this behavior for all controllers that implement the interface. So, perhaps adding something like "addSlide()" to the interface. Anyway, that's all I needed for my purpose so I didn't explore it any further. I imagine anyone using AppIntro instead of AppIntro2 would just need to do the same with addSlide().

**Comment by DHM47** [comment]
@mveroukis take at look at my fork. I did everything in AppIntro class. I can't judge which is better (not enough knowledge or experience) so please compare them. And tell me what you think.

**Comment by mveroukis** [comment]
I took a quick look. It seems we do similar things but in different places. Does yours handle the case when a new fragment is added (outside of the init() method) and the user is NOT at the first fragment? I know that calling the default controller's inititalize() method jumps back to the first fragment and so I added some code there to make it not do that.

**Comment by DHM47** [comment]
@mveroukis yes, I'm actually executing the code from the second fragment's class.

**Comment by avluis** [comment]
Closing -- issue out of library scope -- if there is enough interest for this, I'll probably program it myself if required.
So I'll be gauging interest.
