### ISSUE TITLE
setIndicatorColor doesn't work

### ISSUE THREAD

**Issue by beilianhu** [PaoloRotolo/AppIntro#174]
I try to set Indicator Color:`setIndicatorColor(0x00000000,0x00505050);`

but Indicator disappeared.

am I do some thing wrong?

Thank you!

**Comment by Andrew-Quebe** [comment]
You're using what appear to be memory addresses for the color. Try this: `color.parseColor("#ffffff");`.

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.
