### ISSUE TITLE
Handle input in slide / get instance of current slide

### ISSUE THREAD

**Issue by jossiwolf** [PaoloRotolo/AppIntro#175]
Hello,
I'm trying to make an interactive intro (see #92), but I couldn't find a solution. I have a class _SimpleSlide_, containing a save function.
My idea was to get the current instance of the slide and call the function from there, but I didn't find a way to do this. 

<a href="https://gist.github.com/jossiwolf/8da2a607153e116c588b">SimpleSlide.java</a>

**Comment by avluis** [comment]
Closing -- feature merged.
