### ISSUE TITLE
setNavBarColor & askForPermissions

### ISSUE THREAD

**Issue by iBobb** [PaoloRotolo/AppIntro#179]
` setNavBarColor(Color.parseColor("#3F51B5")); `
This is from your example and it gives me an error:

> java.lang.string cannot be applied to int

Also, those 2 methods do nothing:

>         askForPermissions(new String[]{Manifest.permission.INTERNET}, 2);
        askForPermissions(new String[]{Manifest.permission.ACCESS_NETWORK_STATE}, 2);

I've got 3 slides and the permissions are declared in my Manifest. I tried removing them from there but then my app doesn't work because the permissions weren't granted.

I'm running CyanogenMod 13 on Moto G xt1032
I am also running Android Studio 2 Beta 5 with Gradle 2.0.0-beta5

Thanks!

**Comment by Andrew-Quebe** [comment]
setNavBarColor() requires a String to be passed to it. Color.parseColor returns an int, not a String. Simply pass your color hex to the library method in String format, and the library will utilize Color.parseColor. Check the source code of the method for more info.

Regarding your permissions issues, please provide your manifest file and the intro activity code (the whole file).

**Comment by Andrew-Quebe** [comment]
Closing issue until the above requests are met.

**Comment by iBobb** [comment]
Sorry for taking the time to respond. I got the setNavBarColor() method running the way you told me to use it, however, in the sample code here it's not explained clearly as I already said.

About the permissions, it's my mistake, I was talking about the INTERNET and INTERNET_ACCESS permissions which I found out you don't need to ask permission for in Marshmallow. Thank you.
