### ISSUE TITLE
AppIntro Fullscreen

### ISSUE THREAD

**Issue by 0wzZZzz6** [PaoloRotolo/AppIntro#185]
How to full screen the appintro2?

**Comment by iBobb** [comment]
Can't you just hide the status bar like that:
` showStatusBar(false);`

You could also change the Navigation Bar (at the bottom) color to match the background of the whole screen for example to give a more uniform effect if you are going to focus on a colourful icon in the middle.

`setNavBarColor("#2D2D2D");` - just change the hex value to a desired colour.
