### ISSUE TITLE
Using Picasso/Glide to Load Images

### ISSUE THREAD

**Issue by CeJienAJPC** [PaoloRotolo/AppIntro#187]
I would like to know if Images can be added to slides using Picasso/Glide libraries?

Could you please provide some sample code.

Regards

**Comment by avluis** [comment]
Depending on how your slides are implemented, it is simply a matter of calling the appropriate load method for that particular slide.
In your situation, the following methods will be essential:

```java
    @Override
    public void onSkipPressed() {
    // Do something when users tap on Skip button.
    }

    @Override
    public void onDonePressed() {
    // Do something when users tap on Done button.
    }

        @Override
    public void onSlideChanged() {
    // Do something when the slide changes.
    }

    @Override
    public void onNextPressed() {
    // Do something when users tap on Next button.
    }
```
By making use of `pager.getCurrentItem()` and the resource ID of an ImageView, you could make your Glide.load() call where needed.

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.

**Comment by jehad-suliman** [comment]
Iam Using SampleSlide 
 
How can i use Picasso to load the images ??

**Comment by alexbertis** [comment]
Would be OK if somebody answered exactly **HOW TO ACCESS THE IMAGEVIEW DIRECTLY FROM YOUR ACTIVITY EXTENDING** `AppIntro`...
