### ISSUE TITLE
i wanna use this in my app and wanted permissions

### ISSUE THREAD

**Issue by yashgoyalMIT** [PaoloRotolo/AppIntro#188]
I am developing an android app which may be used for commercial use in future and i wanted to know what is the best and safest legal way to include your "first time tutorial" code in my application. I do not have much idea about licenses so if you could let me know whats the best option i have here, that would be highly appreciated.

**Comment by Andrew-Quebe** [comment]
@yashgoyalMIT AppIntro is licensed under the Apache 2.0 license. You are free to do what you want according to the license. [Read the license.](https://github.com/PaoloRotolo/AppIntro/blob/master/LICENSE)
