### ISSUE TITLE
Blending background colors

### ISSUE THREAD

**Issue by toyongbanatero** [PaoloRotolo/AppIntro#19]
Hello. Great work with this. I'm can't say that I'm very noob but also not very good in Android. I do not know If if missing something but is it possible to make the background colors of every Fragment slides blending every page (i.e, from blue background of first slide, blending to magenta background color which is very much like how Google's app intros were implemented)? Thanks.

**Comment by PaoloRotolo** [comment]
Working on it right now :)
I'll push a new release late today.

**Comment by toyongbanatero** [comment]
Thank you in advanced! Waiting for it!
It will be very great!

**Comment by PaoloRotolo** [comment]
AppIntro 1.4.0 is released.
Please read README to see how to implement Fade effect/custom animations :)
