### ISSUE TITLE
Feature request : 2 "done" buttons

### ISSUE THREAD

**Issue by fabreax** [PaoloRotolo/AppIntro#192]
Hi,

Is it possible to add 2 "done" buttons (for instance, "Buy" and "Subscribe") ?

Thanks

**Comment by avluis** [comment]
@fabreax I would suggest making those two buttons as part of one of your slides.
While the idea of an additional `done` button is not a bad one, I don't really see the need for it to be in the actual library -- that is unless most developers implementing `AppIntro` require a second `done` button as well.
Please update this issue if you have better reasoning than mine as to why this should be a library feature.
