### ISSUE TITLE
Request: insert method after slide

### ISSUE THREAD

**Issue by avluis** [PaoloRotolo/AppIntro#195]
So I have noticed how useful this library is to get going - very good on that regard.
I have been able to address (at least for new users) the whole permission thing with one line of code.

Now, this is what I have come across:

Just how you'd write, `askForPermissions(new String[]{Manifest.permission.CAMERA}, 2);` in order to ask for a permission after slide 2, I would love to see the same for my own methods.

e.g.;
`runAfterSlide(myCustomMethod(), slideNumber);`

While I can essentially do the same with a Fragment/Intent, would this not make it a bit easier while following the existing pattern that `askForPermissions()` introduces.

Additionally, I think something like this can address issue #175, #168 and #92.

**Comment by DHM47** [comment]
(not part of the library development team) For now you can use "onSlideChanged" in it get the Pager and from it get the current slide number. Using an if on that number to do something after slide 2.

**Comment by avluis** [comment]
@DHM47 
Awesome pointer.
I was able to implement what I needed with that helpful nudge, so thanks again!
