### ISSUE TITLE
How to add Scrolling support for the fragments ?

### ISSUE THREAD

**Issue by lokeshsuhas** [PaoloRotolo/AppIntro#197]
Hi,

I tried to add the scrolling support to the fragments, but the view pager is not scolling the fragment i have even tried by adding the following event for the pager.

    pager.setOnTouchListener(new View.OnTouchListener() {
        @Override
            public boolean onTouch(View v, MotionEvent event) {
                v.getParent().requestDisallowInterceptTouchEvent(true);
                return false;
            }
        });

But no luck, any leads will be helpful

**Comment by avluis** [comment]
Having a scrolling view inside another view that scrolls as well usually does not work out too well unless a few things are done beforehand.
Please give [this](http://stackoverflow.com/a/2655740/1615876) a read for a possible pointer.

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.
