### ISSUE TITLE
why when i set titleColor my title missed?

### ISSUE THREAD

**Issue by DearZack** [PaoloRotolo/AppIntro#198]
public static AppIntroFragment newInstance(CharSequence title, CharSequence description, int imageDrawable, int bgColor, int titleColor, int descColor) 

i use this method to creat a AppIntroFragment ,but title and description missed.

public static AppIntroFragment newInstance(CharSequence title, CharSequence description, int imageDrawable, int bgColor)
this is OK

**Comment by avluis** [comment]
This is what is used to initialize that class:

    public static AppIntroFragment newInstance(CharSequence title, CharSequence description, int imageDrawable, int bgColor) {
        return newInstance(title, description, imageDrawable, bgColor, 0, 0);
    }


    public static AppIntroFragment newInstance(CharSequence title, CharSequence description, int imageDrawable, int bgColor, int titleColor, int descColor) {
        AppIntroFragment sampleSlide = new AppIntroFragment();

        Bundle args = new Bundle();
        args.putCharSequence(ARG_TITLE, title);
        args.putCharSequence(ARG_DESC, description);
        args.putInt(ARG_DRAWABLE, imageDrawable);
        args.putInt(ARG_BG_COLOR, bgColor);
        args.putInt(ARG_TITLE_COLOR, titleColor);
        args.putInt(ARG_DESC_COLOR, descColor);
        sampleSlide.setArguments(args);

        return sampleSlide;
    }

What color are you setting your title to and what theme is it applied if any?

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.
