### ISSUE TITLE
Proguard?

### ISSUE THREAD

**Issue by meNESS** [PaoloRotolo/AppIntro#209]
Hi,

I cannot build my project without your library proguard text. what are they? following line doesn't work.

`-keep class com.github.paolorotolo.** {*;}`

**Comment by avluis** [comment]
Hey there, that's what I'm using as well, but you must make sure of a few other things than just that (which apply to the rest of your app, not just this library) for proguard to work.

What else have you defined on your proguard config?

For example, here is a good starting point for Android apps in general:
https://github.com/avluis/Hentoid/blob/optimize/app/proguard-android.txt

And here is what I need for this app to work (this is NOT all that is needed for this project):
https://github.com/avluis/Hentoid/blob/optimize/app/proguard-project-app.pro

The rest of the proguard rules are here:
https://github.com/avluis/Hentoid/tree/optimize/.proguard

This is what I have on gradle for all that to work:

    // Library specific proguard files
    FileCollection proGuardFileCollection = files { file('../.proguard/').listFiles() }
    proguardFiles(proGuardFileCollection)

    // Default proguard files & project app specific rules
    proguardFile getDefaultProguardFile('proguard-android.txt')
    proguardFile 'proguard-project-app.pro'

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.

**Comment by meNESS** [comment]
@avluis Thanks for your help but your sulution didn't worked at that time. I'm currently using [EasyIntro](https://github.com/meNESS/EasyIntro). Thanks again.

**Comment by avluis** [comment]
Would you care to share what libraries you are using in order to figure out the proguard configuration?
If you could post your app's build.gradle, that would be lovely.
