### ISSUE TITLE
Launching app is really slow

### ISSUE THREAD

**Issue by BGomes17** [PaoloRotolo/AppIntro#213]
Hi, first of all thanks foryour work, this intro looks really nice.

I added this intro to my project and it looks really cool. However I'm using the code that you provided to Show the Intro Once and everything works just fine except that the app is really slow to star, it takes about 6 seconds to launch. If I click to show the Intro it appears almost immediatly  but on the first run is really really slow.

Do you know what could be the problem?

Note: I tested in LG G4 and LG G3 both with Android 6.0 and Xiaomi Note 3 with Android 5.0 and all the devices have this problem.

Thanks in advance,

**Comment by AnimbusDev** [comment]
Have this issue too

**Comment by Andrew-Quebe** [comment]
This may be the result of running a background thread to check the preference. You might try taking the preference code out of the thread so that it runs in the same activity...I know that kind of sounds contradictory to speeding up the app, but it is worth a shot. I haven't been able to reproduce the slowness you're talking about, but I'm on stock hardware so that may be the reason.

**Comment by Andrew-Quebe** [comment]
The code would look like this:

```
SharedPreferences getPrefs = PreferenceManager
                    .getDefaultSharedPreferences(getBaseContext());

//  Create a new boolean and preference and set it to true
boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

//  If the activity has never started before...
if (isFirstStart) {

    //  Launch app intro
    Intent i = new Intent(MainActivity.this, DefaultIntro.class);
    startActivity(i);

    //  Make a new preferences editor
    SharedPreferences.Editor e = getPrefs.edit();

    //  Edit preference to make it false because we don't want this to run again
    e.putBoolean("firstStart", false);

    //  Apply changes
    e.apply();
}
```

**Comment by avluis** [comment]
If it helps anyone, I take care of hiding any initial load time with a simple Splash Activity that does not inflate any layouts - you can read more about that approach [here](https://www.bignerdranch.com/blog/splash-screens-the-right-way/).

As for my implementation of that, your code would look something like this:

```
public class SplashActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (AndroidHelper.isFirstRun()) {
            Intent intent = new Intent(this, IntroSlideActivity.class);
            startActivity(intent);
            overridePendingTransition(R.anim.fade_in, R.anim.fade_out);
            finish();
        } else {
            AndroidHelper.launchMainActivity(this);
            overridePendingTransition(R.anim.fade_in, R.anim.fade_out);
            finish();
        }
    }
}
```

That `AndroidHelper `class is simply an Utility class.
Then to make grabbing prefs as quick as possible, I can pass  application context or simply have the application class grab an instance of `SharedPreferences` for me.

So the `isFirstRun()` method looks a bit like this:

```
public static boolean isFirstRun() {
        return SampleApplication.getAppPreferences()
                .getBoolean(ConstantsPreferences.PREF_FIRST_RUN,
                        ConstantsPreferences.PREF_FIRST_RUN_DEFAULT);
    }
```

`getAppPreferences `is where this is done: 

As a variable:

```
public static SharedPreferences getAppPreferences() {
        return sharedPreferences;
    }
```

And onCreate():

`sharedPreferences = PreferenceManager.getDefaultSharedPreferences(this);`

When all that is done, after wiping application data, it only takes a second to go from the splash screen and to my implementation of this library (I'm using `AppIntro2`).

I believe @Andrew-Quebe 's implementation is the way to go, but if you don't mind that splash screen, you can make very good use of it.

**Comment by TurKurT656** [comment]
same issue here. i made a splash screen activity and the problem is now solved. but i dont like splash screens. they are waste of time

**Comment by avluis** [comment]
Well, while I don't have the same opinion in regards to splash screens (they can be a bother if they are implemented just to be there), but they are useful when your app has plenty to load (I love snappy interfaces).

**Comment by guri073** [comment]
Same Issue Here

**Comment by avluis** [comment]
@BGomes17, @AdrianVovk, @TurKurT656 & @guri073:
Please post your app (module) level build.gradle - would like to try and get more detail about what is going on here.

**Comment by AdrianVovk** [comment]
@avluis Take a look at the entire project 
https://github.com/SubstanceMobile/GEM

**Comment by avluis** [comment]
@AdrianVovk Thanks for sharing - will be taking a look at it in a bit.

**Comment by avluis** [comment]
@AdrianVovk I'm not particularly looking to fix your app here :smiling_imp:, I am more interested in running metrics on the app and segregating any issues with AppIntro (seeing what is causing it to be slow on your project).
If I happen to fix any issue in your app, call it a collateral damage from my coding OCD :+1:.

**Comment by AdrianVovk** [comment]
@avluis Yeah. Then I suggest using the stable branch because if you won't you'll have to fix the issues for it to even try to build.

**Comment by avluis** [comment]
@AdrianVovk So I had a bit of time on my hands today -- I've been messing about with the 'stable branch' of your project this time about and besides having to make a few exclusions to the material dialogs library in order for gradle to sync dependencies, replacing a Google provided library with the original Apache version and updating a few things here and there to get it to run, I need to say the following:

`I cannot help you.`

Please fix the issues with your project, then let me know when I can re-attempt to get some metrics off it.
As it is now, I cannot do anything with it -- once again, this is in reference to your 'stable branch'.

@BGomes17, @TurKurT656 & @guri073:
Please post your app (module) level build.gradle - would like to try and get more detail about what is going on here.

**Comment by AdrianVovk** [comment]
@avluis Well it was worth a shot. I'm rewriting the project anyways so if the issue is still there after the rewrite I'll notify you.

**Comment by TurKurT656** [comment]
@avluis what is your mean?
i didnt get it? you mean what other libs am i using?

**Comment by avluis** [comment]
@TurKurT656 What do you not understand?
Open Android Studio, open your project and open the [build.gradle file for your project and app](http://stackoverflow.com/questions/23241681/why-are-there-two-build-gradle-files-in-an-android-studio-project) and post them here in a comment -- or, if you have your project online, share a link to it so that I can build and analyse it -- this way I can gather metrics directly to see what could be causing your application to start up slower with AppIntro (if that is the cause).:ok_hand:

**Comment by marto-k** [comment]
Intro launches sometimes and doesnt do it.In the place when you run main activity launches leaving the intro out.But same case app intro launches once you clear cache when app is already in  phone.Anyone facing this issue?

**Comment by avluis** [comment]
@marto-k Sounds like your implementation of a first run flag needs work.
Please show code -- also, this issue doesn't really apply to your issue -- but what the heck, not like you care.

**Comment by marto-k** [comment]
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.preference.PreferenceManager;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.NavigationView;
import android.support.design.widget.Snackbar;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;

import com.thefinestartist.finestwebview.FinestWebView;

public class MainActivity extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);





        //  Declare a new thread to do a preference check
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //  Initialize SharedPreferences
                SharedPreferences getPrefs = PreferenceManager
                        .getDefaultSharedPreferences(getBaseContext());

                //  Create a new boolean and preference and set it to true
                boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

                //  If the activity has never started before...
                if (isFirstStart) {

                    //  Launch app intro
                    Intent i = new Intent(MainActivity.this, MyIntro.class);
                    startActivity(i);
                    finish();
                    //  Make a new preferences editor
                    SharedPreferences.Editor e = getPrefs.edit();

                    //  Edit preference to make it false because we don't want this to run again
                    e.putBoolean("firstStart", false);

                    //  Apply changes
                    e.apply();
                }
            }
        });

        // Start the thread
        t.start();







        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);


        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
            }
        });

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.setDrawerListener(toggle);
        toggle.syncState();

        NavigationView navigationView = (NavigationView) findViewById(R.id.nav_view);
        navigationView.setNavigationItemSelectedListener(this);
    }

    @Override
    public void onBackPressed() {
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        if (drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(GravityCompat.START);
        } else {
            super.onBackPressed();
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @SuppressWarnings("StatementWithEmptyBody")
    @Override
    public boolean onNavigationItemSelected(MenuItem item) {
        // Handle navigation view item clicks here.
        int id = item.getItemId();

        if (id == R.id.nav_camera) {
            // Handle the camera action
        } else if (id == R.id.nav_gallery) {

        } else if (id == R.id.nav_slideshow) {

        } else if (id == R.id.nav_manage) {

        } else if (id == R.id.nav_share) {

        } else if (id == R.id.nav_send) {

        }

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        drawer.closeDrawer(GravityCompat.START);
        return true;
    }




//    WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW WEBVIEW


    public void onClick(View view) {
        if (view.getId() == R.id.defaultTheme) {
            new FinestWebView.Builder(this)
                    .titleDefault("")
                    .show("");
////                    .toolbarScrollFlags(0)
//                    .webViewJavaScriptEnabled(true)
//                    .webViewUseWideViewPort(false)
////                    .show("http://andrewliu.in/2016/01/30/聊聊Redis的订阅发布/");
//                    .show("http://www.youtube.com");
        } else if (view.getId() == R.id.redTheme) {
//            Intent intent = new Intent(this, WebViewActivity.class);
//            startActivity(intent);
            new FinestWebView.Builder(this)
                    .theme(R.style.RedTheme)
                    .titleDefault("JamiiBora Bank")
                    .webViewBuiltInZoomControls(true)
                    .webViewDisplayZoomControls(true)
                    .dividerHeight(0)
                    .gradientDivider(false)
                    .setCustomAnimations(R.anim.activity_open_enter, R.anim.activity_open_exit, R.anim.activity_close_enter, R.anim.activity_close_exit)
                    .injectJavaScript("javascript: document.getElementById('msg').innerHTML='Hello " + "TheFinestArtist" + "!';")
                    .show("http://jamiiborabank.co.ke");
        }
    }

}

**Comment by marto-k** [comment]
The code that launches the activity once is after layout main.

**Comment by marto-k** [comment]
I never changed the code even after all these occurrences

**Comment by avluis** [comment]
So what is this not doing again?
Please explain clearly.

**Comment by marto-k** [comment]
The app launches intro only after i restart app after clearing cache in phone settings but when i run from android studio or install apk app launches main activity but not intro.

**Comment by marto-k** [comment]
Does this code have an issue



 //  Declare a new thread to do a preference check
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //  Initialize SharedPreferences
                SharedPreferences getPrefs = PreferenceManager
                        .getDefaultSharedPreferences(getBaseContext());

                //  Create a new boolean and preference and set it to true
                boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

                //  If the activity has never started before...
                if (isFirstStart) {

                    //  Launch app intro
                    Intent i = new Intent(MainActivity.this, MyIntro.class);
                    startActivity(i);
                    finish();
                    //  Make a new preferences editor
                    SharedPreferences.Editor e = getPrefs.edit();

                    //  Edit preference to make it false because we don't want this to run again
                    e.putBoolean("firstStart", false);

                    //  Apply changes
                    e.apply();
                }
            }
        });

        // Start the thread
        t.start();

**Comment by marto-k** [comment]
I mean whether there's an update of the (start intro once ) code.It doesnt seem to work on my app

**Comment by marto-k** [comment]
Well it works but not completely.

**Comment by marto-k** [comment]
And by the way also mine slow launching into

**Comment by avluis** [comment]
OK -- so you are having issues with the code that launches the intro once, after you launched the intro once...
Does anyone see a problem here?
@PaoloRotolo @Andrew-Quebe I need help here, I don't think I get it~

**Comment by xiaobailong24** [comment]
Same Issue Here.
Nexus 5 with android 6.0.1 or cm12, and Nexus 6P with Android 7

**Comment by abumoallim** [comment]
Still the horizontal scrolling is not smooth , put in seperate thread but still it lacks ... i am testing on SAMSUNG NOTE 3 and other phones so no processing issue.. can anyone please help ?

**Comment by avluis** [comment]
@abumoallim I don't think the issue you are describing is the same as what is being discussed here.

For everyone else, this is an app I have been helping out with. It uses AppIntro and has a splash/launch activity. Check out how long [it takes to launch](https://avnet.ws/shared/2016_09_10_02_44_03.mp4).
For those that are still having this issue, I suggest [taking a look here](http://slideslive.com/38897331/launch-screens-from-a-tap-to-your-app-en) for some good info.

**Comment by avluis** [comment]
Removed comments that don't fit the issue.
**If you have an issue different from the OP, do not comment here.**

**Comment by d-rahul** [comment]
It's due to you have enabled the instant run setting for your app build, just disable it and check. More: https://readyandroid.wordpress.com/application-taking-so-much-time-to-launching-android/
