### ISSUE TITLE
sdiwi uses AppIntro

### ISSUE THREAD

**Issue by hohl** [PaoloRotolo/AppIntro#215]
[sdiwi](http://www.sdiwi.com/) allows you to win your purchase in any partner store (right now Austria only). We're using your AppIntro and it's awesome. Thank you for that great Android library!

**Links:**
 - [Website](http://www.sdiwi.com/)
 - [sdiwi on Facebook](https://www.facebook.com/sdiwi/)
 - [sdiwi on Twitter](https://twitter.com/sdiwiapp)
 - [sdiwi on Google Play](https://play.google.com/store/apps/details?id=com.sdiwi.app&hl=de)

**Screenshots:**
![sdiwi win your purchase on Android](https://cloud.githubusercontent.com/assets/744417/14707597/d2e8540e-07c5-11e6-8141-e76532e11192.png)
![share sdiwi on Android](https://cloud.githubusercontent.com/assets/744417/14707546/a52878be-07c5-11e6-9d18-28c27952de9f.png)
![personalized offers sdiwi Android](https://cloud.githubusercontent.com/assets/744417/14707547/a52c05e2-07c5-11e6-8424-dad7e797f70f.png)

**Comment by avluis** [comment]
Added!
