### ISSUE TITLE
GEM Player

### ISSUE THREAD

**Issue by AdrianVovk** [PaoloRotolo/AppIntro#216]
GEM Player uses this library. Links:
https://github.com/SubstanceMobile/GEM
https://play.google.com/store/apps/details?id=com.animbus.music

**Comment by Andrew-Quebe** [comment]
The Play Store URL is broken.

**Comment by AnimbusDev** [comment]
@Andrew-Quebe Probably a Google only allows tester to click the link thing

**Comment by Andrew-Quebe** [comment]
Can you give us an community/opt-in link?

**Comment by AnimbusDev** [comment]
https://play.google.com/apps/testing/com.animbus.music Testing link

**Comment by AnimbusDev** [comment]
Huh, I guess you never were in the community @Andrew-Quebe. For some reason I thought you were

**Comment by avluis** [comment]
@AdrianVovk I have not being able to confirm the use of `AppIntro` by building the code nor by installing the app via the Play Store.
Whenever you are done with the implementation, please update this issue~
