### ISSUE TITLE
How to determine the last page has slipped, slid to the left  making the jump

### ISSUE THREAD

**Issue by chond** [PaoloRotolo/AppIntro#217]
How to determine the last page has slipped, slid to the left, making the jump

**Comment by avluis** [comment]
Hey there!
Are you asking about how to track when the last slide has come into view or out of view?
In any case, you want to track pager - refer to this issue to get an idea of that #212 

Please let me know if you need any further details.

**Comment by chond** [comment]
I would like to know, when I slide to the last page, the user is doing to continue to slide left, how do I judge?

**Comment by avluis** [comment]
Can you clarify this a bit more: `the user is doing to continue to slide left`.
Do you mean, `if the user slides back to a prior slide, after I change the slide programmatically`?
Please clarify what is it that you are doing, what the user should be doing and the state of the current slide: `Is it the last slide?`, `Are the navigation buttons disabled?`

In other words, take your time explaining and go into detail, that way I can help you a lot better.
Include pictures/video if that helps you express better.
I know English, Spanish and a bit of Japanese, so if you can get closer to those three languages I can help you best :smile:

**Comment by chond** [comment]
Today, I have solved the problem, thank you very much for your help

**Comment by avluis** [comment]
Awesome!!
Can you share how you came to your solution?
