### ISSUE TITLE
Making use of onCreate instead of init

### ISSUE THREAD

**Issue by walkthehorizon** [PaoloRotolo/AppIntro#219]
i find it's old version (must use init)when I add 'compile 'com.github.paolorotolo:appintro:3.4.0' ,then i download the library of your github，Yes.I can make my intro use onCreate

**Comment by avluis** [comment]
[This tells me](https://docs.gradle.org/current/release-notes) gradle is currently at 2.13 - where do you see 3.4.0 in regards to gradle?

**Comment by walkthehorizon** [comment]
sorry，my english is bad.I use your library by
```
dependencies {
  compile 'com.github.paolorotolo:appintro:3.4.0'
}
```
,so i can create my appintro use 'init',but it's error when i use 'onCreate.' 

you said
**// Please DO NOT override onCreate. Use init.**

but i can see
**let users override onCreate(),mark int ad depreated**
from your Apptro library in github.

so,i think the dependencies not keep consistent with your  PaoloRotolo/AppIntro/library,
What did I get wrong?

**Comment by avluis** [comment]
I see - you are referring to this merge: 2941c7f
The way releases are done, you will see things like these, but that doesn't necessarily mean that they are available just yet.
When a library update with all the commits merged is released to maven central, you will see a version bump that either includes or does not include the merge above.
So, when you integrate the library in your app, follow the [instructions provided](https://github.com/PaoloRotolo/AppIntro/blob/master/README.md) instead.

If you want to use unreleased features though, you can manually download and include the AppIntro library in your project (remove the dependency as well if you do this).

**Comment by Andrew-Quebe** [comment]
The library has never used onCreate simply so that it wouldn't confuse developers. @PaoloRotolo is there any BIG reason why this still needs to be a thing?

**Comment by walkthehorizon** [comment]
Oh, I see. Thanks

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.
