### ISSUE TITLE
SkipIntro

### ISSUE THREAD

**Issue by indianpoptart** [PaoloRotolo/AppIntro#220]
Hey, so I'm using AppIntro2. and It doesnt allow me to add a skip button

Edit: changed can't do doesn't let me add

**Comment by avluis** [comment]
Have you [read the instructions](https://github.com/PaoloRotolo/AppIntro/blob/master/README.md) on how to implement the library?
Or is there something in particular not working?

**Comment by Andrew-Quebe** [comment]
The `AppIntro2` class currently doesn't support a skip button, as it was built based off of the intro that Google Photos has. PR #211 adds support for it, but is currently pending as some clarification is needed.

**Comment by Andrew-Quebe** [comment]
PR #211 has been merged, and this feature will be available in the next release of the library.

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.
