### ISSUE TITLE
Hide header bar

### ISSUE THREAD

**Issue by guri073** [PaoloRotolo/AppIntro#221]
i need help in hide header bar

**Comment by avluis** [comment]
Please add more detail to this issue.
What sort of help do you need?

**Comment by guri073** [comment]
i am using this addSlide(AppIntroFragment.newInstance(title, description, image, background_colo
![jjhhh](https://cloud.githubusercontent.com/assets/5301258/15105837/906b17ba-158a-11e6-884a-035b0b6512ee.PNG)
ur)); i want to remove android header bar

**Comment by guri073** [comment]
i fix it by style but my api is 11 and i want to use android:windowTranslucentStatus i can't use for uper api

**Comment by avluis** [comment]
Have you tried any of these:

```java
    // OPTIONAL METHODS
    // Override bar/separator color.
    setBarColor(Color.parseColor("#3F51B5"));
    setSeparatorColor(Color.parseColor("#2196F3"));
```

**Comment by abhishekpriyam** [comment]
@guri073 How did you remove that bar from the top?

**Comment by abhishekpriyam** [comment]
For others who are searching for this - 
In your styles.xml define a style 
```
<style name="FullscreenTheme" parent="Theme.AppCompat.Light.NoActionBar">
</style>
```

And in your manifest, add it as the theme for the Intro activity
```
<activity android:name=".AppIntro"
            android:theme = "@style/FullscreenTheme">
</activity>
```

**Comment by guri073** [comment]
Thanks @abhishekpriyam  But i already fixed :+1: . I did same as your steps and i add windowTranslucentStatus to style 21 api for status bar color and every thing is working fine now
