### ISSUE TITLE
askForPermissions does not work if on the last slide

### ISSUE THREAD

**Issue by stamanuel** [PaoloRotolo/AppIntro#222]
i added two slides with 

`addSlide(AppIntroFragment.newInstance(...))`

and then asked for location permission on the second slide:
` askForPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, 2);`

this does not work, i guess because it is not on the next click but on the finish click on the last slide.
if i leave this as it is and add a third slide the permission request dialog appears.

**Comment by avluis** [comment]
If your slides fit the following:

`[slide0 {App Intro/Welcome}] - [slide1 {Slide informing user of permissions}] - [slide2 {Final slide}`

Then your permission code needs to be:
`askForPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, 1);`

That's because, as you discovered, the permission request is made **after** the slide it has been attached to - slides are ordered in insert order, starting with 0, as usual with Arrays.

**Comment by stamanuel** [comment]
yes i know that it's working if the permission request is not on the last slide - but my question is, why is it not possible to ask for a permission on the last slide?
that was the behavior i expected.

if thats by design (which i would not prefer, since it patronizes the developer and it may in some cases make sense to do so) then i think it should maybe throw an exception that it is not possible to assign on that location?

**Comment by avluis** [comment]
It's definitely not patronizing:
When a permission request is made, you are essentially running the following method:
`askForPermissions` which requires `onRequestPermissionsResult`.

If an additional slide is not present to receive said result - then whatever activity follows after the slide needs to implement `onRequestPermissionsResult` or simply, add an additional slide.

**Comment by Andrew-Quebe** [comment]
@avluis is right. In your activity that launches your intro (if you followed my first start example) you need to catch the response from the system after the user has granted or denied access to requested permissions.

**Comment by avluis** [comment]
Closed, please reopen if your issue has not been resolved.
