### ISSUE TITLE
Problem with fragments

### ISSUE THREAD

**Issue by fradali** [PaoloRotolo/AppIntro#226]
I got a little problem with addSlide(MyFragment); , the Error is Expression expected.

**Comment by avluis** [comment]
There is not enough information here for us to figure out what is going on.
Please post your code or more detail about what `MyFragment` is.

**Comment by fradali** [comment]
`public class MyFragment extends Fragment {
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.intro_1, container, false);
        return v;
    }
}`

`public class HelpActivity extends AppIntro {
    private CoordinatorLayout coordinatorLayout;


    @Override
    public void init(Bundle savedInstanceState) {
        coordinatorLayout = (CoordinatorLayout) findViewById(R.id.coordinatorLayout);
        // Add your slide's fragments here.
        // AppIntro will automatically generate the dots indicator and buttons.

        addSlide(MyFragment);
        

        // Instead of fragments, you can also use our default slide
        // Just set a title, description, background and image. AppIntro will do the rest.
       // addSlide(AppIntroFragment.newInstance(title, description, image, background_colour));

        // OPTIONAL METHODS
        // Override bar/separator color.
        setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

        // Hide Skip/Done button.
        showSkipButton(false);
        setProgressButtonEnabled(false);

        // Turn vibration on and set intensity.
        // NOTE: you will probably need to ask VIBRATE permisssion in Manifest.
        setVibrate(true);
        setVibrateIntensity(30);
    }`
I just tried to follow the example

**Comment by avluis** [comment]
This is a bit better - let's see, you are extending AppIntro, so if you base your `MyFragment` of [this](https://github.com/PaoloRotolo/AppIntro/blob/master/example/src/main/java/com/github/paolorotolo/appintroexample/SampleSlide.java) then it should at least get you a working fragment.

Your current implementation of `MyFragment` is missing a few required public methods, essentially, a way to initialize said Fragment.

**Comment by fradali** [comment]
Even when I followed the SimpleSlide class the error still persist , addslide show Expression expected

**Comment by avluis** [comment]
I see - is there any way I can see more of your code?
Is it published somewhere?

The information that you have given me is not sufficient for me to draw a conclusion from the error that you are getting.
The `Expression expected` exception is not a library issue at all unfortunately - it points at how the code is written or implemented - which is why I need to see more of it to figure out the actual issue.

**Comment by fradali** [comment]
I just did now what you have said sir and the error is gone but the fragments are not showing anything
`MyFragment.newInstance(R.layout.intro_1);`
is this a problem from the layout ?

**Comment by avluis** [comment]
It could be, what does your layout xml look like?
Can you post it?

**Comment by fradali** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/coordinatorLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.example.ali.biodyxpert.HelpActivity">



    <RelativeLayout
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:gravity="center"
        android:orientation="vertical">


        <pl.droidsonroids.gif.GifTextView
            android:id="@+id/imageView1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentBottom="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_marginBottom="241dp"
            android:background="@drawable/anim3" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_marginBottom="107dp"
            android:text="@string/help_one_two"
            android:textColor="@color/button_border_labes_icon_color"
            android:textSize="25dp"
            android:textStyle="bold"></TextView>

    </RelativeLayout>

  

    </android.support.design.widget.CoordinatorLayout>`

**Comment by avluis** [comment]
Ok - I'm trying to figure out why there is a CoordinatorLayout in there with nothing using it.
Other than that, your Fragment call: `MyFragment.newInstance(R.layout.intro_1);` is not how it should be done.
Let me post a bit of code to hopefully assist you.

**Comment by fradali** [comment]
Actually I'm use it in the HelpActivity to show a Snackbar for the user .
I think i didn't understand how to use it  very well so thank you for this assit

**Comment by avluis** [comment]
Got it - I won't get too sidetracked then - but basically this is what is needed to get AppIntro working:

- [The layout](https://github.com/PaoloRotolo/AppIntro/blob/master/example/src/main/res/layout/intro.xml)
- [A 'sample slide' or base slide (for easier reuse)](https://github.com/PaoloRotolo/AppIntro/blob/master/example/src/main/java/com/github/paolorotolo/appintroexample/SampleSlide.java)
- [The addSlide call](https://github.com/PaoloRotolo/AppIntro/blob/master/example/src/main/java/com/github/paolorotolo/appintroexample/DefaultIntro.java)

Each item on that list is linked to the sample code, give it a look and see if you can get your implementation close to it.

**Comment by fradali** [comment]
Working like a charm Thank you very much Sir :) .

**Comment by avluis** [comment]
No problem, glad I could help~
