### ISSUE TITLE
Not Working for less than  API level 19

### ISSUE THREAD

**Issue by reddy2510** [PaoloRotolo/AppIntro#233]
[ ] What you've tried (include code snippets, or whole files as necessary):

I am trying to implement the paolo app intro.
My implementation is successfully its works for greater than API level 19.

it's not working for less than API level 19; it does a force shut down.
its shows the file: `ic_skip_white_24px.xml` in force close.

Can i use this library on less than API 19.

So only i wanted to know that app intro working for less than API 19?

**Comment by avluis** [comment]
Library definately works on lower API levels - I'm using it on API level 15 right now.
Can I see the rest of your app level build.gradle?

**Comment by Andrew-Quebe** [comment]
Have you checked to see if your own app has an API level lower than 19?

**Comment by avluis** [comment]
@reddy2510 Care to reply back with results?
I have not being able to reproduce this yet.
I'm giving this issue a week or so before I close it unless it gets updated.

**Comment by avluis** [comment]
OK - it has been a week + 1 day to allow time zone difference, etc.
Please reopen this issue with a response if you have one, don't create 5 more like the last time, please.
