### ISSUE TITLE
Marshmallow permissions not asked when swipe enabled 

### ISSUE THREAD

**Issue by Arkanayan** [PaoloRotolo/AppIntro#239]
[ ] What you've tried (include code snippets, or whole files as necessary):

In marshmallow (api 23) permissions are not requested at all when swiping is enabled. 

[ ] What you thought should happen:

I thought it would ask for permissions on clicking finish.

**Comment by avluis** [comment]
Please show code - also, swiping is disabled when asking for permissions.
Think about what the flow of an application would look like if you could revisit the permission slide over and over.

**Comment by Andrew-Quebe** [comment]
This has already been addressed in #222. Please ensure you check the closed issues section before making a new issue :)
