### ISSUE TITLE
Can't import and build project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [PaoloRotolo/AppIntro#24]
I get this issue:

![untitled20150621205056](https://cloud.githubusercontent.com/assets/5357526/8272737/525b14f6-1857-11e5-8dc5-de7adfac2f85.png)

**Comment by PaoloRotolo** [comment]
@porokoro just proposed a merge to make import easier on Android Studio.
Can you try now please :)?

**Comment by AndroidDeveloperLB** [comment]
What do you mean "proposed" ?

**Comment by PaoloRotolo** [comment]
Edited previous comment, I'm writing from mobile.

**Comment by AndroidDeveloperLB** [comment]
oh, ok.

**Comment by AndroidDeveloperLB** [comment]
Seems to work fine now. Looks cool.
Maybe I will put it in my app. 
Anyway, thank you. You are welcomed to check my repos too.

**Comment by PaoloRotolo** [comment]
@AndroidDeveloperLB Good, I'd like to use some your libraries too. Awesome work :)

**Comment by AndroidDeveloperLB** [comment]
Say, if the last page (or any other page) of the tutorial needs an EditText to enter some text, and yet I need the other buttons to stay visible on the screen while the user is typing, what should I do?
Is there a way to protect the bottom views from being overlapping with the keyboard, yet (of course) let the EditText be visible too?
