### ISSUE TITLE
Custom Text invalidation

### ISSUE THREAD

**Issue by Xmashine** [PaoloRotolo/AppIntro#242]
### New Policy-method: input text and custom invalidation

In your app, you can write a function who allow you to give a <b>custom invalidation text</b>, a special fragment who help you by invalidate or skip a determinated slide by input some text

**Comment by avluis** [comment]
Can you go into a bit more detail - is this an issue or a request?
If it is an issue, please follow the format that was provided when you opened this issue.
If it is a request, there is not enough detail in here to formulate one, please follow this example:

Request: Title of Request
Summary of request.
Current issue that is resolved by this request.
Request proposition (how should this request be approached).
Additional details.

**Comment by avluis** [comment]
As this request has yet to be updated with additional details (proposal, sample and demonstration), I will go ahead and close it for now.
Please reopen with those additional details, or if in doubt of the information needed.
