### ISSUE TITLE
Sliding lags

### ISSUE THREAD

**Issue by ibrcic** [PaoloRotolo/AppIntro#243]
I have a problem where sliding between standard AppIntroFragments produces a lot of lag. Lag does not stop even when all of the fragments are loaded in background. I even tried setting offset on pager to 3 (which is number of fragments I have). 

Lag does not happen when all of the images are the same or when I do custom fragment and load images asynchronously using Glide library. I am using Galaxy S6 but issue is also persistent on emulator.

Images are not big in size, about 20kb each and are stored in standard drawable resource folder. 

[ ] What you've tried (include code snippets, or whole files as necessary):

Tried using the simplest code from sample, issue still persist.

[ ] What you thought should happen:

Fragments should slide without any lag.

[ ] What actually happened:

A lot of lag when sliding.

**Comment by avluis** [comment]
Can you edit/reply with the code that you are using to build/construct your fragments and any code associated with those view to see where the issue could be.

**Comment by ibrcic** [comment]
Hi, this is my AppIntro activity. Just use any images you have (mine are about 20k in size). Also replace strings with any strings because as I said, it is issue with images since it does not happen when images are loaded asynchronously. 

```
public class TutorialActivity extends AppIntro {

    @BindColor(R.color.colorTutorial) int bgColor;
    @BindColor(R.color.dividerTutorialColor) int dividerTutorialColor;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ButterKnife.bind(this);

        getPager().setOffscreenPageLimit(4);
        setSeparatorColor(dividerTutorialColor);
        addSlide(AppIntroFragment.newInstance(getString(R.string.first_slide_title),
                getString(R.string.first_slide_text), R.drawable.tutorial_slide_1, bgColor));
        addSlide(AppIntroFragment.newInstance(getString(R.string.second_slide_title),
                getString(R.string.second_slide_description), R.drawable.tutorial_slide_2, bgColor));
        addSlide(AppIntroFragment.newInstance(getString(R.string.third_slide_title),
                getString(R.string.third_slide_description), R.drawable.tutorial_slide_3, bgColor));
    }

}
```

**Comment by avluis** [comment]
Have you tried this without the use of ButterKnife?
Could be an issue between the two libraries (note that this is speculation, as the code I happen to have looked over in AppIntro does not suggest anything like that so far, but Android development is weird like that sometimes).

**Comment by ibrcic** [comment]
I just tried removing ButterKnife from this class completely but the problem still persists.

**Comment by avluis** [comment]
Forgot to mention, have you tried without retaining the pager?
Remove this: `getPager().setOffscreenPageLimit(4);`

I haven't been able to reproduce this so far unfortunately - I will keep trying.
Do you have your code posted anywhere where I can just pull it and run or is it a private project?

**Comment by ibrcic** [comment]
I tried removing that line of code but it still doesn't work. I'll create sample project later this week and if it still doesn't work I'll update the issue.

**Comment by bbarke** [comment]
Try placing your images in the `res/drawable-hdpi` folder. This seemed to work for me.
http://stackoverflow.com/questions/15763407/android-viewpager-lag

**Comment by ibrcic** [comment]
That fixed it, so it seems that it is issue with Android itself and not the library.

**Comment by avluis** [comment]
@ibrcic I've been researching this as well - and yes, so far it seems to be a ViewPager issue when images are populated in the layout.
Which is weird at the same time since I have that exact setup on my app and don't get any lag.
Have you checked images sizes?
Maybe running lint on your project and see if you get any warnings in relation to this.

**Comment by avluis** [comment]
As it has been almost two weeks since the last reply, I'll consider the poster no longer needing assistance.
Please reopen this issue otherwise.
