### ISSUE TITLE
Using Custom font

### ISSUE THREAD

**Issue by hatim63** [PaoloRotolo/AppIntro#246]
I am trying to use google Roboto font in the fragment, I have tried writing code in xml as well as in fragment.java file but in the both the case the font is not getting applied.

whereas, I have tried using in some other activity it did work.

can you please let me know how to integrate custom font in AppIntro

**Comment by avluis** [comment]
Which AppIntro are you using - also, you need to create your own Fragments for your slides, in which you'll then specify your font.

**Comment by hatim63** [comment]
thank you for your reply..
 
I am using 4.0.0

`View viewRoot = inflater.inflate(R.layout.fragment_slide1, container, false);
        slide1_text = (TextView) viewRoot.findViewById(R.id.slide1_welcomeText);`

the above code is written in onCreateView of my fragment

`Typeface myCustomFont = Typeface.createFromAsset(getContext().getAssets(), "fonts/RobotoCondensed-Bold.ttf");
        slide1_text.setTypeface(myCustomFont);`

the above code is written in onViewCreated of my fragment

**Comment by avluis** [comment]
The AppIntro library can be implemented via AppIntro or AppIntro2 -- which one are you using?

Then, as mentioned in my prior comment, in order for AppIntro to use the font requested, you need to provide a fragment with the appropriate xml style or via code - are you providing your own fragment or using the ones built-in to the library?

**Comment by avluis** [comment]
As it has been almost two weeks since the last reply, I'll consider the poster no longer needing assistance.
Please reopen this issue otherwise.
