### ISSUE TITLE
Sask. Geo-Memorial uses AppIntro

### ISSUE THREAD

**Issue by dstaflund** [PaoloRotolo/AppIntro#247]
Hi there,

I am just writing to let you know that I am using AppIntro v3.3.0 in my new Android App entitled 'Sask. Geo-Memorial'.  The app is currently in public alpha and can be downloaded from:

[https://play.google.com/apps/testing/com.github.dstaflund.geomemorial](https://play.google.com/apps/testing/com.github.dstaflund.geomemorial)

and the source code can be viewed at:

[https://github.com/dstaflund/Capstone-Project](https://github.com/dstaflund/Capstone-Project)

Thanks for making this library available and if I need to acknowledge its use in my code somewhere, just let me know what I need to do and I'll get it done.

Darryl

**Comment by avluis** [comment]
@dstaflund I was going to say that the alpha is not accessible unless you are providing the invite link as well -- but the source code link is enough to verify.

Though -- once you leave alpha, the link needs to be updated, so make sure to update this issue when that happens.

**Comment by dstaflund** [comment]
Hi there,

Sorry for the testing link.  It's in production now so I have corrected the link in my original comment.

Darryl

**Comment by avluis** [comment]
Got it - link updated.
Thank you.
