### ISSUE TITLE
Intro like WizardPager

### ISSUE THREAD

**Issue by davideas** [PaoloRotolo/AppIntro#248]
Hello Paolo,
this is a question of usability for a particular functionality similar to the Roman Nurik's project: https://github.com/romannurik/Android-WizardPager

Some months ago I successfully created a custom wizard for my app, it was quite complex and I was thinking to integrate into a library to simplify the wizard process. Main features are:
- block the page slide based of the current fragment information typed by the user
- and based on that even create different branches slides: Now you know that next fragments are created with minimum 1, here it comes the complexity to create a new branch when next is pressed or page is slid.

Is this library already able or will be able to support this nice wizard pager?

**Comment by Andrew-Quebe** [comment]
Since this library allows you to pass your own fragment layouts to it, you could essentially load those views with anything you want...text fields, buttons, etc.

**Comment by avluis** [comment]
Closing -- redundant, please reopen if you require additional assistance.
