### ISSUE TITLE
Followed Wiki but App Intro does not start.

### ISSUE THREAD

**Issue by Thyroideus** [PaoloRotolo/AppIntro#250]
Hi,

[ ] What you've tried (include code snippets, or whole files as necessary):

Im pretty new to Android development so it is possible this question sounds really dumb. But the App Intro doesn't start when I start my MainActivity.

My MainActivity:
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        final Account account = getIntent().getParcelableExtra("account");

        mLocationProvider = new LocationProvider(this, this);

        SetUpMap(savedInstanceState);

        putChirosIntoList();

        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //  Initialize SharedPreferences
                SharedPreferences getPrefs = PreferenceManager
                        .getDefaultSharedPreferences(getBaseContext());

                //  Create a new boolean and preference and set it to true
                boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

                //  If the activity has never started before...
                if (isFirstStart) {

                    //  Launch app intro
                    Intent i = new Intent(MainActivity.this, TutorialActivity.class);
                    startActivity(i);

                    //  Make a new preferences editor
                    SharedPreferences.Editor e = getPrefs.edit();

                    //  Edit preference to make it false because we don't want this to run again
                    e.putBoolean("firstStart", false);

                    //  Apply changes
                    e.apply();
                    Log.d("TEST", "BLA");
                }
            }
        });

        // Start the thread
        t.start();
```

My TutorialActivity:

```java
package com.jeroen.capturetheflag;

import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;

import com.github.paolorotolo.appintro.AppIntro;

public class TutorialActivity extends AppIntro {

    FirstFragment first_fragment = new FirstFragment();
    SecondFragment second_fragment = new SecondFragment();
    ThirdFragment third_fragment = new ThirdFragment();
    FourthFragment fourth_fragment = new FourthFragment();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Add your slide's fragments here.
        // AppIntro will automatically generate the dots indicator and buttons.
        addSlide(first_fragment);
        addSlide(second_fragment);
        addSlide(third_fragment);
        addSlide(fourth_fragment);

        // Instead of fragments, you can also use our default slide
        // Just set a title, description, background and image. AppIntro will do the rest.
        //addSlide(AppIntroFragment.newInstance(title, description, image, background_colour));

        // OPTIONAL METHODS
        // Override bar/separator color.
        setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

        // Hide Skip/Done button.
        showSkipButton(false);
        setProgressButtonEnabled(false);

        // Turn vibration on and set intensity.
        // NOTE: you will probably need to ask VIBRATE permisssion in Manifest.
        setVibrate(true);
        setVibrateIntensity(30);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        // Do something when users tap on Skip button.
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        // Do something when users tap on Done button.
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        // Do something when the slide changes.
    }
}
```

[ ] What you thought should happen:

The TutorialActivity to start when my MainActivity is loaded.

[ ] What actually happened:

Nothing. MainActivity just starts. I also have problems with the two lines I need to add in my AndroidManifest. The `android:label="@string/app_intro"` line doesn't work?

I know this may sound silly but I don't know where else to search to find the solution. Thanks in advance and any help is much appreciated!

**Comment by avluis** [comment]
Let's tackle this by order of severity, from lowest to greatest.

"I also have problems with the two lines I need to add in my AndroidManifest. The android:label="@string/app_intro" line doesn't work?"

Do you have a string named app_intro in your strings.xml file?

**Comment by Thyroideus** [comment]
Yes I figured this out right after I posted this issue. I know have a string named app_intro in my strings.xml file. I still don't really know why this is necessary, but this is no longer a problem.

**Comment by avluis** [comment]
I see that you really don't know much about Android Development then if you are questioning why that needs to be there for that line to work -- just how much do you know?

Your Main Activity (as defined in your manifest) is what launches first, so, in `MainActivity.java`, in `onCreate` -- remove the code from the wiki and then add the following:

```java
    SharedPreferences getPrefs = PreferenceManager.getDefaultSharedPreferences(this);
    boolean isFirstRun = getPrefs.getBoolean("firstRun", true);

    if (isFirstRun) {
        //  Make a new preferences editor
        SharedPreferences.Editor e = getPrefs.edit();

        //  Edit preference to make it false because we don't want this to run again
        e.putBoolean("firstRun", false);

        //  Apply changes
        e.apply();

        Intent intent = new Intent(this, TutorialActivity.class);
        startActivity(intent);
    }
```
Import the classes as needed and edit any class names that don't match.
Give this code a run and then study the differences between this code and the code snippet in the wiki.
There are not that many differences between then so it should not be too hard.
Test and make sure that you are launched into your tutorial activity on initial run (you need to make sure your app has no data saved in prefs so clear app data first) and then on subsequent runs, it should not be launching the tutorial.

**Comment by Thyroideus** [comment]
Hi thanks for the reply.

I studied your code against the code in the wiki. I tried running it but I get an error:
must implement OnFragmentInteractionListener
Searched for this but could not find any solution...

**Comment by avluis** [comment]
That is not related at all -- is your project on GitHub by any chance?

**Comment by Thyroideus** [comment]
There was indeed something wrong with my Fragments and wasn't related to this library. I got it fixed and now it works as a charm. Thanks for your patience with a newbie in Android Development. ;)
I'm not sure if it is important I post the solution to my problem? The code you gave worked for me.

Many thanks!

**Comment by avluis** [comment]
I only meant the posting part if the solution itself is not figured out by whoever is assisting (or in this case, it is too simple, as you are starting out with Android Development, so no need to post it).

If your issue is resolved, don't forget to close this issue.
