### ISSUE TITLE
BackColor is the same everywhere

### ISSUE THREAD

**Issue by inromualdo** [PaoloRotolo/AppIntro#253]
Thank you for all.
Can i set backcolor for each AppIntroFragment?

**Comment by Andrew-Quebe** [comment]
Which back color are you referring to?

**Comment by inromualdo** [comment]
Sorry. i refer to the BarColor and the separator color

ex: setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

**Comment by Andrew-Quebe** [comment]
This currently isn't supported by the library. Sorry.
