### ISSUE TITLE
Window Background Not Following The Theme

### ISSUE THREAD

**Issue by janakagamini** [PaoloRotolo/AppIntro#254]
[ ] What you've tried (include code snippets, or whole files as necessary):

I'm extending AppIntro/AppIntro2 and using my own custom fragment (like Sample Slide). In the manifest I have set the theme for my AppIntro activity to `Theme.AppCompat.Light.DarkActionBar` (I do want the action bar).

[ ] What you thought should happen:

I expect the window background of my slide fragment to be the default light colour because of the theme I have set.

[ ] What actually happened:

Window background of the slide fragment is dark. 

What am I missing or doing wrong?

**Comment by avluis** [comment]
Can you post the xml for the fragment layout, along with your app theme xml (or style if you have it on there).
And finally, can you post your implementation of your Fragment.

**Comment by janakagamini** [comment]
Fragment layout

    <RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <TextView
            android:text="hello world"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
    </RelativeLayout>


AppTheme xml

    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

Setting theme in Manifest

    ....
    <activity
        android:name=".MyAppIntro"
        android:theme="@style/AppTheme" />
    ....

Fragment is just the one I get from the wizard in Android studio. The code is very similar to the SampleSlide code.

**Comment by janakagamini** [comment]
Anyone else got a similar issue?

**Comment by vinothvino42** [comment]
I'm having related to this issue. I've black color in all my slides. I added "android.R.color.holo_red_dark" to newInstance method of last parameter(background_color) but I've only the black color. Even I tried with my own fragments too that one also having the same black color background. Anyone help me please... Thanks in advance

` addSlide(AppIntroFragment.newInstance("Octocat","Meow.... It is your friend",R.drawable.octocat,android.R.color.holo_red_dark));`

AppTheme

  `<style name="AppTheme.NoActionBar" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowFullscreen">true</item>
    </style>`

**Comment by KChernenko** [comment]
@janakagamini, @vinothvino42 

` android:background="@color/yourcolor"` in your fragment's root layout.

**Comment by intrepidkarthi** [comment]
I had the similar issue. Then I passed the background color argument like 

`addSlide(AppIntroFragment.newInstance("Join with Music party", "Easy way to find local music parties", R.drawable.join_party, Color.parseColor("#000000")));`
       
This worked.

**Comment by janakagamini** [comment]
@KChernenko Yeah, I know this is what I am doing now. I'm just pointing out that it doesn't follow the theme. Or perhaps it doesn't follow the theme by design?

**Comment by avluis** [comment]
@janakagamini After further digging and research of stack issues -- I think this is the behavior the library should keep.
If a library defines styles that conflict on app level -- then you'll encounter merger issues that not many know how to fix on their own -- so instead, allow library users to implement their own styles.

**Comment by janakagamini** [comment]
Hi @avluis thanks for replying! I have since worked around this problem by setting the colour I want as the background of my root layout.

**Comment by avluis** [comment]
Good to know, if you feel this issue has been addressed -- go ahead and close it for now.
