### ISSUE TITLE
How to disable logs.

### ISSUE THREAD

**Issue by Pedramrn** [PaoloRotolo/AppIntro#255]
I see lots of unnecessary logs in logcat, I looked into the source code and find out there are lots of `Log.d()` lines, It would be nice to have a way to disable them, a simple wrapper around Android Log class for instance.

**Comment by avluis** [comment]
Good issue to add, but why is the following so difficult:

> Please check off the following things BEFORE submitting a new issue. Any issues that do not properly follow this format will be closed without discussion. If you're requesting to have your app added to the list, you can erase the list and provide your app's name and play store listing link. Thanks!
> 
> [ ] What you've tried (include code snippets, or whole files as necessary):
> 
> (REPLACE with your answer)
> 
> [ ] What you thought should happen:
> 
> (REPLACE with your answer)
> 
> [ ] What actually happened:
> 
> (REPLACE with your answer)
