### ISSUE TITLE
Why is onNextPressed deprecated?

### ISSUE THREAD

**Issue by xsorifc28** [PaoloRotolo/AppIntro#259]
_[ ] What you've tried (include code snippets, or whole files as necessary):_

**Overriding onNextPressed**

[ ] What you thought should happen:

**Should not be deprecated**

_[ ] What actually happened:_

**Is deprecated.**

**Why is this method depreated, is there an alternative method?**

Edit: I was able to override _onCanRequestNextPage_ to do the same thing I was doing using _onNextPressed_ (basically, prevent user from going to next page). Couldn't find any documentation about this method at first.

**Comment by xsorifc28** [comment]
Actually, it is not working as expected.

How can I prevent user from moving to next page if a condition is not met?

**Comment by avluis** [comment]
Are you using Android Studio?
If you check the `onNextPressed()` method that you have been overriding, it now says to use `public void onSlideChanged(@Nullable Fragment oldFragment,@Nullable Fragment newFragment))` (I believed this was changed on the last release).

All I did on my app was to move the code that was in `onNextPressed()` and in the parameter-less `onSlideChanged()` with the appropriate conditionals.

**Comment by avluis** [comment]
@xsorifc28 Does the above workaround help your issue at all?

**Comment by xsorifc28** [comment]
Yes, it did help. Thank you. I had to make some modifications, but I'm now using onSlideChanged.

The issue wast that I cannot check if an EditText is null before the slide changes since the override isn't triggered.. First I wait for the slide to change, then check, then go back to the previous slide by setting the current item of the view pager (this all happens quite fast, before the slide visually changes).

**Comment by xsorifc28** [comment]
Having access to onCanRequestNextPage would be an optimal solution - allow user to move on to the next fragment or display appropriate message based on meeting a certain condition.

**Comment by janakagamini** [comment]
I'm having the same issue: How can I check whether certain conditions are met before I move to the next slide?

@xsorifc28 I tried your solution, but onSlideChanged ends up being called in an infinite loop because when I do `getPager().setCurrentItem(0)` within onSlideChanged, it triggers the onSlideChanged again and so on and so forth.

May I ask how you solved this problem?

Overriding onCanRequestNextPage and returning false only prevents the user from swiping. Clicking the next button will still advance the user to the next fragment.

**Comment by xsorifc28** [comment]
```java
@Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        Log.d(TAG, "onSlideChanged, Page: " + getPager().getCurrentItem());

        int currItem = getPager().getCurrentItem();


        if (currItem == FIRST_SLIDE + 1) {
            if (checkYourCondition) {
                getPager().setCurrentItem(SLIDE_WELCOME, true);
            }
        } else if (currItem == MY_FRAGMENT + 1) {

            MyFragment myFragment = (MyFragment) getSlides().get(MY_FRAGMENT);

            String code = referralFragment != null ? referralFragment.getReferralCodeInput() : null;

            if (code != null && code.length() == 8) {
                new RefAction(this).query(Ref.getQueriableInstance(code),
                        new ExistenceActionCallback<Ref>() {
                            @Override
                            public void onExist(Ref ref) {
                                referrer = ref;
                                Toast.makeText(getBaseContext(), "Referral code accepted", Toast.LENGTH_SHORT).show();
                            }

                            @Override
                            public void onDNE() {
                                getPager().setCurrentItem(SLIDE_REFERRAL, true);
                                new MaterialDialog.Builder(WelcomeActivity.this)
                                        .title("Referral Code")
                                        .content("The referral code you have entered is invalid.")
                                        .positiveText(android.R.string.ok)
                                        .show();
                                Log.i(TAG, "onDNE: Key does not exist");
                            }

                            @Override
                            public void onError(FirebaseError error) {
                                Log.w(TAG, "error validating the key: " + error.getMessage());
                            }
                        });
            } else if (code != null && code.length() > 0 && code.length() < 8) {
                getPager().setCurrentItem(SLIDE_REFERRAL, true);
                new MaterialDialog.Builder(WelcomeActivity.this)
                        .title("Referral Code")
                        .content("The referral code you have entered is invalid.")
                        .positiveText(android.R.string.ok)
                        .show();
            }
        }
    }

**Comment by xsorifc28** [comment]
@janakagamini  above is how i solved it.. I just set the current item to itself. It does not loop for me..

**Comment by janakagamini** [comment]
Please read the update to my last post, I believe that is the correct way to approach this problem.

**Comment by xsorifc28** [comment]
Oh! I read the update as the bottom part, assumed that ISlidePolicy did not work haha. I'll implement that instead. Thanks!
