### ISSUE TITLE
Long Description issue

### ISSUE THREAD

**Issue by karopass** [PaoloRotolo/AppIntro#261]
Long Description is not showing properly in AppIntro, How can I make it scroll able or how can I decrease margin between title, image and description ? 
Thanks

**Comment by flavio20002** [comment]
Same problem here

**Comment by avluis** [comment]
Better support for long descriptions was a recent PR #234 -- so next library release should have it.
Also, start following the issue guidelines when opening an issue -- I will simply close this next time around.
