### ISSUE TITLE
How to change slide programmatically ?

### ISSUE THREAD

**Issue by OzoTek** [PaoloRotolo/AppIntro#262]
Hello,

I'm using AppIntro in order to create the sign up process of my app.

Thus, I have a form with a validation process in the first fragment (format of email, empty fields etc.) and I would like to launch this checking during `onSlideChanged()`, and if the validation failed for any reason, I need to set the focus on this field (so I need to change the current slide).

Thank you !

Alex.

**Comment by avluis** [comment]
> [I need to change the current slide](https://github.com/PaoloRotolo/AppIntro/issues/212#issuecomment-210894948)

**Comment by pacdouglas** [comment]
getPager().setCurrentItem(SLIDE_NUMBER);
