### ISSUE TITLE
Would like to get my app listed.

### ISSUE THREAD

**Issue by mntgoat** [PaoloRotolo/AppIntro#263]
I've just released the update of [my app](https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo) that uses your library. You can list it as Web Video Caster. Thank you. 

[Play Store](https://play.google.com/store/apps/details?id=com.instantbits.cast.webvideo)

**Comment by avluis** [comment]
Please provide a link to it from the Play Google Store.

**Comment by mntgoat** [comment]
A link back to AppIntro? I'm already at 4000 characters however I have listed AppIntro on the about section of my app http://goo.gl/f2FZbk
