### ISSUE TITLE
I can not swipe fragment when i have called askForPermissions()

### ISSUE THREAD

**Issue by Hymanme** [PaoloRotolo/AppIntro#265]
if i called the function askForPermissions() ,then the fragments would not be swiped. I must click the next button to swipe. why?is there any way to fix it?

**Comment by Hymanme** [comment]
I found that setSwipeLock(true); is called in askForPermissions(),but ,we must setSwipeLock？

**Comment by avluis** [comment]
This is by design -- will need to implement a custom ViewPager in order to support swiping + permissions.
