### ISSUE TITLE
Example APK link in README.md broken :(...

### ISSUE THREAD

**Issue by lovellfelix** [PaoloRotolo/AppIntro#27]
## Example
See example code here on Github. You can also see it live downloading [this apk](https://github.com/PaoloRotolo/AppIntro/raw/master/AppIntroExample/app/app-release.apk).

**Comment by porokoro** [comment]
Hi @lovellfelix, I removed the apk with pull request [#23](https://github.com/PaoloRotolo/AppIntro/pull/23).
Sorry, I forgot to remove the direct link from the _README_ file.

I think it is somewhat unusual to have the compiled files directly in the repository. 
But this is up to @PaoloRotolo to decide.

It can be added into the repo again easily but we should consider some nicer solutions:
- Add the _APK_ file as a release directly on Github (together with the library jar) and link this file in the _README_ instead
- Publish the sample app into _Google Play Store_ so you can simply install it from the store

**Comment by PaoloRotolo** [comment]
So, thanks to @porokoro link is fixed now.
I'll upload ASAP the example app on **Google Play** and release a new version.
