### ISSUE TITLE
How to disable Skip button using AppIntro2

### ISSUE THREAD

**Issue by yenpei** [PaoloRotolo/AppIntro#270]
I tried to use showSkipButton(false) in AppIntro2 onCreate() but it shows as unresolved.

**Comment by avluis** [comment]
The library has yet to be updated, add this to the activity implementing `AppIntro2`:

```java
    private void showSkipButton(boolean showButton) {
        this.skipButtonEnabled = showButton;
        setButtonState(skipButton, showButton);
    }
```

Then add this in `onCreate()`:
```java
showSkipButton(false);
```

Once the library is created, just remove the showSkipButton() method from your activity.

**Comment by avluis** [comment]
@yenpei `4.1.0` includes the changes mentioned above, so remember to remove just the method in your Intro Activity, leave `showSkipButton(false);` and you'll be good to go.

**Comment by yenpei** [comment]
@avluis Excellent. Work like a charm. Thank you.
