### ISSUE TITLE
Unable to access view 

### ISSUE THREAD

**Issue by yenpei** [PaoloRotolo/AppIntro#275]
How to access the current view in R.layout.intro3_2 after adding slide?

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addSlide(SampleSlide.newInstance(R.layout.intro_2));
        addSlide(SampleSlide.newInstance(R.layout.intro2_2));
        addSlide(SampleSlide.newInstance(R.layout.intro3_2));
    }
```

**Comment by developingwild** [comment]
I've got the same problem too, please help him

**Comment by yenpei** [comment]
@Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        text = (TextView) findViewById(R.id.mytextview);

        if (text != null) {
            text.setMovementMethod(LinkMovementMethod.getInstance());
        }
    }

**Comment by MohammadSommakia** [comment]
it did not work for me

**Comment by cortinico** [comment]
@MohammadSommakia Can I ask you to open another issue if you found a bug? This one is really old and the library changed drastically by then.
