### ISSUE TITLE
Feature request: RTL support

### ISSUE THREAD

**Issue by abdurrahimbliss** [paolorotolo/AppIntro#279]
It would be great if you provide rtl support.

**Comment by avluis** [comment]
This could be a good addition to the library, but one that is fairly time consuming.
If there are any devs out there with experience with RTL support, PRs are welcome.

**Comment by Andrew-Quebe** [comment]
If we're allowing text to be passed to the library, shouldn't it automatically support RTL? After all, only certain types of languages are written RTL, so I'm assuming that if we pass them through to the lib, they'll show up automatically. @abdurrahimbliss did this not work out in your testing?

**Comment by avluis** [comment]
@Andrew-Quebe Actually, what this means, besides the text being oriented said way, is that the slides themselves need to slide RTL and the buttons need to reflect that as well.
This requires an alternative implementation of ViewPager, since Android does not have one that support RTL -- those were my reasons for adding the `help wanted` label here.

**Comment by Andrew-Quebe** [comment]
@avluis Ah, I gotcha. I'll try fiddling around with reverse viewpagers and see what I can accomplish. We might be able to throw this into the `4.1.0` update.

**Comment by Andrew-Quebe** [comment]
Note to self: An issue has been opened on the Android forums already. No official support from Google, but several people say to change XML layout code. Still investigating.

Issue Source: https://code.google.com/p/android/issues/detail?id=56831

**Comment by Andrew-Quebe** [comment]
Note to self: Several libraries create RTL viewpagers, but I'm not sure if it's best to use a library inside a library.

Links:
https://github.com/DisionCo/android-rtl-viewpager
https://github.com/diego-gomez-olvera/RtlViewPager 

@avluis thoughts?

**Comment by beatbrot** [comment]
I'd loove to have RTL support in this library too!

**Comment by avluis** [comment]
@Andrew-Quebe I wouldn't make this part of 4.2.0 (and a few other issues) unless you are really wanting to wait -- this issue alone will need plenty of testing.

**Comment by Andrew-Quebe** [comment]
@avluis you're right about the milestone stuff...good thinking.

I'll probably mess around with this when I get done with the sample app.

**Comment by beatbrot** [comment]
I just created a pull request you may want to take a look at ;) While I know that its hacky in many ways, it actually works quite fine :)

[https://github.com/paolorotolo/AppIntro/pull/379](url)
