### ISSUE TITLE
Set color of progress indicator

### ISSUE THREAD

**Issue by shrutygupta0297** [PaoloRotolo/AppIntro#282]
_**Template ignored.**_

**Comment by avluis** [comment]
Please follow the template above when filling out issues, there is no need for the title to be so long...

Anyways, have you tried, as an example, which is in the example app btw:

`setIndicatorColor(Color.parseColor("#ff0000"), Color.parseColor("#00ff00"));`

**Comment by shrutygupta0297** [comment]
Thanks a lot for ur prompt response!

Could fix it!

Thanks
Shruti
