### ISSUE TITLE
Filmy - AppIntro

### ISSUE THREAD

**Issue by webianks** [PaoloRotolo/AppIntro#284]
We are using AppIntro in this app. We wanted you to add this app in the list.
https://github.com/salRoid/Filmy
https://play.google.com/store/apps/details?id=tech.salroid.filmy

**Comment by mrzear** [comment]
Sir webianks 
Can you help me this ?
https://github.com/PaoloRotolo/AppIntro/issues/285
I Followed the procedure told below the Main com.github.paolorotolo:appintro:4.0.0 
But Buttons Do not work :-)

**Comment by avluis** [comment]
Adding soon.
