### ISSUE TITLE
Not working: DONE, SKIP, AND Next Slide Buttons

### ISSUE THREAD

**Issue by mrzear** [PaoloRotolo/AppIntro#285]
[ ] What you've tried (include code snippets, or whole files as necessary):
[ Sir I have Tried below code, But I am unable to Find proper working of DONE, SKIP, AND Next Slide Buttons, Please help :-) ]
public void loadMainActivity() {
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
        //finish();
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        // Do something when users tap on Skip button.
        super.onSkipPressed(currentFragment);
        loadMainActivity();
        Toast.makeText(getApplicationContext(), getString(R.string.skip), Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onDonePressed (Fragment currentFragment){
        // Do something when users tap on Done button.
        super.onDonePressed(currentFragment);
        loadMainActivity();

    }

    @Override
    public void onSlideChanged(Fragment oldFragment, Fragment newFragment) {
        // Do something when slide is changed
        super.onSlideChanged(oldFragment, newFragment);

    }

[ ] What you thought should happen:

I though Skip, Next And Done Buttons would work.

[ ] What actually happened:

Error occurs: Unfortunately App encountered an error sort of pop up thing

**Comment by avluis** [comment]
Please include those errors in your issue, I'm gonna be asking for them
anyways -- I haven't acquired the all seeing eye skill yet ;)

**Comment by mrzear** [comment]
Below is The Code, and Sir I Followed the exact procedure you told, But Even then when I Press Exit, Next and Done Buttons While App Running It leads with a popup error Like App Error has Occured [Generic Error which occurs when proper Reference is given to view etc like that.


import android.Manifest;
import android.content.Intent;
import android.os.Bundle;
import com.github.paolorotolo.appintro.*;

import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.widget.Toast;
import com.paakland.yums.myintro.IntroFragment.SampleSlide;


public final class IntroActivity extends AppIntro {
    // Please DO NOT override onCreate. Use init
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Add your slide's fragments here
        // AppIntro will automatically generate the dots indicator and buttons

        // Instead of fragments, you can also use our default slide
        // Just set a title, description, background and image. AppIntro will do the rest
        //Here we are adding the four slides
        addSlide(SampleSlide.newInstance(R.layout.fragment_intro_one));
        addSlide(SampleSlide.newInstance(R.layout.fragment_intro_two));
        addSlide(SampleSlide.newInstance(R.layout.fragment_intro_three));
        addSlide(SampleSlide.newInstance(R.layout.fragment_intro_four));

        // Edit the color of the nav bar on Lollipop+ devices
        // setNavBarColor(Color.parseColor("#3F51B5"));

        // Hide Skip/Done button

        showSkipButton(true);
        showStatusBar(false);
        // Turn vibration on and set intensity
        // NOTE: you will probably need to ask VIBRATE permisssion in Manifest
        setVibrate(true);
        setVibrateIntensity(30);
        setDepthAnimation();
        // Animations -- use only one of the below. Using both could cause errors.
        //setFadeAnimation(); // OR
/*            setZoomAnimation();
            setFlowAnimation(); // OR
            setSlideOverAnimation(); // OR
            setDepthAnimation(); // OR
            setCustomTransformer(yourCustomTransformer);*/

        // Permissions -- takes a permission and slide number
        //askForPermissions(new String[]{Manifest.permission.CAMERA}, 3);
    }

    public void loadMainActivity() {
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
        //finish();
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        // Do something when users tap on Skip button.
        //loadMainActivity();
        finish();
        Toast.makeText(getApplicationContext(), getString(R.string.skip), Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        // Do something when users tap on Done button.
        //loadMainActivity();
        finish();
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        // Do something when the slide changes.

    }



    private void permissions() {
        askForPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE}, 3);
    }
}

**Comment by avluis** [comment]
I'm seeing incomplete implementations, how do you suppose this will work if it has properly implemented?

If you are having issue putting your own AppIntro together, take a look at the example project included with the library.

**Comment by Andrew-Quebe** [comment]
"Error occurs: Unfortunately App encountered an error sort of pop up thing"

This isn't the most descriptive info for us to go on...also, you've posted your code with implementation errors and haven't showed us what the error actually looks like. "Error sort of pop up thing" doesn't mean much, as a lot of error pop up things can happen on the Android System.

Please take a look at the sample app, and reopen this issue if your issue has not been solved in doing so.
