### ISSUE TITLE
Pre-Launch Report can't navigate

### ISSUE THREAD

**Issue by seang96** [PaoloRotolo/AppIntro#286]
[ ] What you've tried (include code snippets, or whole files as necessary):

Compiled library with the wizard, made it the intro a start up wizard.
[ ] What you thought should happen:

The buttons should be navigable for the bots

[ ] What actually happened:

When launching the app to the playstore, the pre-launch reports all succeeded with screenshots on the first screen, leading the assumption that the buttons aren't recognized as buttons for them.

**Comment by avluis** [comment]
If you require the library to support test reports from the Play Store -- please submit a PR with the required changes, as I'm not seeing where this is advertised as a feature or function of the library, which invalidates this as an issues.

This could be considered a feature request instead.

**Comment by avluis** [comment]
Closing due to non-interest -- please re-open if you wish to proceed with the above request.
