### ISSUE TITLE
Long descriptions don't scroll

### ISSUE THREAD

**Issue by Merlin1896** [PaoloRotolo/AppIntro#287]
I add my slides via `addSlide(AppIntroFragment.newInstance(title, description, image, background_colour));`. Unfortunately, some of the descriptions have to be a bit longer. On devices with small screens, the bottom of the textView is cut off and the description cannot be read completely. I tried to use my own layout with an scrollview but was unsuccessful. Scrolling should be enabled by default in order to support devices with small screens.

How do I handle this properly?

**Comment by avluis** [comment]
Please try to follow the template for your next issue.

As for scrolling in long descriptions, that is not how you should be approaching this issue.
You were on the right path when you created your own layouts, but you need to create alternative layouts for devices with [smaller screen width](https://developer.android.com/training/multiscreen/screensizes.html#TaskUseSWQuali), size, etc.

As for why the library does not enable scrolling by default, well it simply isn't good design; design your layouts for the intended device.

**Comment by avluis** [comment]
Closing due to non-response -- non-compliant request.
