### ISSUE TITLE
Cannot Add it to my Project

### ISSUE THREAD

**Issue by balzathor** [PaoloRotolo/AppIntro#29]
Well, A few days ago, I tried adding this to my project for the people who are new to it.
Successfully Imported this into android studio, added the required stuff, but when I execute, It crashes at the start.
Can you help me add it to my project? Any kind of help is appreciated.

Regards.

**Comment by PaoloRotolo** [comment]
Hey @balzathor,
can you share the code or crash logs please?

**Comment by balzathor** [comment]
I have currently taken it out of my application, if you want to see the main repo, you can check UltimateBrowserProject and help me add it. Like just tell me what to do exactly and I'll do it. Thanks for the reply.

Regards.

**Comment by PaoloRotolo** [comment]
Just follow the instructions in README: create a new Activity that extends AppIntro and add the methods you want. If your app still crashes, paste the log here.

**Comment by balzathor** [comment]
I just want it to launch when its the first time, so when in my main activity's onCreate i check boolean whether its the first run, if true, it should run or else just continue with loading, but it crashes. Am I doing it right by adding it to the onCreate? because it is also supposed to show the changelog on first start, which works flawlessly. Thanks for the reply.


Regards.

**Comment by PaoloRotolo** [comment]
Add a new activity, like IntroActivity with all Intro stuff (you can also copy it from example).
In your MainActivity check if it's first run. *If yes*, start IntroActivity.

**Comment by balzathor** [comment]
Why does it crash when I put it in onCreate in my MainActivity? Am I supposed to put it somewhere else or am I doing it right? I'll try it now and let you know about the log if it crashes.

**Comment by PaoloRotolo** [comment]
Please paste logs here so I can tell you why it doesn't work :)

**Comment by balzathor** [comment]
Sure I'm working on it now :)

**Comment by balzathor** [comment]
Doesn't seem to crash now, but doesn't work too. It just loads the main activity.
I tried using `SecondIntroLayout.java`
In my __MainActivity's__ `onCreate` I added this 

`SharedPreferences pref = getSharedPreferences("ActivityPREF", Context.MODE_PRIVATE);`
 `       if(pref.getBoolean("activity_executed", false)){`
  `          Intent intent = new Intent(this, SecondLayoutIntro.class);`
  `          startActivity(intent);`
   `         finish();`
  `      } else {`
         `   SharedPreferences.Editor ed = pref.edit();`
      `      ed.putBoolean("activity_executed", true);`
     `       ed.commit();`
  `      }`

and my `AndroidManifest` includes this 

`<activity android:name=".Intro.SecondLayoutIntro"`
           ` android:label="@string/title_activity_intro"/>`

Please help

**Comment by balzathor** [comment]
Well now everytime I open the application it shows `Intro` written on top of a black screen and then application crashes.

**Comment by PaoloRotolo** [comment]
Can you paste here your SecondLayoutIntro.class please?

**Comment by balzathor** [comment]
Its the same as the one included in your sample Application

```
package io.github.UltimateBrowserProject.Intro;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import com.github.paolorotolo.appintro.AppIntro2;

import io.github.UltimateBrowserProject.Activity.BrowserActivity;
import io.github.UltimateBrowserProject.Slides.FirstSlide2;
import io.github.UltimateBrowserProject.Slides.SecondSlide2;
import io.github.UltimateBrowserProject.Slides.ThirdSlide2;

public class SecondLayoutIntro extends AppIntro2 {
    @Override
    public void init(Bundle savedInstanceState) {
        addSlide(new FirstSlide2(), getApplicationContext());
        addSlide(new SecondSlide2(), getApplicationContext());
        addSlide(new ThirdSlide2(), getApplicationContext());
    }

    private void loadMainActivity(){
        Intent intent = new Intent(this, BrowserActivity.class);
        startActivity(intent);
    }

    @Override
    public void onDonePressed() {
        loadMainActivity();
    }

    public void getStarted(View v){
        loadMainActivity();
    }
}
```

Where it shows ___Method getStarted() is never used___

**Comment by PaoloRotolo** [comment]
Seems fine to me... Push your code on GitHub, I'll try to import it and see what's wrong.

**Comment by balzathor** [comment]
Alright, updated the repo, check it out.

**Comment by PaoloRotolo** [comment]
On it :)

**Comment by PaoloRotolo** [comment]
Fixed, there were a problem with SharedPreferences: https://github.com/balzathor/UltimateBrowserProject/pull/15

**Comment by balzathor** [comment]
Thanks a lot, I'll accept it :)
