### ISSUE TITLE
Feature request: option to change title and description text color

### ISSUE THREAD

**Issue by APierson** [PaoloRotolo/AppIntro#294]
Hi, I'm not sure if I'm just missing this option somewhere, but I don't see a way to change the color of title or description text, and this would be a terrific capability to have. 

Thanks so much for all of the work on this! It's really useful.

**Comment by avluis** [comment]
You are aware that you can create your own slides instead of relying on the library to provide all possible options?
This way, if a particular feature is not there yet, you can still create a fairly complicated intro.

**Comment by gauravgupta2** [comment]
There is a second method to create new Instance of AppIntroFragment

`public static AppIntroFragment newInstance(CharSequence title, CharSequence description, int imageDrawable, int bgColor, int titleColor, int descColor) `

**Comment by avluis** [comment]
Closing this since @gauravgupta2 provides your answer.
