### ISSUE TITLE
How to auto scroll?

### ISSUE THREAD

**Issue by mja46** [PaoloRotolo/AppIntro#295]
hi thanks to make this nice library.

i want to ask about auto scroll slide like this library https://github.com/Trinea/android-auto-scroll-view-pager?

Thanks before

**Comment by avluis** [comment]
@mja46 Please look into timers/handlers and use the `pager` object to set the appropriate slide:
`pager.setCurrentItem(SLIDE);`

**Comment by EssenKh** [comment]
Please How to use auto scrolling ? I don't get your answer
