### ISSUE TITLE
Skip/ Done Button color Change in AppIntro2

### ISSUE THREAD

**Issue by AtulaGuleria** [PaoloRotolo/AppIntro#301]
Can you tell me how to change the color of Skip/ done button ?

**Comment by Andrew-Quebe** [comment]
Currently there isn't a way to change this, but the `AppIntro2` button is meant to look good on all different colors. That is, unless you mean the arrow inside the button.

**Comment by avluis** [comment]
If this is referring to the arrow colors in AppIntro2, then this would need to be provided by the library:
We can easily tint the arrows by making use of a Color Filter with PorterDuffColorFilter to cover additional platforms.
e.g; `imageView.setColorFilter(Color.argb(255, 255, 255, 255)); // White Tint`
[Ref]
(https://developer.android.com/reference/android/widget/ImageView.html#setColorFilter%28int%2C%20android.graphics.PorterDuff.Mode%29)
