### ISSUE TITLE
Suggestion for setting value

### ISSUE THREAD

**Issue by thevisuales** [PaoloRotolo/AppIntro#303]
Hi Friend, thanks for your great work. With this project I've saved some time improving my screen presentation. If you allow me a suggestion, to my mind it would be missing an option in view of: addSlide (AppIntroFragment.newInstance

So that the titles appear in bold only if desired, perhaps with a field that provides more value.

A greeting and congratulations on your new job!

**Comment by Andrew-Quebe** [comment]
Are you wanting to control a boolean value that styles the text bold or not? If I'm not mistaking, this is already implemented, right @avluis?

**Comment by avluis** [comment]
I took a quick look at the library, I'm not seeing anything that will accomplish this with just a toggle.
With that said, there is the custom typeface option, which would be available once a new release of the library comes out.
Or you can do what plenty of devs have done and simply create your slides, with everything you need...

**Comment by Andrew-Quebe** [comment]
@thevisuales please reopen if the aforementioned solutions do not suite your needs.
