### ISSUE TITLE
[feature request] optional button

### ISSUE THREAD

**Issue by zoff99** [PaoloRotolo/AppIntro#307]
please add the feature of a Button that can be option on any slide.
like "for more info press" -> Button
with onClickListener

something like this "get started" button:

![button](https://camo.githubusercontent.com/bc9e591b8a21ab31064c38b9e73be901fb519b9e/687474703a2f2f692e696d6775722e636f6d2f634c575735716d2e706e67)

**Comment by avluis** [comment]
This won't happen anytime soon -- since the library already allows you to create your own fragments, so there are no limits to how many button you can have on your slides...
If you feel that its inclusion is a must, submit a PR.

**Comment by zoff99** [comment]
i am not sure why i would need to use the library, if i need to code everything myself manually?

**Comment by Andrew-Quebe** [comment]
@zoff99 the app intro library is a bare-bones library that allows you to pass text and images to it to create a simple introduction to your app. If you desire custom layouts and custom buttons, the library supports that too. The library makes it easier to do such things, so I don't see why you don't see the need for it.

**Comment by zoff99** [comment]
i have done it totally manual now, without any library. which was less complicated and also works down to API9 (2.3.x)

i used this page. takes 10 minutes and you're set.

**Comment by zoff99** [comment]
http://www.androidhive.info/2016/05/android-build-intro-slider-app/

**Comment by Andrew-Quebe** [comment]
@zoff99 if your intention was to prove this library useless, I'd say that's kind of a dick move. If you find it easier to code everything yourself, fine. If you feel the need to come on here and make this library (and the hours of work that went into it) look pointless, that's not fine.

**Comment by zoff99** [comment]
the exact opposite. i tried this library and before that another lib. i put work into it, but both did not really work. so i was forced to do it manually.
if your read something evil here, thats your perspective.

**Comment by Andrew-Quebe** [comment]
@zoff99 if you did work manually, consider making your own library instead of telling us that our work isn't needed.
