### ISSUE TITLE
Changelog for AppIntro v4.1.0

### ISSUE THREAD

**Issue by Andrew-Quebe** [PaoloRotolo/AppIntro#308]
(Ignoring issue template because it doesn't apply to this issue.)

It would be awesome if we could get a full changelog going with credits and everything. I think @maxee has made some big changes, but there have also been some other people as well. If we can track them down and formulate a good changelog, that would help @PaoloRotolo out a lot.

Thanks guys!

**Comment by Andrew-Quebe** [comment]
@avluis since you've been doing most of the merging, I'm assigning you to this.

**Comment by avluis** [comment]
@Andrew-Quebe This is a great idea -- gotta give credit where it is due~

**Comment by avluis** [comment]
- Wizard Mode & Custom Typeface @ameykshirsagar #267

**Comment by PaoloRotolo** [comment]
Hey, I've just pushed ```4.1.0``` on Maven Central. I'll publish a new release here on GH as soon as changelog is available. Let me know if you need help with it :+1:

**Comment by Andrew-Quebe** [comment]
@avluis nice!

**Comment by Andrew-Quebe** [comment]
@avluis one thing I'm noticing is that @maxee is only listed for documentation updates...didn't he do code side stuff too?

**Comment by Andrew-Quebe** [comment]
Also, a draft 4.1.0 draft release is up, which I believe is available to collabs only.

**Comment by maxee** [comment]
@Andrew-Quebe, Nope I only did the readme updated... My former changes (Slide Policy, big refactoring, color transitions,...) were already merged in #204. I think those changes are already included in v4.0.0.

**Comment by Andrew-Quebe** [comment]
@maxee ah....gotcha. Thanks for clarifying ;)

**Comment by Andrew-Quebe** [comment]
Latest release is (live)[https://github.com/PaoloRotolo/AppIntro/releases/tag/v4.1.0]. Special thanks to @SandroMachado, @RafaG, @ameykshirsagar, @xsorifc28, @K0bin, @voghDev, and @maxee for your contributions.

**Comment by SandroMachado** [comment]
@Andrew-Quebe I will suggest https://github.com/skywinder/github-changelog-generator for generating the changelog automatically.
