### ISSUE TITLE
Buttons Not Showing

### ISSUE THREAD

**Issue by nicdichiara** [PaoloRotolo/AppIntro#310]
[ ] What you've tried (include code snippets, or whole files as necessary):

I made a new application in Android Studio. Nothing fancy, just the basic MainActivity. 
I then included the AppIntro library as per the instructions and made an IntroActivity. 
I loaded it up and while it seems to work flawlessly, there are no SKIP or > buttons at the bottom? 

I tried to use the AppIntro2 but still no bottom buttons. 

Just a little info about my setup: 
Using AppIntro 4.0.0
Developing in Android Studio
Tested on both a Android 7 and Android 5.1 phone (same result).

I feel like I'm missing something simple. Any advice? 

Thanks ahead of time! And thank you all for this library!!!

**Comment by nicdichiara** [comment]
I think I figured it out, I just needed to set 

`setProgressButtonEnabled(true);`

Haven't been able to find that in the documentation/through GitHub's repo search.

**Comment by avluis** [comment]
When you created your intro activity, what part of the instructions in the README did you follow?

**Comment by nicdichiara** [comment]
I followed the instructions exactly. 

- I copied over the text into build.gradle
- I created a new activity using Android studio (which adds the proper manifest entry) and pasted into it the example activity in the README. 

Then I loaded the app up to see that everything works except for the buttons at the bottom. 

What does the setProgressButtonEnabled(true); function do? When I changed it from false to true it began working fully.

**Comment by avluis** [comment]
There are instructions for `AppIntro` and `AppIntro2` -- as well as being able to create your own `Fragment` to pass to `.addSlide()`.
Can you paste your code for your intro here and any other files that were created manually (no need for manifest or build.gradle).

**Comment by nicdichiara** [comment]
Avluis, I'm aware that there are instructions, and I followed them exactly. 

My issue is not with Fragments or slides, only that the bottom buttons do not show on a clean install unless` setProgressButtonEnabled(true);` is enabled. 

I can paste my code, but it is literally the exact same as the code in the README. No changes. 

All I want to know is what the `setProgressButtonEnabled(true);` function does.

**Comment by avluis** [comment]
If you want to know what that method does, read the source code.
If you don't want to share your code, or simply answer the question, then I cannot help you.

**Comment by nicdichiara** [comment]
@avluis 
I already did, and there was no explanation in the code comments ([link](https://github.com/PaoloRotolo/AppIntro/blob/276326c7f2e9b0ab9dc9050ae79b7498ae3c7828/library/src/main/java/com/github/paolorotolo/appintro/AppIntroBase.java)), or in the README. See for yourself. 

At this point, my code is irrelevant. I was only suggesting that this function should be mentioned in the documentation if it is needed for the library to work properly. I'd be glad to add the commentary myself but I can't find what it does.

**Comment by avluis** [comment]
So if I understand you correctly - you implemented everything that is in the sample fragment, including the following:
```java
        // OPTIONAL METHODS
        // Override bar/separator color.
        setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

        // Hide Skip/Done button.
        showSkipButton(false);
        setProgressButtonEnabled(false);

        // Turn vibration on and set intensity.
        // NOTE: you will probably need to ask VIBRATE permission in Manifest.
        setVibrate(true);
        setVibrateIntensity(30);
```
