### ISSUE TITLE
Bug and Intro Update

### ISSUE THREAD

**Issue by niilante** [PaoloRotolo/AppIntro#311]
![appintro](https://cloud.githubusercontent.com/assets/10741609/18899351/3a844862-84ed-11e6-9ba4-3df49268fd87.JPG)
Please check off the following things BEFORE submitting a new issue. Any issues that do not properly follow this format will be closed without discussion. If you're requesting to have your app added to the list, you can erase the list and provide your app's name and play store listing link. Thanks!

[ ] What you've tried (include code snippets, or whole files as necessary):

Please check out my error image.
Also I want you to help me connect the AppIntro to my Login Sc
![appintro](https://cloud.githubusercontent.com/assets/10741609/18899411/aa7d9ea2-84ed-11e6-97dc-fdf9ab01d1a4.JPG)
reen

**Comment by avluis** [comment]
You are extending the wrong class, extend `android.support.v4.app.Fragment`;

**Comment by niilante** [comment]
So how can I extend the right class

**Comment by Andrew-Quebe** [comment]
@niilante read the Readme, and you'll figure it out. I'm just gonna close this pointless question now.

**Comment by niilante** [comment]
I am new with android studio, so please take time and explain the things into details. Andrew I will be happy if you help me out, since you understand the ReadMe better than I do.

**Comment by Andrew-Quebe** [comment]
@niilante first off, you've provided us with no code at all. The error you've shown us makes me assume you're extending the wrong library class. As I said, refer to the readme and it will tell you which class you need to extend to be able to use AppIntro. If you need help with extending classes, refer to the (Java documentation)[https://docs.oracle.com/javase/tutorial/java/IandI/subclasses.html].
