### ISSUE TITLE
Swipe operation not working between the screens

### ISSUE THREAD

**Issue by pulimiharish** [PaoloRotolo/AppIntro#312]
[ ] What you've tried (include code snippets, or whole files as necessary):

        // Add your slide fragments here.
        // AppIntro will automatically generate the dots indicator and buttons.
        addSlide(AppIntroFragment.newInstance("1", "one", R.drawable.one, Color.parseColor("#3f51b5")));
        addSlide(AppIntroFragment.newInstance("2", "two", R.drawable.two, Color.parseColor("#3f51b5")));
        addSlide(AppIntroFragment.newInstance("3", "Three", R.drawable.three, Color.parseColor("#3f51b5")));
        addSlide(AppIntroFragment.newInstance("4", "Four", R.drawable.four, Color.parseColor("#3f51b5")));
        addSlide(AppIntroFragment.newInstance("5", "Five", R.drawable.five, Color.parseColor("#3f51b5")));
        addSlide(AppIntroFragment.newInstance("6", "Six", R.drawable.six, Color.parseColor("#3f51b5")));

        // OPTIONAL METHODS
        // Override bar/separator color.
        setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

        // Hide Skip/Done button.
        showSkipButton(true);
        setProgressButtonEnabled(true);

        // Turn vibration on and set intensity.
        // NOTE: you will probably need to ask VIBRATE permission in Manifest.
        setVibrate(true);
        setVibrateIntensity(30);
        setFadeAnimation();

        askForPermissions(new String[]{Manifest.permission.CAMERA}, 5);

[ ] What you thought should happen:

Should be able to swipe between the help screens

[ ] What actually happened:

Swipe doesn't work on Nexus 9 (Android 7.0) & LG G4 (Android 6.0). However with the same code swipe works on HTC ONE (Android 5.0). The buttons Skip, DONE and > are working in all the devices.

**Comment by avluis** [comment]
When you ask for permissions, swipe is usually disabled -- the reason why you are still able to swipe on the HTC ONE is because the API does not apply to that device.
This is by design.

**Comment by pulimiharish** [comment]
Okay, thank you for the explanation
