### ISSUE TITLE
setNextPageSwipeLock() can be skiped

### ISSUE THREAD

**Issue by blaaz15** [PaoloRotolo/AppIntro#313]
[ ] What you've tried (include code snippets, or whole files as necessary):

I have implemented 7 slides and on 6-th slide I call `setNextPageSwipeLock(true)`
```
override fun onPageSelected(position: Int) {
        when (position) {
            5 -> { setNextPageSwipeLock(true) }
        }
        super.onPageSelected(position)
    }
```
And then when action is taken in the custom fragment I call a listener back into AppIntro activity, where i programatically click on NEXT button to move forward.
```
override fun onFragmentInteractionIntroLanguage() {
        val nextButton = findViewById(R.id.next) as ImageButton
        nextButton.performClick()
    }
```
Page swipe to next page is locked and everything works.
But if you (for some reason) on 6-th slide start to swipe back and then in the same move swipe to next slide, it lets you trough.

Here is a [video](https://goo.gl/photos/gyJXAuJNYF7iCw1X8) of normal behaviour and at ~0:11 a swipe lock is skiped. 

[ ] What you thought should happen:

Swipe gesture to next slide should be blocked.

[ ] What actually happened:

You can, in above scenario, skip a swipe lock and continue with the next slide.

This issue is not a problem for this (my) app, because I allready have a default value, but I thought that I should let you know.

**Comment by avluis** [comment]
This seems to be the behavior by design: https://github.com/PaoloRotolo/AppIntro/blob/master/library/src/main/java/com/github/paolorotolo/appintro/AppIntroBase.java#L706
