### ISSUE TITLE
App with AppIntro 4.1 does not build with proguard

### ISSUE THREAD

**Issue by connyduck** [PaoloRotolo/AppIntro#314]
I get the following error:
**Error:Uncaught translation error: com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type java.lang.Object using a local variable of type int**

AppIntro 4.0 works fine with the exact same configuration. I assume I have to include something in my Proguard config, but no idea what it could be.

**Comment by avluis** [comment]
I can assure you that it builds just fine - please post your project and app level build.gradle here and your settings.gradle as well -- finally, your proguard configuration.
Exclude any secret keys from those files before posting.

**Comment by Andrew-Quebe** [comment]
@connyduck this issue should technically be closed right away since you ignored the template. You're supposed to provide us with code and things you've tried that haven't solved your issue. Please do so in a timely manner, or your issue will be closed. Thanks.

**Comment by jbollacke** [comment]
Fixed with bf1fb7d4e83d6743e4e74e9c9b30a78de248aa60.
