### ISSUE TITLE
Page indicator does not show the first page selected

### ISSUE THREAD

**Issue by SandroMachado** [PaoloRotolo/AppIntro#316]
**AppIntro Version**: 4.1.0 or 4.0.0

**Device/Android Version**: OnePlus 1 and 2 - 6.0.1

**Issue details / Repro steps / Use case background**: The first time the `AppIntro`screen is shown, it does not show the page selected. Only if we go to the next page and come back it shows the page selected at the page indicator. 

![baconmhc19qsandromachado09302016162225](https://cloud.githubusercontent.com/assets/631739/18996930/3cc01c20-872a-11e6-8b22-5e002c1419d9.png)

I am extending the `AppIntro` and adding `AppIntroFragment` to the activity.

**Comment by avluis** [comment]
Good catch -- will take a look here unless someone else does before me~

**Comment by Andrew-Quebe** [comment]
@avluis I don't have a OP1 or OP2, so I can't do it before you ;)

**Comment by avluis** [comment]
@Andrew-Quebe LOL -- I don't either -- I'm currently building a few activities and checking the sample app as my current implementation does not use the progress indicator~

**Comment by Andrew-Quebe** [comment]
@SandroMachado you're not running a custom ROM, correct?

@avluis something tells me this might be a OP specific issue.

**Comment by avluis** [comment]
@Andrew-Quebe Just finished running the example app across all of my devices -- progress indicator is working -- so can't reproduce.

**Comment by SandroMachado** [comment]
@Andrew-Quebe, not, I am not using a custom ROM. ASAP I will try to fix the issue and make a PR to the library. If I were able to find it. :)

**Comment by Andrew-Quebe** [comment]
@SandroMachado if it's not a OP or ROM issue, it may just be a viewpager bug. I think `4.0.0` and `4.1.0` updated the SDK libs to the latest version; perhaps there's a bug in one of those.

**Comment by SandroMachado** [comment]
I found the problem, it is related to the listener of the view pager. When overridden without calling the super and extending the `PagerOnPageChangeListener`, it breaks the first time, the first page.

So, to override the listener for the page change event it is required to do:
```
 getPager().addOnPageChangeListener(new PagerOnPageChangeListener(){

                @Override
                public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                    super.onPageScrolled(position, positionOffset, positionOffsetPixels);
                }

                @Override
                public void onPageSelected(int position) {
                    super.onPageSelected(position);
                }

                @Override
                public void onPageScrollStateChanged(int state) {
                    super.onPageScrollStateChanged(state);
                }

            });
```

This fixes my issue.

I made a PR to change the access level of the `PagerOnPageChangeListener`, to make it public. And updated the method to add the listener to make it accept only `PagerOnPageChangeListener`.

**Comment by avluis** [comment]
@SandroMachado Tested the sample app on this?

**Comment by SandroMachado** [comment]
Yup.

**Comment by Andrew-Quebe** [comment]
Good work guys! I never have time to test stuff these days :/
