### ISSUE TITLE
Custom Typefaces Ignored

### ISSUE THREAD

**Issue by arcoirislabs** [PaoloRotolo/AppIntro#318]
**AppIntro Version**: 4.1.0

**Device/Android Version**: Xiaomi Mi Max (Android Marshmallow)

**Issue details / Repro steps / Use case background**: 
Just install the release library using Gradle method.
The wizard mode & custom typefaces are not getting applied. Even though the right parameters are passed. No error are reproduced per se. But no typefaces are being applied. It seems that since pull request by @ameykshirsagar is being added, changes are being made. I used the CustomFontCache class to set the typeface using a workaround which means the font asset is being correctly read.

**Your Code**: 
addSlide(AppIntroFragment.newInstance("Setup Panel","OpenSans-Light.ttf", "Lets go through the setup step by step","OpenSans-Regular.ttf" ,R.mipmap.ic_launcher, Color.parseColor("#3F51B5")));

**Stack trace / LogCat**:
Nothing related the issue

**Comment by ameykshirsagar** [comment]
The wizard mode is working fine, but the typefaces are not getting set.

**Comment by avluis** [comment]
If you take a look at the sample app then you'll see that typefaces are still being applied there -- can you cross check for differences between your implementation and the sample implementation?

**Comment by ameykshirsagar** [comment]
@avluis : I was able to reproduce the issue and I found that that latest release is not applying the typeface. The sample implementation was similar to the implementation. You can give a look to the latest pull request. I have mentioned the cause.

**Comment by indrac** [comment]
I'm also has this problem untill now (like what I mentioned on [](https://github.com/PaoloRotolo/AppIntro/pull/267)
Custom typeface not working. but the weird thing, I can change the Skip and Done fonts.
