### ISSUE TITLE
onSlideChanging method request

### ISSUE THREAD

**Issue by theBuggerLabs** [PaoloRotolo/AppIntro#322]
There's no way to cancel (or prevent) the slide change.
For example I have a slide where the user must input a numeric code of a specified length. 
It would be useful to have a "onSlideChanging" method to override. So I can check if the input is not ok and, eventually, cancel the slide change

**Comment by mychaelgo** [comment]
@theBuggerLabs when i take a look on example folder, maybe you can toggle disable swipe or implements ISlidePolicy?

**Comment by theBuggerLabs** [comment]
Yes, I saw ISlidePolicy just after submitting the request. Sorry

Il giorno lun 3 ott 2016 alle ore 16:54 Mychael Christian Go <
notifications@github.com> ha scritto:

**Comment by Andrew-Quebe** [comment]
@theBuggerLabs did you not read the issue template?
