### ISSUE TITLE
Conflict with android.support.v7.app.AlertDialog

### ISSUE THREAD

**Issue by tazeroualti** [PaoloRotolo/AppIntro#327]
Hi all and thank you for your work.
I use android.support.v7.app.AlertDialog in my application.
It want not compile when I add compile 'com.github.paolorotolo:appintro:4.1.0 to my app gradle.
the error is:
Error:Failed to resolve: com.android.support:appcompat-v7:24.2.1

crdlt.

**Comment by Andrew-Quebe** [comment]
Issue template ignored....closing.

**Comment by Andrew-Quebe** [comment]
If you wish to have this reopened, please follow the template, and print full errors.
