### ISSUE TITLE
Question/Request - Hiding the progress dots

### ISSUE THREAD

**Issue by amitav13** [PaoloRotolo/AppIntro#328]
Is there a way to hide the progress dots within the current API?

**Comment by avluis** [comment]
Oh man, come on -- if you are not going to follow the template then you could have just asked me on your prior issue -- @Andrew-Quebe won't be too happy with that -- nor will I for that matter~

**Comment by avluis** [comment]
WTF -- I just clicked on new issue and I'm not seeing the template - is GitHub f*ing up?

**Comment by amitav13** [comment]
@avluis sorry for not following the template, it seemed a bit overkill for such a simple question.

The template had shown for me, might be Github acting up on your end.

Got it, thanks!

**Comment by Andrew-Quebe** [comment]
I usually don't get too upset about the template so long as the question applies, and the inquirer has shown evidence of trying different things.
