### ISSUE TITLE
Can I change position of the indicators in layout?

### ISSUE THREAD

**Issue by expectpin** [PaoloRotolo/AppIntro#329]

**Comment by avluis** [comment]
What have you tried?

**Comment by RUSSCITY** [comment]
@expectpin, yes you can. Here is how I do it:

Create your own DotIndicatorController in onCreate of AppIntro2:

     dotIndicatorController = new DotIndicatorController(this);
     setIndicatorController(dotIndicatorController);


in onResume of AppIntro2 activity:

    @Override
    protected void onResume() {
        super.onResume();

        // size of indicator
        ViewGroup.LayoutParams layoutParams = dotIndicatorController.getLayoutParams();
        layoutParams.height = UIHelper.fromDp(this, 10);
        dotIndicatorController.setLayoutParams(layoutParams);

        // move indicator to bottom
        FrameLayout indicatorContainer = (FrameLayout) dotIndicatorController.getParent();
        ConstraintLayout constraintLayout = (ConstraintLayout) indicatorContainer.getParent();
        ConstraintSet constraintSet = new ConstraintSet();
        constraintSet.clone(constraintLayout);
        constraintSet.connect(indicatorContainer.getId(), ConstraintSet.BOTTOM, constraintLayout.getId(), ConstraintSet.BOTTOM, UIHelper.fromDp(this, 8));
        constraintSet.connect(indicatorContainer.getId(), ConstraintSet.TOP, -1, ConstraintSet.TOP, 0);
        constraintSet.applyTo(constraintLayout);
    }

This allows me to show small progress on the bottom:
![Screenshot_2020-11-04-11-38-01-48_4fe276277b82efdfc9ccadc96143a4bc](https://user-images.githubusercontent.com/9445518/98101443-7f9d3600-1e92-11eb-8947-fe86bcf8a229.jpg)

It would be nice if could have an setting for this directly on AppIntro2.
