### ISSUE TITLE
'Done' button doesn't show when there's only 1 slide

### ISSUE THREAD

**Issue by DeepSpace2** [PaoloRotolo/AppIntro#33]
Hi. 
I don't know if I'm doing something wrong, but if I have only 1 slide the `Done` button isn't showing. Instead there's the `next` arrow button that does nothing.

The issue is with both of the layouts (`AppIntro` and `AppIntro2`).

Thanks for any help and great library :)

This is a sample of my code:

Intro.java:

    import android.content.Intent;
    import android.os.Bundle;
    import android.util.Log;

    import com.github.paolorotolo.appintro.AppIntro2;

    public class Intro extends AppIntro2
    {
        @Override
        public void init(Bundle savedInstanceState)
        {
            addSlide(new FirstSlide(), getApplicationContext());
        }  
    
        @Override
        public void onDonePressed() {
            Log.d("myapp", "done pressed");
            startActivity(new Intent(this, MainActivity.class));
        }
    }

FirstSlide.Java:

    import android.app.Activity;
    import android.os.Bundle;
    import android.support.v4.app.Fragment;
    import android.view.LayoutInflater;
    import android.view.View;
    import android.view.ViewGroup;

    public class FirstSlide extends Fragment
    {
        public static FirstSlide newInstance()
        {
            FirstSlide fragment = new FirstSlide();
            Bundle args = new Bundle();
            fragment.setArguments(args);
            return fragment;
        }

        public FirstSlide()
        {
            // Required empty public constructor
        }

        @Override
        public void onCreate(Bundle savedInstanceState)
        {
            super.onCreate(savedInstanceState);
        }

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                  Bundle savedInstanceState)
        {
            // Inflate the layout for this fragment
            return inflater.inflate(R.layout.fragment_first_slide, container, false);
        }
    
        @Override
        public void onAttach(Activity activity)
        {
            super.onAttach(activity);
        }

        @Override
        public void onDetach()
        {
            super.onDetach();
        }
    }

**Comment by PaoloRotolo** [comment]
Hi @DeepSpace2!
I think there's no point in adding one slide in AppIntro.
Just create your own fragment and add it directly, without using this library :)
