### ISSUE TITLE
Not supporting Navigation Drawer and Drawer layout

### ISSUE THREAD

**Issue by dhruv2601** [PaoloRotolo/AppIntro#330]
**4.1.0**:

**Device/Android Version**:

**colliding with navigation drawer "support" library, ERROR: unable to instantiate SupportMenuInflater  / Repro steps / Use case background**: 

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by avluis** [comment]
Not enough here to go on with or even start with -- please fill out the template entirely.
