### ISSUE TITLE
lag is seen when user slide the screen.

### ISSUE THREAD

**Issue by bheemanm7** [PaoloRotolo/AppIntro#333]
**AppIntro Version**:

4.1.0

**Device/Android Version**:
Samsung galaxy s3 5.0.1

**Issue details / Repro steps / Use case background**: 
i have 3 slides to present to user as tutorial screen. They are shown as expected but during sliding or when next icon pressed lag is observed in transition. I have tried placing my images 
1. drawable-mdpi
2. drawable-hdpi
3. drawable-xhdpi
4 mipmap-mdpi
5. mipmap-hdpi
6. mipmap-xhdpi

**Your Code**: 

        addSlide(AppIntroFragment.newInstance(getResources().getString(R.string.unicorn_title), getResources().getString(R.string.unicorn_description), R.mipmap.unicorn, Color.WHITE));

        addSlide(AppIntroFragment.newInstance(getResources().getString(R.string.rainbow_title), getResources().getString(R.string.rainbow_description), R.mipmap.rainbow, Color.WHITE));

        addSlide(AppIntroFragment.newInstance(getResources().getString(R.string.castle_title), getResources().getString(R.string.castle_description), R.mipmap.castle, Color.WHITE));*/

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by avluis** [comment]
Can you take a video or whatever showing this lag?
