### ISSUE TITLE
Using the layout where the image is below the long description

### ISSUE THREAD

**Issue by imin83** [PaoloRotolo/AppIntro#334]
I tried using AppIntroFragment.newInstance and AppIntro2Fragment.newInstance but couldn't find a way to create layout where the image is BELOW the long description like displayed [here](https://github.com/PaoloRotolo/AppIntro/raw/master/art/layout2.png) 
AppIntro Version: 4.1.0

Device/Android Version**: Alcatel POP 2/Android 4.4

**Comment by avluis** [comment]
https://github.com/PaoloRotolo/AppIntro#alternative-layout
