### ISSUE TITLE
Touch Events bleed through

### ISSUE THREAD

**Issue by kebernet** [PaoloRotolo/AppIntro#34]
If you have a button on a view, touch events for subsequent slides bleed through to the button even though it is not on screen.

**Comment by PaoloRotolo** [comment]
Hi @kebernet!
Maybe there's a problem with your fragment. Can you try adding ```android:clickable="true"``` in your layouts? It should block the touch event.

**Comment by kebernet** [comment]
I actually tried that to no avail. It seems the problem is only when you use the fade transition method. If you disable that, no problem.

**Comment by PaoloRotolo** [comment]
Thanks, I'll investigate.

**Comment by PaoloRotolo** [comment]
Fixed, I'll release a new version in Maven Central soon. Thank you!

**Comment by PaoloRotolo** [comment]
AppIntro 3.0.0 released. Closing.
