### ISSUE TITLE
How to check Settings.ACTION_MANAGE_OVERLAY_PERMISSION in PermissionIntro?

### ISSUE THREAD

**Issue by erginduran** [PaoloRotolo/AppIntro#341]
**AppIntro Version**: 4.1.0

**Device/Android Version**: +23/M

**Issue details / Repro steps / Use case background**: Question

**Your Code**: 

                  if (Build.VERSION.SDK_INT >= 23) {
                        if (!Settings.canDrawOverlays(ContactsActivity.this)) {
                            Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
                                    Uri.parse("package:" + getPackageName()));
                            startActivityForResult(intent, 77);
                        }
                    }

how to check this setting option in permissionintro slide? i use askForPermissions for other Manifest permissions but how can i perform "if(!Settings.canDrawOverlays(ContactsActivity.this)).. " in any method if did not get that permission,user cant skip/pass that slide.i hope you understand what i mean :p

ty

**Comment by avluis** [comment]
This is out of scope for AppIntro -- read [about permissions here](https://developer.android.com/training/permissions/requesting.html) and take a look at the [permission list here](https://developer.android.com/reference/android/Manifest.permission.html).
