### ISSUE TITLE
v4.1.0 is crashed with com.android.support:design:23.4.0

### ISSUE THREAD

**Issue by ryc16** [PaoloRotolo/AppIntro#343]
Hi, 

After I added AppIntro v4.1.0 into dependencies on build.gradle to my app, my app started crashing and couldn't start anymore. The exception is about "Error inflating class android.support.design.widget.FloatingActionButton". I spent some times to check the compatibility. Currently, I am using  com.android.support:design:23.4.0.

If I need to use v4.1.0, I have to use at lesat 24.1.0. However, if I need to keep 23.4.0, I can only use AppIntro v4.0.0. Can you have a look to have AppIntro v4.1.0 compatible on a bit lower as I haven't had plan to upgrade to 24 level yet but still want to have your v4.1.0 feature.

Regards,

**Comment by avluis** [comment]
We can't do much on the library side if you are using older libraries -- but you, as an Android developer, can simply up your SDK level (and the required libraries) while keeping `targetSdkVersion` at  23.
As you update your app and check for compatability on each platform, you can then increase this number.

_Note:_ You should be working on making your app compatible on the latest Android SDK (version 25) unless there is something holding you back -- libraries usually don't -- _for example;_ if your app handles images, but your image viewer is a third party app that doesn't accept content uri, then this would be a valid reason to keep your app on API 23.

**Comment by Andrew-Quebe** [comment]
@avluis doesn't Gradle have some sort of way to target whatever support lib you're using locally? If set on a library, it will use whichever one is local instead of hardcoding the lib to use the latest.

Not to say that the latest is bad, but I don't think a lot of devs update right away.

**Comment by avluis** [comment]
@Andrew-Quebe If you know a way to pull the Android SDK version that the user sets locally into a library then please share 'cause that would be awesome to have documented and implemented.
I have yet to come across that.

What gradle offers is a way to override what library dependencies a particular library introduces -- in order to make use of that, you could try:

```gradle
    compile ("com.github.paolorotolo:appintro:4.1.0") {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
```

Note: I can't guarantee what sort of side-effect you'll have from using the above method.

**Comment by avluis** [comment]
@Andrew-Quebe And I just fired up my IDE to bring what I was talking about into a PR -- note the relation to this issue.
