### ISSUE TITLE
Allow to move to next slide programmatically

### ISSUE THREAD

**Issue by K0bin** [paolorotolo/AppIntro#344]
I'm using AppIntro to host a fragment in which I ask the user to login. I'd love to move to the next slide once the login is successful.

So I'd like to have the ability to move to the next slide with code. Maybe add a new minimal base fragment that has that. Or just expose a method in the Activity and just have the users cast the fragments context to that Activity.

On that note, I'd also love to set the current page in the activity. So I can start it on a certain page depending on Intent Extras.

**Comment by avluis** [comment]
The pager object is exposed exactly for this purpose.

So you can make use of `pager.setCurrentItem(SLIDE_NUMBER);` after initialization.

**Comment by K0bin** [comment]
Oh, I'm sorry. I even looked for that but somehow didn't find it.

**Comment by Ascendance** [comment]
what if we want to do this from inside a fragment?

**Comment by Nfear** [comment]
@Ascendance `((OnboardingIntro) getActivity()).getPager().setCurrentItem(1);`
