### ISSUE TITLE
setting typeface isnt working. 

### ISSUE THREAD

**Issue by noam2** [paolorotolo/AppIntro#346]
**AppIntro Version**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by noam2** [comment]
when i use the new instance constructor and supply 2 fonts typfaces it doesnt put them in title and desrip. my fonts definitely work, in every other place, what should i do?

**Comment by avluis** [comment]
#318 #320

**Comment by noam2** [comment]
sorry i dont understand what you mean. is it possible to fix ?

**Comment by avluis** [comment]
Have you read what I've linked above?

**Comment by Andrew-Quebe** [comment]
@noam2 the numbers listed above are links to issues that have address yours...aka duplicates. Review them, and reopen this if your problem still persists.

**Comment by noam2** [comment]
Hi ,
do you have a good way to design layouts in ANDROID for all screens and
sizes, like you did in the APPIntro library and other libraries that i saw ?
thank You

**Comment by avluis** [comment]
@noam2 https://developer.android.com/guide/practices/screens_support.html
