### ISSUE TITLE
Event observation for fragments

### ISSUE THREAD

**Issue by Sebastian-Hojas** [paolorotolo/AppIntro#351]
Allow fragments to observe sliding events. I'd suggest

```
public interface ISlideObserve
{
   public void slideWillAppear();
   public void slideWillDisappear();
}
```

**Comment by Andrew-Quebe** [comment]
If you want to make a pull request, feel free to submit one. Issues are not the place for code suggestions, as the best place to do that would be a pull request. Thank you :)
