### ISSUE TITLE
Request: Native Back Navigation onBackPressed

### ISSUE THREAD

**Issue by Sebastian-Hojas** [paolorotolo/AppIntro#352]
Would be cool if the walkthrough implements the back button logic from Android (slide back, instead of closing activity) natively.

**Comment by beatbrot** [comment]
Created a pullrequest for this issue [here](https://github.com/paolorotolo/AppIntro/pull/382)

**Comment by Andrew-Quebe** [comment]
@beatbrot merged. Thank you :)
