### ISSUE TITLE
Apply padding of appIntroBottomBarHeight to AppIntroViewPager if necessary (AppIntro)

### ISSUE THREAD

**Issue by xxtesaxx** [paolorotolo/AppIntro#355]
If you use custom fragments as slides and set the bar color, the bar is hiding parts of your custom ui. To get around this "issue", you can apply "android:paddingBottom="@dimen/appIntroBottomBarHeight"" to your fragments root layout. 

Do you think it would be useful to have a method on AppIntro to apply the padding to AppIntroViewPager in intro_layout.xml or even to automatically apply if the barcolor is set to a color without alpha?

We could for example use "Color.alpha(color) == 255" in setBarColor() to check if we need to apply the padding.

**Comment by Andrew-Quebe** [comment]
I don't think extra methods are necessary when you can pass a fragment containing a scrollview to the library.
