### ISSUE TITLE
Fabric + AppIntro

### ISSUE THREAD

**Issue by PaoloLoconsole** [paolorotolo/AppIntro#359]
Version of AppIntro you're running, for example: 4.1.0
Stack trace / LogCat: Failed to execute task. java.util.concurrent.TimeoutException at java.util.concurrent.FutureTask.get(FutureTask.java:176) at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44) at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235) at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693) at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690) 11-18 12:08:28.119 5675-5675/it...here E/AndroidRuntime: FATAL EXCEPTION: main Process: it...here, PID: 5675 java.lang.RuntimeException: Unable to start activity ComponentInfo{it....e.AndroidExplorer}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=630261345 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376) at android.app.ActivityThread.access$800(ActivityThread.java:147) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5253) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:949) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:744) Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=630261345 at android.support.v4.util.SimpleArrayMap.setValueAt(SimpleArrayMap.java:353) at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:589) at it....re.AndroidExplorer.onStart(AndroidExplorer.java:389) at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220) at android.app.Activity.performStart(Activity.java:5991) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)  at android.app.ActivityThread.access$800(ActivityThread.java:147)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:135)  at android.app.ActivityThread.main(ActivityThread.java:5253)  at java.lang.reflect.Method.invoke(Native Method)  at java.lang.reflect.Method.invoke(Method.java:372)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:949)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:744) 

Initialing of Fabric try { Fabric.with(this, new Crashlytics()); Crashlytics.log("AndroidExplorer.onCreate"); } catch (Exception e) { Crashlytics.log("AndroidExplorer.onCreate --> error"); }
Code of ...AndroidExplorer.onStart(AndroidExplorer.java:389)
@Override
protected void onStart() {
    super.onStart();
}
My Gradle file
apply plugin: 'com.android.application' apply plugin: 'io.fabric' buildscript {
repositories {
    maven { url 'https://maven.fabric.io/public' }
}

dependencies {
    classpath 'io.fabric.tools:gradle:1.+'
}
}
repositories { maven { url 'https://maven.fabric.io/public' } mavenCentral()
}
dependencies { compile 'com.android.support:appcompat-v7:24.2.1' compile fileTree(dir: 'libs', include: '*.jar') compile 'com.android.support:multidex:1.0.0' compile('com.google.android.gms:play-services-ads:7.5.0') { exclude module: 'support-v4' } compile project(':mupdf') compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') { transitive = true; } compile project(':actionsContentViewLib') // compile 'com.google.android.gms:play-services-identity:7.5.0' compile('com.google.api-client:google-api-client-android:1.22.0') { exclude group: 'org.apache.httpcomponents' } compile('com.google.apis:google-api-services-drive:v2-rev244-1.22.0') { exclude group: 'org.apache.httpcomponents' } compile project(':library')
compile 'com.github.paolorotolo:appintro:4.1.0'
}
android {
configurations {
    all*.exclude group: 'com.android.support', module: 'support-v4'
}

lintOptions {

    checkReleaseBuilds false

}
signingConfigs {
    config {
        keyAlias 'printanywhere'
        keyPassword 'aryonsolutions'
        storeFile file('../keystore/release/PrintAnywhere')
        storePassword 'aryonsolutions'
    }
}
compileSdkVersion 23
buildToolsVersion "23.0.2"

defaultConfig {
    minSdkVersion 13 //lower than 14 doesn't support multidex
    targetSdkVersion 23

    multiDexEnabled true
}
sourceSets {
    main {
        manifest.srcFile 'AndroidManifest.xml'
        java.srcDirs = ['src']
        resources.srcDirs = ['src']
        aidl.srcDirs = ['src']
        renderscript.srcDirs = ['src']
        res.srcDirs = ['res']
        assets.srcDirs = ['assets']
    }

    // Move the tests to tests/java, tests/res, etc...
    instrumentTest.setRoot('tests')

    // Move the build types to build-types/<type>
    // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
    // This moves them out of them default location under src/<type>/... which would
    // conflict with src/ being used by the main source set.
    // Adding new build types or product flavors should be accompanied
    // by a similar customization.
    //debug.setRoot('build-types/debug')
    //release.setRoot('build-types/release')

}
buildTypes {
    NewBuild {
        debuggable false
        jniDebuggable false
        signingConfig signingConfigs.config
        renderscriptDebuggable false
        minifyEnabled false
        zipAlignEnabled true
        shrinkResources false
        proguardFile 'proguard.cfg'
    }
    release {
// debuggable true // shrinkResources true // minifyEnabled true // proguardFiles getDefaultProguardFile('proguard-android.txt'), // 'proguard-rules.pro' debuggable false minifyEnabled false signingConfig signingConfigs.config proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' zipAlignEnabled true shrinkResources false proguardFile 'proguard.cfg' } } dexOptions { javaMaxHeapSize "4g" }
}

**Comment by avluis** [comment]
Why was another issue opened? Just reopen the issue you already had...
