### ISSUE TITLE
Conversion on Library from Android Studio to Eclipse

### ISSUE THREAD

**Issue by cashlex** [paolorotolo/AppIntro#364]
Am trying to convert the Library from Android Studio to Eclipse but it seems that its very difficult can you help me out

**AppIntro Version**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by avluis** [comment]
This is no longer supported by Google -- please provide a valid reason and reopen this issue.

**Comment by Andrew-Quebe** [comment]
Since Google [officially no longer supports Eclipse](http://www.androidpolice.com/2015/06/26/google-officially-ends-support-for-adt-with-eclipse-urges-android-developers-to-migrate-projects-to-android-studio/), we won't be migrating the library over to it. Have a look at migrating your Eclipse projects over to Android Studio [here](https://developer.android.com/studio/intro/migrate.html).

**Comment by Andrew-Quebe** [comment]
@avluis you beat me ;)

**Comment by cashlex** [comment]
To be frank We over here prefer Eclipse to Android studio because of many reason like easy app building , easy error fixing, fast app building, fast loading of eclipse when opened , even eclipse now support gradle

if you go to developers.google.com you will see that eclipse is still supported by google and as android studio is being upgraded eclipse and its plugin is also upgrade and making it easy to convert / downgrade  Android studio App to eclipse . Android studio gradle sometimes build / run for 28 hours and still building without completion so you see eclipse is more better

i arrest my case

**Comment by Andrew-Quebe** [comment]
@cashlex did you click the links in my comment? Google NO LONGER supports Eclipse...they said so on their own developer blog! [CLICK HERE](http://android-developers.blogspot.com/2015/06/an-update-on-eclipse-android-developer.html) to visit that post.

_**To that end and to focus all of our efforts on making Android Studio better and faster, we are ending development and official support for the Android Developer Tools (ADT) in Eclipse at the end of the year. This specifically includes the Eclipse ADT plugin and Android Ant build system.**_ 

Granted, it's not the end of the year quite yet...but there's about a month left in this year, and by the time we migrate our library, it will be 2017. Android Studio is the main IDE for developing Android apps, and if you have a worthy machine that isn't from the 1980's, you'll be compiling your Android apps and libraries in about 30 seconds. (My Macbook Air from 2013 compile times are generally this.)

**Comment by cashlex** [comment]
you guys are using a more faster machine we are still stock on Windows like Toshiba AMD processor the problem is in bring new advance machine is that we are running on high Power voltage  my country supply power to most of the African countries so must USA product are not compatible in my country and the advance Machines here are mostly China product which have record in burning up and exploding so we prefer using Core 2, i3 and lower once because are are stronger than most core i 5 and i7 which are imported 

and our president stop the importation of everything even cars and placed a high tariff on others so we use what we have 

thats why eclipse is more preferable and also i thing Android studio have issues every upgrade they make have more issues than the last

**Comment by cashlex** [comment]
please how can i solve this problem in Eclipse project while trying to build it 

[2016-11-27 11:38:03 - Dex Loader] Unable to execute dex: Multiple dex files define Lcom/google/android/gms/internal/zznv;
[2016-11-27 11:38:03 - Pocket-v1.3] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lcom/google/android/gms/internal/zznv;

**Comment by HeinrichReimer** [comment]
@cashlex Come on, Android Studio runs perfectly on my 4-year-old laptop running  an i3.
Maybe your build will take a minute longer but what's that compared to the advantages Android Studio has over Eclipse. And with instant run enabled you'll get even better build times. 
Don't blame these excellent library developers for not supporting a deprecated IDE. Don't forget: What they offer you is completely free and they gain nothing back other than experience.
In my language there's a proverb saying "Einem geschenkten Gaul guckt man nicht ins Maul". That basically means you should never judge something you get for free.
If you want support for Eclipse don't hesitate to fork this repo and add support by yourself but don't blame the developer!

**Comment by cashlex** [comment]
No I never blamed any developer . I found out that IntellJ is best alternative to Android studio . it builds app BTW 2 to 45 mins depending on the size and libraries involved .I got a fairly used core i3 laptop because of android studio but haven't tested it with android studio.its like IntellJ is a middle ide BTW android studio and eclipse . all errors in android studio was fixed in IntellJ even due IntellJ is a lite weight software  thanks all

**Comment by HeinrichReimer** [comment]
Haha, IntelliJ is Android Studio + extra core Java functionality. So if you have IntelliJ, you wouldn't need Android Studio anyway 😄
