### ISSUE TITLE
Example to use too complex ! 

### ISSUE THREAD

**Issue by hieuxinhe94** [paolorotolo/AppIntro#371]
It's cool!, but
I need a basic app , very easy to use .
You should make isolation some level of your library.
good job!

**Comment by avluis** [comment]
Is this an issue? Can't tell.

**Comment by Andrew-Quebe** [comment]
@hieuxinhe94 the sample app is intended to show off everything the library does...in my redesigns, I've tried my best to simplify the UI to make it easy to navigate and understand the full power of the library. 

In terms of code navigating (to see how certain things look in code), I've also sorted all the files to make them easily distinguishable. Can you elaborate on what you mean by a basic app? I'm only asking to gain feedback...I'm not sure how a library demo can be any simpler than what's already there.
