### ISSUE TITLE
Permissions management and AppIntro.

### ISSUE THREAD

**Issue by YPierru** [paolorotolo/AppIntro#376]
**AppIntro Version**:4.1.0

**Device/Android Version**:One Plus X Android 6.0.1

**Issue details / Repro steps / Use case background**: 
I absolutely need to ask some permissions to my user at the first start of the app. However that's exactly at this moment that I want to show the AppIntro. The AppIntro would be also usefull to explain to my user why I need further permissions.
The thing is that where I should ask the permissions... If I do it in the onCreate of my MainActivity, the dialog popup asking for permissions will prompt at the same time than the AppIntro.
So I could do it in the "onSkipped" or "onDone" of the AppIntro... but what if my user remove some permissions after accepted it first ? As the AppIntro is only shown at the installation, the application will not asked them again and will crash....
Do you have an idea on the best way to do it ?

Thanks !

**Comment by avluis** [comment]
@Andrew-Quebe Do we not have a wiki explaining how to tackle permissions with AppIntro (though if you look at the README, it has all you need on the AppIntro side -- as for the rest of the app, devs need to look at Android dev guide).

**Comment by avluis** [comment]
On another note, do we need to prep a template for issues asking for help instead of big reports?

**Comment by Andrew-Quebe** [comment]
@YPierru you can refer to the [README](https://github.com/paolorotolo/AppIntro#runtime-permissions-android-60) for info on the best way to present permission requests to your users. The AppIntro library does it by asking on the slide you provide an explanation (i.e. explanation on slide 2, request on slide 2 assuming your code is right).

**Comment by Andrew-Quebe** [comment]
@avluis The Wiki doesn't explain permissions other than providing a few lines of code. We should probably work on that. 

I'll make some modifications to the issue template to make sure people are reading what they should be reading before opening an issue. 

However, some people will still ignore that, and all we have to do is close issues that don't follow our rules. We've made them clear...if people ignore them, it's our right to act accordingly. And if they complain about our actions, we simply point them in the direction of the things they failed to read the first time.
