### ISSUE TITLE
Support for Android TV (Intro2)

### ISSUE THREAD

**Issue by Fleker** [PaoloRotolo/AppIntro#38]
I can navigate between slides using the Dpad, but I can't finish the intro. There's no way of pressing the done button. 

In my Intro class, which extended `AppIntro2`, I added this method. I recommend that you include this in the class. I can fork the project and make a pull request if you want.

    @Override
    public boolean onKeyDown(int code, KeyEvent kvent) {
        if(code == KeyEvent.KEYCODE_ENTER || code == KeyEvent.KEYCODE_BUTTON_A) {
            ViewPager vp  = (ViewPager)this.findViewById(com.github.paolorotolo.appintro.R.id.view_pager);
                if(vp.getCurrentItem() == vp.getAdapter().getCount()-1) {
                    onDonePressed();
                 } else {
                    vp.setCurrentItem(vp.getCurrentItem()+1);
                }
                return false;
            }
            return super.onKeyDown(code, kvent);
        }

**Comment by PaoloRotolo** [comment]
@Fleker Thank you! Can you open a pull request please?
