### ISSUE TITLE
Can't add slide with method addSlide

### ISSUE THREAD

**Issue by Marcusjnr** [paolorotolo/AppIntro#391]
![screenshot 8](https://cloud.githubusercontent.com/assets/18102852/21467222/1fba44e4-c9e6-11e6-9e1c-4aa595f45958.png)

**AppIntro Version**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

I am new to android development. I can't add a slide in using this library with this method. I have browsed the solution but i haven't found a solution. It keeps giving me this error
addSlide
(android.support.v4.app.Fragment)
in AppIntroBase cannot be applied
to
(com.cuid.gigabytedevelopersinc.splanner.SampleSlide)

**Comment by avluis** [comment]
@Marcusjnr Hey there~
Start by removing this static import: `import static android.R.attr.fragment`.
Then, can you post all of the code above. I need to see all of your import statements.

**Comment by Marcusjnr** [comment]
My code has changed since then cause i had continued trying. These are all my imports now but it is still not working


`    package com.cuid.gigabytedevelopersinc.splanner1;

     import android.os.Bundle;
     import android.support.annotation.Nullable;

     import com.github.paolorotolo.appintro.AppIntro;

     public class Slide_Start extends AppIntro {

        @Override
            protected void onCreate(@Nullable Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            addSlide(SampleSlide.newInstance(R.layout.slide_1));
    }
}
`

**Comment by avluis** [comment]
Did you modify `SampleSlide` in any way?

**Comment by Marcusjnr** [comment]
here is the SampleSlide

`package com.cuid.gigabytedevelopersinc.splanner1;

      import android.app.Fragment;
     import android.os.Bundle;
     import android.support.annotation.Nullable;
     import android.view.LayoutInflater;
     import android.view.View;
      import android.view.ViewGroup;


     public class SampleSlide extends Fragment {

    private static final String ARGS_LAYOUT_RES_ID ="layoutResId";
    private int layoutResId;

    public static SampleSlide newInstance(int layoutResId)
    {
        SampleSlide sampleSlide = new SampleSlide();


        Bundle args = new Bundle();
        args.putInt(ARGS_LAYOUT_RES_ID,layoutResId);
        sampleSlide.setArguments(args);

        return sampleSlide;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (getArguments()!=null && getArguments().containsKey(ARGS_LAYOUT_RES_ID))
        {
            layoutResId = getArguments().getInt(ARGS_LAYOUT_RES_ID);
        }
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(layoutResId,container,false);
    }
}
`

**Comment by avluis** [comment]
I already see the issue.

Look at your imports on the file above -- note that you are importing the built-in Fragment and not the support library version.
Change that line to this: `import android.support.v4.app.Fragment;`

Or simply copy the contents of this [file](https://github.com/paolorotolo/AppIntro/blob/master/example/src/main/java/com/amqtech/opensource/appintroexample/util/SampleSlide.java).
Make sure to keep your own package name at the top when doing so.

**Comment by Marcusjnr** [comment]
Wow thank you so much i am very grateful worked like a charm.
