### ISSUE TITLE
RTL not supported in Gradle

### ISSUE THREAD

**Issue by vladik1985ab** [paolorotolo/AppIntro#396]
Hi  , 
thanks for the great work , I try to implement your library to my project 
I know that month ago you implemented RTL support.
 I noticed that the RTL is not supported yet in the Gradle / Maven (4.1.0 version),
could u please synchronizing the projects

**Comment by mfonville** [comment]
I also think that @beatbrot's RTL code should warrant a new release, it is a great and import addition to the project

**Comment by avluis** [comment]
A release will be pushed to gradle when @paolorotolo and @Andrew-Quebe feel the library is ready.
So please, there is no need to open an issue to inquire when the next release will be, as that in itself is not an issue.

But, if you wish to have the latest code from the repo, there is always [JitPack](https://jitpack.io/#paolorotolo/AppIntro/-SNAPSHOT).
