### ISSUE TITLE
appintro crashes by showing images

### ISSUE THREAD

**Issue by Excel1** [paolorotolo/AppIntro#402]
Version:
version of AppIntro: 4.1.0

Device:
fails on Galaxy S5 5.1

        

I used AppIntro, it workes pretty nice but i have some problems with it.
I used the Code:

addSlide(AppIntroFragment.newInstance("Klasseneinteilung", "Anstatt Jahrgänge werden nun Klassen untersützt (6a;6b;...)", R.drawable.st3 , Color.parseColor("#f50057")));

to create a slide with a picture. Ofcourse it works but it crashes, when i used 4 of the slides with an Image.

Error:
java.lang.outofmemory

I red on a OverStack Topic, that i can give the App more Memory, i did it and it helps. Now my App can hold ~6. But it will crash.

Also lag the Slide with the Image.

**Comment by avluis** [comment]
Sounds like you need to deflate, compress/optimize those images.
The issue you are having is exactly as described, you are running out of memory here. Doesn't sound like a leak so take a good look at the images that you are using.

**Comment by Andrew-Quebe** [comment]
I'd suggest linking us to your images to see if that's the issue...and/or check out the images in any kind of image viewer on your computer. Android tends to crash if images are over ~2000px from what I've seen.

**Comment by TomCyril1** [comment]
Open the picture with paint, reduce it by  40%,
Crop it  , and save it ,
then  reput it on your workspace  ,  its working for me, no more lag  or crashes

**Comment by TomTasche** [comment]
I had the same problem (see https://blog.tomtasche.at/2018/11/designing-good-on-boarding-experience.html) and fixed it by using an Android Studio plugin called "Android Drawable Importer".

**Comment by cortinico** [comment]
Closing as inactive and potential solutions were offered
