### ISSUE TITLE
"SKIP" button in all the Fragments

### ISSUE THREAD

**Issue by vinod-jaiswal18** [PaoloRotolo/AppIntro#43]
Hey,
Does this library has feature to keep the "SKIP" button always active for all the fragments.
Thanks,
Vinod

**Comment by PaoloRotolo** [comment]
Hi @vinod-jaiswal18!
Just use ```showSkipButton(true);```. Please note that skip button is not available with second layout (AppIntro2).

**Comment by vinod-jaiswal18** [comment]
Hey @PaoloRotolo ,
Ohh, I just missed it. The function 'showSkipButton()' is available.
Thanks,
Vinod
