### ISSUE TITLE
addslide

### ISSUE THREAD

**Issue by shanmmukha1589** [PaoloRotolo/AppIntro#44]
when i use it its show error
Error:(20, 13) error: cannot find symbol method addSlide(FirstSlide,Context)

addSlide(new FirstSlide(), getApplicationContext());

**Comment by mohak1712** [comment]
U nedd to add fragmemts name FirstSlide and pass their instance here
There is a predefined method when u create fragments in android studio (new instance) i can just call the method in addSlide() it takes 2 strings as parameters and u r done

**Comment by shanmmukha1589** [comment]
Can you please explain in a step by step process i am new to android development..

**Comment by mohak1712** [comment]
i dont think my answer is something you are looking for but u can try this
https://github.com/mohak1712/AppIntro

**Comment by shanmmukha1589** [comment]
thanku

**Comment by shanmmukha1589** [comment]
Still same error 
and 
addSlide in in red state in android studio

**Comment by mohak1712** [comment]
Make sure that ur fragment import class is android.support.v4.fragment and not something else thats the last thing i can think of!

**Comment by shanmmukha1589** [comment]
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Toast;
import com.msrkumar.tracker.rtcinfo.Main;
import com.msrkumar.tracker.rtcinfo.slides.FirstSlide;
import com.msrkumar.tracker.rtcinfo.slides.SecondSlide;
import com.msrkumar.tracker.rtcinfo.slides.ThirdSlide;


/**
 * Created by msrkumar on 7/10/2015.
 */
public class Intro extends Main{

    public void init(Bundle savedInstanceState){
            addSlide(new FirstSlide(), getApplicationContext());
            addSlide(new SecondSlide(), getApplicationContext());
            addSlide(new ThirdSlide(), getApplicationContext());
    }

    private void loadMainActivity(){
        Intent intent = new Intent(this, Main.class);
        startActivity(intent);
    }

    public void onSkipPressed(){
        loadMainActivity();
        Toast.makeText(getApplicationContext(),"Introduction Skipped",Toast.LENGTH_SHORT).show();
    }

    public void onDonePressed() {
        loadMainActivity();
    }

    public void getStated(View v){
        loadMainActivity();
    }

}




addslide i red marked in my code

**Comment by shanmmukha1589** [comment]
https://www.quora.com/How-do-i-fix-this-problem-in-android-code
