### ISSUE TITLE
Hide done button

### ISSUE THREAD

**Issue by laminsk** [PaoloRotolo/AppIntro#47]
Hi there

Thanks for the great library, I'm trying to use it for my personal project and have a quick question regarding done button. Basically, I just want to hide the button at all times (or only hide the button when it reaches to the final slide) and present the user with options to register or login in the final slide (will implement my own buttons for that). Any help would be greatly appreciated.

Many Thanks

**Comment by PaoloRotolo** [comment]
Will be fixed in next release.

Thank you!

**Comment by ashokslsk** [comment]
Any Updates on this feature how to hide done button @PaoloRotolo
