### ISSUE TITLE
Issue for 1 slide only

### ISSUE THREAD

**Issue by marbat87** [PaoloRotolo/AppIntro#48]
Hi,

When I create a class with only 1 slide, the "next" button is shown in place of "done" button and it does nothing.
Could you please fix it?

I also would really appreciate if you make the library compatible with API 8.
I made I locally (using nineoldandroid) and it's very easy, but then is boring to merge code when you make updates.
Let me know if you need help with this.

P.S. I'm Italian too :)

Regards,
Marcello

**Comment by JamesGBritton** [comment]
Hi,

I am having the same issues when I only display one screen.

The users is completely unable to continue, if there is only one screen. The current *fix* is to just add another screen. Which is not ideal ;)

Many thanks,
James

**Comment by PaoloRotolo** [comment]
Hi guys,
the issue should be fixed in next AppIntro release.

Thank you.

**Comment by marbat87** [comment]
Any hope for API 9?

I created a pull request:
https://github.com/PaoloRotolo/AppIntro/pull/50

Thanks in advance
