### ISSUE TITLE
Translation please.....

### ISSUE THREAD

**Issue by javierpe** [paolorotolo/AppIntro#5]
Translation for SKIP and DONE...

**Comment by StefanFaulhaber** [comment]
+1

**Comment by QuadFlask** [comment]
:+1:

**Comment by Bernix01** [comment]
+1

**Comment by javiersantos** [comment]
You could use a localization management platform, like CrowdIn (it's free for Open Source projects).

**Comment by PaoloRotolo** [comment]
Hey guys,
I'll try to set up a management platform, thanks. Meanwhile, try Layout2: you shouldn't have issues with localization.

<img src="https://github.com/PaoloRotolo/AppIntro/blob/master/art/layout2.png" width="300"> 
<img src="https://github.com/PaoloRotolo/AppIntro/blob/master/art/layout2_2.png" width="300"> 

Cheers,
Paolo

**Comment by deinlandel** [comment]
You can just override texts in your app's values.xml
For example (russian):
```xml
<string name="skip_button">Пропустить</string>
<string name="done_button">Готово</string>
```

**Comment by FranciscoJavierPRamos** [comment]
+1

**Comment by HeinrichReimer** [comment]
@PaoloRotolo Any updates on this?

**Comment by OzoTek** [comment]
Works perfectly with @deinlandel's answer :-)

**Comment by Andrew-Quebe** [comment]
Update: #291 and #292 added German and Spanish translations. As soon as @PaoloRotolo has time, these changes will be available.

**Comment by Andrew-Quebe** [comment]
Update: #321 added Indonesian translations. Will be published in next release.

**Comment by mychaelgo** [comment]
I think is more efficient if we add prefix on every string we have add to prevent resources merge conflict? 

For example for string skip button:
```
<string name="app_intro_skip_button">Готово</string>
```

**Comment by Andrew-Quebe** [comment]
@mychaelgo what do you mean?

**Comment by avluis** [comment]
@Andrew-Quebe I'm thinking he is referring to the string names -- it is a bit of standard practice to prefix library strings with the name of the library in order to guarantee uniqueness and avoid overriding a string unintentionally.

**Comment by Andrew-Quebe** [comment]
@mychaelgo ahh...yeah you're right. My mistake for not knowing what you meant ;)

**Comment by mychaelgo** [comment]
yeah, no problem

**Comment by Andrew-Quebe** [comment]
Update: #365 and #366 added Arabic and Turkish translations.

**Comment by Andrew-Quebe** [comment]
Update to everyone who has added translations...the example app is needing to be translated as well, and I'm in the process of revamping it. I'll report back here when done, but for now, refer to the file listed in 46f9d36e6a692e370b7a62b5878b71e21f93a73e.

**Comment by araratm** [comment]
I tried to override strings on android but it doesn't work for Armenian.

    <string name="skip_button">Անցնել</string>
    <string name="done_button">Ավարտել</string>

Please add if you can.

**Comment by oskarh** [comment]
@araratm The keys for the strings have changed, try overriding the new key values:

```
<string name="app_intro_skip_button">Անցնել</string>
<string name="app_intro_done_button">Ավարտել</string>
```

**Comment by chocolatesoup** [comment]
I would suggest you just add an example to the instructions on how to add your custom translations, i.e.:

To translate the buttons, add the following strings and their translations:
```
<string name="app_intro_skip_button">SKIP</string>
<string name="app_intro_done_button">DONE</string>
```
Then you can safely close this issue.

**Comment by paolorotolo** [comment]
Fix merged, we can close this. 
Thanks.
