### ISSUE TITLE
Extend AppCompatActivity rather than FragmentActivity

### ISSUE THREAD

**Issue by cr5315** [PaoloRotolo/AppIntro#52]
Because AppIntro and AppIntro2 use FragmentActivity as their base class, the material for pre-Lollipop doesn't take effect in the Fragments. I'm going to make a fork and test out using AppCompatActivity instead.

**Comment by PaoloRotolo** [comment]
Thanks, let me know :)

**Comment by cr5315** [comment]
Well, it didn't fix my specific issue, but it may still be worthwhile to do since AppCompatActivity ends up extending FragmentActivity down the line. I also updated the support library versions to 22.2.1.

**Comment by PaoloRotolo** [comment]
Good! @cr5315 waiting for your pull request (and yes, add your app in README too). :+1:

**Comment by raphaelcuba** [comment]
@PaoloRotolo this issue can be closed.

**Comment by PaoloRotolo** [comment]
Right, closing.
Thanks!
