### ISSUE TITLE
Add setDrawable(drawable) property

### ISSUE THREAD

**Issue by seba123neo** [paolorotolo/AppIntro#532]
I need to add a drawable variable, not a resource int

**Comment by TomTasche** [comment]
There is setImageNextButton on AppIntro.java

**Comment by TomTasche** [comment]
In case you were referring to the image of a SliderPage, you can use the onSlideChanged-callback to change the content of the next page before it's displayed:

```
// this is the ImageView - modify it as needed
newFragment.getView().findViewById(R.id.image);
```

**Comment by cortinico** [comment]
Looks like we can close here
