### ISSUE TITLE
If back button is pressed in the first slide it returns to the MainActivity 

### ISSUE THREAD

**Issue by Prakashk141** [paolorotolo/AppIntro#540]
**AppIntro Version**: 4.2.3

**Device/Android Version**: 7.1.2

If the user presses the back button when the first slide comes it takes directly to the MainActivity instead of exiting the app.

**Comment by noam1023** [comment]
Pressing the Back cause the activity to finish and return to the previous activity in the task. You probably started the AppIntro activity from MainActivity, so this is normal behavior

**Comment by cortinico** [comment]
Closing as this is not an issue but the intended behavior @Prakashk141
