### ISSUE TITLE
Manifest merger failed : Attribute application@supportsRtl

### ISSUE THREAD

**Issue by hoseinsttr** [paolorotolo/AppIntro#553]
Hi
I use AppIntro v4.2.3 and I set  android:supportsRtl="false" in manifest.
when I want to sync gradle this error apears:

_Manifest merger failed : Attribute application@supportsRtl value=(false) from AndroidManifest.xml:26:9-36
	is also present at [com.github.apl-devs:appintro:v4.2.3] AndroidManifest.xml:11:18-44 value=(true).
	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:24:5-70:19 to override._

I tried to add  tools:replace="android:supportsRt" to Manifest But encounter with new error(Manifest merger failed with multiple errors)

**Comment by cortinico** [comment]
Hey @hoseinsttr 

I had the same issue a couple of days ago.
After you set both `tools:replace` and `android:supportsRtl` on your app manifest, run a clean build and everything should work fine.

**Comment by hoseinsttr** [comment]
Thanks
I found another solution for issue.
just add          tools:node="replace"    to application tag


```
<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        tools:node="replace"
        android:supportsRtl="false"
        android:label="@string/app_name"
        android:roundIcon="@drawable/arzancell"
        android:theme="@style/AppTheme">
        <activity android:name=".BasteActivity">
```

**Comment by cortinico** [comment]
Closing as looks solved
