### ISSUE TITLE
Multi language app   android:supportsRtl="true" 

### ISSUE THREAD

**Issue by NLLAPPS** [paolorotolo/AppIntro#587]
I have a multi language app with has    android:supportsRtl="true" in the Manifest. This causes library to assume that app is in a RTL language.  Although app's language at first run is the default locale which may be RTL or LTR

Culprit seems to  be LayoutUtil class.

Is there any way to override this?

**Comment by paolorotolo** [comment]
Yes, I can reproduce this. We're working on a fix ASAP.
