### ISSUE TITLE
Setting up a proper CI environment

### ISSUE THREAD

**Issue by cortinico** [paolorotolo/AppIntro#589]
Hey @paolorotolo 
If is fine for you, I'd love to set up some CI for building and executing some tests (that we currently don't have but would be cool to have) on AppIntro.

Do you have preferences on this? Otherwise, I'd go for either Travis or Circle.

**Comment by paolorotolo** [comment]
Absolutely yes! I've used Travis in another Open Source project and developed a CrowdIn integration with it to automatically download and let people crowdfund string translation. We could reuse some code.
