### ISSUE TITLE
Update to 5.0.0 fails

### ISSUE THREAD

**Issue by mueller-ma** [paolorotolo/AppIntro#591]
**AppIntro Version**: 5.0.0

**Issue details / Repro steps / Use case background**: I have migrated the app to AndroidX, but it's still not possible to update to 5.0.0.
PR: https://github.com/openhab/openhab-android/pull/1035
CI: https://travis-ci.org/openhab/openhab-android/builds/441747775#L1973

Can you help me with migrating to 5.0.0?

**Comment by cortinico** [comment]
Hey @mueller-ma I tried to checkout your branch locally but I wasn't able to build because of `google-services.json` missing. Do you have a debug file to share?

**Comment by mueller-ma** [comment]
The file is in the repo (https://github.com/openhab/openhab-android/blob/master/mobile/google-services.json), but some flavors don't build. Can you try fullStable?

**Comment by paolorotolo** [comment]
You have a dependency conflict with annotations package from IntelliJ, thus you need to esclude that when adding AppIntro.

I opened a new pull here that fixes the issue: https://github.com/openhab/openhab-android/pull/1051

**Comment by mueller-ma** [comment]
Thanks!
