### ISSUE TITLE
No SKIP button for Layout2

### ISSUE THREAD

**Issue by checklist** [PaoloRotolo/AppIntro#60]
Great job! 

We are missing the SKIP button for AppIntro2.

**Comment by PaoloRotolo** [comment]
Hi @checklist,
AppIntro2's design is inspired by Google Photos app. Unfortunately they didn't provide design for Skip button.
You're free to implement it by yourself, simply adding a button in your fragment.

Have fun!

**Comment by xsorifc28** [comment]
@PaoloRotolo I think it would be a good idea to implement the skip method, even if Google has not provided it. Helps when user has cleared the app data and would want to skip the intro screen. It's not an issue add it manually, but wouldn't hurt to have in the library either.
