### ISSUE TITLE
Problem on (addSlide) in AndroidX

### ISSUE THREAD

**Issue by Mr-ARBN** [paolorotolo/AppIntro#609]
I'm using AndroidX
this part will not work on AndroidX.
we get error (Cannot resolve method 'addSlide(com.github.paolorotolo.appintro.AppIntroFragment)'
on this part of code < addSlide(AppIntroFragment.newInstance(sliderPage)); >

![image](https://user-images.githubusercontent.com/39969822/47937795-20993500-def7-11e8-8a48-7c938ccfe712.png)

**Comment by cortinico** [comment]
Hey @Mr-ARBN 
The problem is exactly what I mentioned:

> Are you subclassing either AppIntro or AppIntro2? Looks like not.

In your code you have

```java
public class IntroductionActivity extends AppCompatActivity {
```

You need to replace `AppCompatActivity` with either `AppIntro` or `AppIntro2`.

**Comment by Mr-ARBN** [comment]
Thank you.

**Comment by Mr-ARBN** [comment]
> 
> 
> Hey @Mr-ARBN
> The problem is exactly what I mentioned:
> 
> > Are you subclassing either AppIntro or AppIntro2? Looks like not.
> 
> In your code you have
> 
> ```java
> public class IntroductionActivity extends AppCompatActivity {
> ```
> 
> You need to replace `AppCompatActivity` with either `AppIntro` or `AppIntro2`.

@cortinico  thank you

**Comment by cortinico** [comment]
You're welcome 💪
