### ISSUE TITLE
v5.1.0 fails when using com.android.support:appcompat-v7:28.0.0

### ISSUE THREAD

**Issue by GabrielBB** [paolorotolo/AppIntro#617]
It gives this error:

> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
> 	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
> 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:15:5-83:19 to override.

**tools:replace="android:appComponentFactory"** doesn't resolve the problem, it adds another one

**Comment by cortinico** [comment]
Hey @GabrielBB 

This issue was already reported in #610 
In order to use the latest version of AppIntro, you need to use AndroidX. If you don't migrate to AndroidX, use the version `v4.2.3` of the library.

**Comment by GabrielBB** [comment]
Understood. Thanks for the quick response.

**Comment by cortinico** [comment]
You're welcome :)
