### ISSUE TITLE
Buttons are white when pressed

### ISSUE THREAD

**Issue by deinlandel** [PaoloRotolo/AppIntro#62]
In AppIntro (not AppIntro2), when you use Appcompat theme, buttons are becoming white when pressed (this bug is reproduced in your example app). I guess this is because new appcompat requires to extend AppCompatActivity for button color tinting to work. I think you should upgrade your library to support proper button theming.

**Comment by PaoloRotolo** [comment]
Hi @deinlandel,
I actually can't reproduce this issue. Can you provide screenshots?
Did you tried latest AppIntro release (cloning from github)?

![screenshot from 2015-07-29 18 04 26](https://cloud.githubusercontent.com/assets/5623301/8962724/5c909f9e-361c-11e5-8c11-324299db2b27.png)

![screenshot from 2015-07-29 18 04 22](https://cloud.githubusercontent.com/assets/5623301/8962725/5cfd919e-361c-11e5-903e-de5488301862.png)

**Comment by PaoloRotolo** [comment]
Found the bug in Android 4.1.1.
I'm working on a fix.

![screenshot from 2015-08-04 14 44 39](https://cloud.githubusercontent.com/assets/5623301/9060789/60416f34-3ab7-11e5-92b4-392a260c5840.png)

**Comment by PaoloRotolo** [comment]
Fixed, thank you!
