### ISSUE TITLE
newInstance is Depreciated

### ISSUE THREAD

**Issue by studio2bdesigns** [paolorotolo/AppIntro#627]
Please note, `newInstance` is **Depreciated.**<br>
It is crossed-out within Android Studio, and said to be **Depreciated** - however it _does_ work when ran.<br>
..Is there an updated way of doing this, to replace using `newInstance`..?<br>
<br>
**Example of code that is Depreciated:**<br>
`addSlide(AppIntroFragment.newInstance("title", "description", R.drawable.image, background_color));`<br>
<br>
Please take note, and anybody who knows anything about this please let me know.<br>
Thanks!<br>
<br>

**Comment by cortinico** [comment]
Hi @studio2bdesigns 

So the behavior is expected.
The method `AppIntroFragment.newInstance` is deprecated in AppIntro `4+`. Deprecated means that you can still use it but expect it to change.

The alternative to your code is to use a SliderPage:

```
        SliderPage sliderPage = new SliderPage();
        sliderPage.setTitle(title);
        sliderPage.setDescription(description);
        sliderPage.setImageDrawable(image);
        sliderPage.setBgColor(backgroundColor);
        addSlide(AppIntroFragment.newInstance(sliderPage));
```

Please note that in the upcoming version of AppIntro, we removed the deprecated methods and we now offer only two methods on `AppIntroFragment`:

```kotlin
fun newInstance(
                title: CharSequence? = null,
                description: CharSequence? = null,
                @FontRes titleTypefaceFontRes: Int = 0,
                @FontRes descTypefaceFontRes: Int = 0,
                @DrawableRes imageDrawable: Int = 0,
                @ColorInt bgColor: Int = 0,
                @ColorInt titleColor: Int = 0,
                @ColorInt descColor: Int = 0
        )

fun newInstance(sliderPage: SliderPage)
```
