### ISSUE TITLE
Layouts are bugged: indicator not centered

### ISSUE THREAD

**Issue by deinlandel** [PaoloRotolo/AppIntro#63]
Both intro_layout and intro_layout2 layouts are unstable: they rely on sizes of "skip" and "continue" buttons to center pager indicator. On some devices (mine, for example) this also leads to page indicator being off center. Page indicator should be in separate layout which is overlaid on top of the layout with buttons. This way, it will always be centered horizontally regardless of buttons visibility, size and position.

**Comment by deinlandel** [comment]
Here are screenshots of your example app from google Play on my Xperia Z2
![screenshot_2015-07-28-18-41-39](https://cloud.githubusercontent.com/assets/2368101/8932814/d391a9cc-3558-11e5-88e8-e52571f64568.png)
![screenshot_2015-07-28-18-41-48](https://cloud.githubusercontent.com/assets/2368101/8932816/d8f71852-3558-11e5-86a9-96d2b036106f.png)

**Comment by PaoloRotolo** [comment]
Will be fixed in next release. Thank you!
