### ISSUE TITLE
Why does this library depend on the deprecated NineOldAndroids library?

### ISSUE THREAD

**Issue by rajohns08** [PaoloRotolo/AppIntro#67]
The library build.gradle brings in NineOldAndroids. Why? That library is deprecated and adds a lot of bloat:

https://github.com/PaoloRotolo/AppIntro/blob/master/library/build.gradle

**Comment by PaoloRotolo** [comment]
It seems it was added to maintain API 9 compatibility: https://github.com/PaoloRotolo/AppIntro/commit/352ba6823efd4acc4e6c3748e2c095444c09cdfa

**Comment by rajohns08** [comment]
I would argue it is better to up minSdk to 14 like NineOldAndroids README suggests as opposed to including a big deprecated library.

**Comment by PaoloRotolo** [comment]
Aye, I'll remove NineOldAndroids in next release.
Thanks!

**Comment by PaoloRotolo** [comment]
Fixed.
Thanks again!

**Comment by marbat87** [comment]
@rajohns08 What's your problem? Did API8 compatibility cause any issue with the library?? I don't see the need to remove NineOldAndroids...

**Comment by SimonMayerhofer** [comment]
I would love to have support back to API 10. Is there a way to make it compatible with API 10 devices?
