### ISSUE TITLE
Only Show when First Installing ?

### ISSUE THREAD

**Issue by helmifluida** [PaoloRotolo/AppIntro#7]
How, if this intro only show when First Installing ??? i newbie dev

**Comment by Bernix01** [comment]
Try this http://stackoverflow.com/questions/7238532/how-to-launch-activity-only-once-when-app-is-opened-for-first-time

**Comment by jbollacke** [comment]
IMHO this should be in the scope of this plugin.

**Comment by PaoloRotolo** [comment]
@jbollacke You can easly do it in your MainActivity. Just check if there's an entry in SharedPreferences and **if yes** start IntroActivity.
It's bad to check it when IntroActivity is already started.

**Comment by jbollacke** [comment]
@PaoloRotolo Sure. But it would be nice if this library would provide some neat API for that problem ;-)

**Comment by cyberformed** [comment]
Thanks for sharing this link.
