### ISSUE TITLE
Is there any way to hide the navigation bar

### ISSUE THREAD

**Issue by Ridermansb** [PaoloRotolo/AppIntro#70]
In my app, I need to hide navigation bar and I will manage the next page, previous and done.

**Comment by PaoloRotolo** [comment]
Make a new style for your FullScreen activity:

```
    <style name="FullscreenTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
    </style>
```

And put it in Manifest:

```
        <activity
            android:name=".DefaultIntro"
            android:label="@string/title_activity_default_intro"
            android:theme="@style/FullscreenTheme">
        </activity>
```

**Comment by Ridermansb** [comment]
![untitled](https://cloud.githubusercontent.com/assets/725337/9141996/41d8faae-3d13-11e5-95cb-3ab1812cdfb5.png)

**Comment by PaoloRotolo** [comment]
Ah, so just implement your own ViewPager. You don't need to use AppIntro.

Read more on Android Developers: http://developer.android.com/training/animation/screen-slide.html

**Comment by Ridermansb** [comment]
Thank you. I did not know about this feature.

**Comment by PaoloRotolo** [comment]
Np, good luck :)
