### ISSUE TITLE
Correct way to get the fragment reference after configuration change

### ISSUE THREAD

**Issue by shell-software** [PaoloRotolo/AppIntro#71]
Hi!

Thank you for great library. It saves much time

While using the Library I faced with the problem of getting the reference to a fragment, which is already added to **ViewPager**
The simple way for getting the fragment is to use its tag or id (in my case the tag is more preferable). However I didn't find any way of using tag with your library

Say, you have a code like this:

```java
public class ActivityStart extends AppIntro2 {

	private FragmentSlidePassword fragmentSlidePassword;

	@Override
	public void init(Bundle bundle) {
		if (bundle == null) {
			fragmentSlidePassword = new FragmentSlidePassword();
		} else {
			List<Fragment> fragments = getSupportFragmentManager().getFragments();
			for (Fragment fragment : fragments) {
				if (fragment instanceof FragmentSlidePassword) {
					fragmentSlidePassword = (FragmentSlidePassword) fragment;
				}
			}
		}
		if (fragmentSlidePassword != null) {
			addSlide(fragmentSlidePassword);
		}
	}

}
```

As you see, this part of code:
```java
List<Fragment> fragments = getSupportFragmentManager().getFragments();
for (Fragment fragment : fragments) {
	if (fragment instanceof FragmentSlidePassword) {
		fragmentSlidePassword = (FragmentSlidePassword) fragment;
	}
}
```
is used to get the reference to a specific fragment. This code, however, is not a correct way of getting the reference.

Could you please suggest a more elegant way of getting such references?

Thanks

**Comment by Andrew-Quebe** [comment]
What's incorrect about this?

**Comment by Andrew-Quebe** [comment]
@shell-software I'm closing this issue as it hasn't been active in almost 2 months. Please feel free to reopen a new issue should you have any troubles. I don't see anything wrong with your workaround.
