### ISSUE TITLE
Add option to show Notification bar

### ISSUE THREAD

**Issue by filippofavaro** [PaoloRotolo/AppIntro#73]
Cloud you please add an option to show the notification bar like in Google Apps intros?

![screenshot_2015-08-16-14-18-45](https://cloud.githubusercontent.com/assets/6340261/9293213/12cfd276-4422-11e5-8dc2-9bf1a35e4021.png)

**Comment by SimonMayerhofer** [comment]
+1

**Comment by brunano21** [comment]
+1

**Comment by Andrew-Quebe** [comment]
This is addressed in issue #69.
