### ISSUE TITLE
Change properties to protected

### ISSUE THREAD

**Issue by sagits** [PaoloRotolo/AppIntro#74]
Hi Paolo, its an amazing job you are doing there. I have a suggestion, can you change all your properties to protected instead of private? This way we can extend and customize any of your classes. Thanks in advance.

**Comment by danluong** [comment]
I'm trying to set a constant background image with some transparency in the AppIntro2 activity and think this would help. Right now, I can see the background color in intro_layout2.xml, but would like to replace with an image. If I could override onCreate (while calling super.onCreate) then I can set it programmatically and solve the issue. +1 for hoping this can be changed.
