### ISSUE TITLE
Adding Slide directly into Fragment

### ISSUE THREAD

**Issue by andremacpereira** [PaoloRotolo/AppIntro#76]
Is there anyway we can "addSlides" straight thru the SampleSlide Fragment? I'm facing a Java Multiple Inheritance problem where I can't extend my class to AppIntro2.

**Comment by Andrew-Quebe** [comment]
Please provide some code of what you've tried and what's not working.

**Comment by Andrew-Quebe** [comment]
@andremacpereira closing this issue until code is provided. Thanks :)
