### ISSUE TITLE
How can i change the color of the dots?

### ISSUE THREAD

**Issue by cabuhatprince** [PaoloRotolo/AppIntro#78]

**Comment by milosjovac** [comment]
Thanks for the great lib! Though it is possible to change indicator dots' color by providing custom IndicatorController, it would be great if one could do it just by calling AppIntro methods.

@cabuhatprince Until I make the pull request for this feature, or someone else beat me to it, this is how you can do it with providing custom IndicatorController.

Step 1: 
At the bottom of your init method in AppIntro activity add this line setCustomIndicator(new CustomIndicator());

Step 2:
Create 2 drawable files to your liking.

Step 3:
Create CustomIndicator class and implement IndicatorController. Copy DefaultIndicatorController code and replace drawable ids with files you created in step 2.

Step 4:
Enjoy :)

**Comment by Andrew-Quebe** [comment]
@milosjovac ETA on that PR?

**Comment by Andrew-Quebe** [comment]
This issue was addressed in PR #93.
