### ISSUE TITLE
Overlapping?

### ISSUE THREAD

**Issue by Bernix01** [PaoloRotolo/AppIntro#8]
Hi, I'm getting this, pls help
![device-2015-06-06-130155](https://cloud.githubusercontent.com/assets/5255494/8020795/4295f12e-0c4c-11e5-8fdc-395c88235112.png)

**Comment by PaoloRotolo** [comment]
Can you share your code implementation please?

**Comment by Bernix01** [comment]
My fault, I wass setting traslucent navigation bar in theme so it resulted in this... Btw great job! Very usefull (Y)

**Comment by Ayysir** [comment]
im having same issue

**Comment by PaoloRotolo** [comment]
Good! @Ayysir make sure you're not using the wrong theme :)
