### ISSUE TITLE
Custom animation inside view

### ISSUE THREAD

**Issue by MaSteve** [PaoloRotolo/AppIntro#81]
Hello! I'm so interested in your lib, but I've some doubts about it. Transition animations are so cool but I'm also interested in set an animation inside my custom view. I would like to show a screenshot of my app and then show a description changing the alpha value of a TextView. That's easy but I need to know when my view will be shown and then start the animation. So, is there any easy option to notify my fragment when it will appear?

Thanks for all your work.

**Comment by Andrew-Quebe** [comment]
I just came onto this project so @PaoloRotolo should be able to answer this...I'm still learning all the capabilities of the lib! I'll make sure this gets to him.

**Comment by Andrew-Quebe** [comment]
@MaSteve the latest version of the library (will be released sometime soon) has support for detecting when the slide is changed. You will be able to override what happens when the slide is changed and I believe this will solve your issue.
