### ISSUE TITLE
onDotSelected not working

### ISSUE THREAD

**Issue by jeffreyliu8** [PaoloRotolo/AppIntro#84]
@Override
    public void onDotSelected(int index) {
        Log.d("intro", "index " + index + " is selected");
    }

I tried this and nothing happens.

**Comment by pulimento** [comment]
Me too, method is not called

**Comment by fanky10** [comment]
I just took a look at the code and that function is currently broken due to, what looks like, a refactoring of how and when dots are generated. I'm looking forward to fixing it, when I get it ready I will create a pull request.

Thanks

**Comment by porokoro** [comment]
The callback was introduced with pull request #66 and never worked. Unfortunately the function `selectDot(int)` was reinserted with this pull request. But I moved the stated method to another place even before the pull request ([Commit link](https://github.com/PaoloRotolo/AppIntro/commit/c0e69e036fc4b10a7c66e991f25356354aeca4f0), #46). Thus the reinserted method was never called (and consequently the callback as well) right from the beginning. 

Seems like this feature was never tested before the pull request was merged.

**Comment by ericcarboni** [comment]
@fanky10 how did you implement a  fix for this?

**Comment by fanky10** [comment]
adding a listener to each button and checking with was clicked by getting the view id.

Something like this
http://stackoverflow.com/questions/3320115/android-onclicklistener-identify-a-button

I have to add some cleanup I think by EOD will create the PR.

**Comment by tajchert** [comment]
I'm looking forward this because it is great way to ask for permissions or some action. Much appreciated.

**Comment by Andrew-Quebe** [comment]
Full support for Android 6.0 permissions is coming soon :)

**Comment by Quentin330** [comment]
@Andrew-Quebe you marked it as fixed in next release, any idea when this will be ? I'm using app intro in the next update of my app and I'm waiting to be able to ask permissions in the intro before releasing the update

**Comment by Andrew-Quebe** [comment]
@Quentin330 here's some basic progress: https://github.com/PaoloRotolo/AppIntro/commit/441620a8e14088738a0cb8f35231033b857512c4

onDotSelected has been completely removed. I have no clue what it's original purpose was or why it was even there. Read my commit message carefully. A lot of work still needs to be done to perfect this thing but I think I'm getting closer. Thanks for being patient :)

**Comment by danluong** [comment]
I think this method onDotSelected is not actually needed. What it would have been used for is to know when a certain page was selected, but this can be accomplished by adding an OnPageChangeListener to the pager, incorporated a while ago in my pull request #100 . 

For example, you could do this to know when a page is selected in your activity which extends AppIntro, however you will not get a notification upon the display of the initial slide which is a bug in Android's ViewPager OnPageChangeListener:


        AppIntroViewPager pager = getPager();
        pager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
            }


            @Override
            public void onPageSelected(int position) {
                Toast.makeText(getApplicationContext(), "onPageSelected: " + position, Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onPageScrollStateChanged(int state) {
            }
        });

**Comment by Andrew-Quebe** [comment]
@danluong well, as of the next version, it's actually much more simple. Devs now have the option to code things when the slide is changed (onSlideChanged()) and also when the buttons are pressed (onNextPressed()).

Also, if you're using Android 6.0 permissions, you can run this method to request permissions.

askForPermissions(String[], int slideNumber);

These changes are coming soon to maven.

**Comment by brunano21** [comment]
@Andrew-Quebe I wonder if with the latest version 3.3.0 the onSlideChanged() and onNextPressed() methods have been introduced or not. 
Thanks.

**Comment by Andrew-Quebe** [comment]
@brunano21 yes they are. However, onSlideChanged is called only when the slide is changed but there isn't an indicator of what slide it changed to. This will be fixed soon.

**Comment by benkissi** [comment]
For now can we use the OnPageChangeListener to create slide specific actions.
