### ISSUE TITLE
Transform background color while sliding

### ISSUE THREAD

**Issue by nowke** [PaoloRotolo/AppIntro#85]
How to transform the Fragments' background color according to the percentage of swipe, like in Google Apps? (Drive, Docs etc.) 

Similar approach is done in [TakeOffAndroid](https://github.com/TakeoffAndroid/AppIntroAnimation)

**Comment by msathis** [comment]
I have added an example in https://github.com/PaoloRotolo/AppIntro/issues/80

**Comment by Andrew-Quebe** [comment]
Duplicate of #80.
