### ISSUE TITLE
Not showing up when app is started

### ISSUE THREAD

**Issue by armyofpunk** [PaoloRotolo/AppIntro#87]
Hi Thanks for the great library, I am unable to get AppIntro to show up when the app is first opened, I have tried the code from stackoverflow you have linked here but it shows up with errors that i cant figure out why.

thanks for any help!

**Comment by armyofpunk** [comment]
After searching and fighting I've got AppIntro working now, but now it wont load MainActivity after done is pressed. it just reloads the first slide again.

thanks

**Comment by Andrew-Quebe** [comment]
Have you looked at the example app? You might try compiling that in Android Studio to see how it's done...browsing files in an editor is much easier than browsing them on GitHub.

**Comment by armyofpunk** [comment]
I was just doing that, and I've got it loading now but it doesn't go away after the first so run now. It's there everything I open the app up?

Thanks for the help!

**Comment by armyofpunk** [comment]
I will post my code for you

**Comment by Andrew-Quebe** [comment]
@armyofpunk great! Looking forward to seeing your implementation. I remember I had a little bit of trouble getting the activity to launch and quit at the right time but I figured it out eventually...trial and error. Your code will help me see what's up.

**Comment by Andrew-Quebe** [comment]
As this hasn't been active for a over a month, I'm going to close it with some final suggestions.

So make the intro not show up again, run a thread at the bottom of your onCreate method of your MainActivity. In this thread, declare a SharedPreference that is a boolean value. This boolean value is going to be set in your thread after your app is started for the first time. 

Here's a code example for you:

    //  Declare a new thread to do a preference check
    Thread t = new Thread(new Runnable() {
        @Override
        public void run() {
            //  Initialize SharedPreferences
            SharedPreferences getPrefs = PreferenceManager
                        .getDefaultSharedPreferences(getBaseContext());

            //  Create a new boolean and preference and set it to true
            boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

            //  If the activity has never started before...
            if (isFirstStart) {

                //  Launch app intro
                Intent i = new Intent(MainActivity.this, DefaultIntro.class);
                startActivity(i);

                //  Make a new preferences editor
                SharedPreferences.Editor e = getPrefs.edit();

                //  Edit preference to make it false because we don't want this to run again
                e.putBoolean("firstStart", false);

                //  Apply changes
                e.apply();
            }
        }
    });

    //Start this thread AFTER drawer and activity have been loaded to prevent errors
    t.start();

This should solve your problem of it starting every time you launch your app. I hope this helps you :)

If you have any questions, feel free to reopen this issue.
