### ISSUE TITLE
No touch feedback on interactive elements

### ISSUE THREAD

**Issue by vickychijwani** [PaoloRotolo/AppIntro#9]
Hey, cool library you have here. I tried Hermes as a demo, and it seems like none of the interactive UI elements (buttons, etc) have touch feedback. It'd be great to add that.

**Comment by ikrum** [comment]
1+ for touch feedback

**Comment by PaoloRotolo** [comment]
Nice idea, I'm working on it :)

**Comment by vickychijwani** [comment]
Apologies if I miscommunicated, but by touch feedback I meant touch ripples (for API 21+) and highlights (for < API 20).

**Comment by vickychijwani** [comment]
I can send a pull request if you want me to, just let me know :)

**Comment by PaoloRotolo** [comment]
Woops, now you have both features :P

**Comment by vickychijwani** [comment]
Great, thanks! I hope the vibration doesn't eat battery, and besides, it's not standard behaviour on Android. You may want to re-consider that :)
