### ISSUE TITLE
Question: how to handle an interactive intro?

### ISSUE THREAD

**Issue by brunano21** [PaoloRotolo/AppIntro#92]
Hi,
I would like to use AppIntro in order to have an interactive tutorial. In particular, the user will follow this intro setting some user details, like an username and a photo.
In this scenario, what is the best way to accomplish that?
Where should the business logic take place?

Any suggestion is really appreciated.

**Comment by Andrew-Quebe** [comment]
You might be able to override the fragment views and store that data in a database (assuming this is user info like username, password, etc.). You can also pass it as intent data since the app intro itself is an activity.

**Comment by brunano21** [comment]
@Andrew-Quebe
Yes the app intro has its own activity. My main concern is:
Let say we have 3 slides and in each of them the user will set up some personal details (like first name and last name and few more). When he gets at the end I should collect all those information and send to a server. With this scenario, who can collect those details? 
Almoat sure that when the user gets at the end the server call can take place within the `onDonePressed` method (confirm please). Instead between slides, what is the method and the way I can use to access to the current fragment, get data I need and finally move to the next slide? 
Hope I have been clear.
Thanks.

**Comment by Andrew-Quebe** [comment]
So gathering text from your text fields would be handled in the fragments...each one actually. What you could do is gather the info, perhaps store it as intent data, and then onDonePressed, send your intent data to the server. Another way to achieve this is to store that data locally using a database of some sort and then query it onDonePressed and send the data to your server. You'd want to delete the tables and such after user creation for security reasons.

**Comment by brunano21** [comment]
Ok, I agree with you - but there is something still not clear to me. It's more a fragment handling related question. When the user fills in a field within to a fragment, then he presses the `next` button. Before the app switches to the next fragment, it has to collect and store the inserted data somewhere (not important where at the moment). So, how? Where is this done? How can I get data ***when*** the user taps on next? This is the point that I don't get.

**Comment by Andrew-Quebe** [comment]
I'll look into this and get back to you...I need to conduct some research and testing. It may be something I need to add to the library itself...to handle such things. Give me some time.

**Comment by brunano21** [comment]
Sure. Thanks!

**Comment by brunano21** [comment]
@Andrew-Quebe Hi again
I was thinking about the above question, and writing some code I see that the onCreate of the fragment is never called, this means that I cannot also change something programmatically.
Do you confirm?

**Comment by konigsoft** [comment]
@brunano21 hi Bruno,
Have you think about using PreferenceFragment in order to save the data ?

@PaoloRotolo thank you for your lib do you plan to add support for preferencefragment ?

I use preferenceFragment unfortunately the theme is not showing correctly with AppIntro2

**Comment by brunano21** [comment]
Hi @konigsoft, storing data is not a problem at the moment. My main concern is how to handle fragments with some inputs. As I said above, I realized that I cannot manage the onCreate function, since it doesn't get called.

**Comment by HeinrichReimer** [comment]
@brunano21 this is in some way related to #119.
You could fix this temporary by using `init()` as `onCreate()` replacement.

**Comment by avluis** [comment]
Looks like this no longer applies after the recent changes on the library, please reopen this issue if still affected by this issue.
