### ISSUE TITLE
I'm using AppIntro... 

### ISSUE THREAD

**Issue by MartinNemec** [PaoloRotolo/AppIntro#95]
... May I ask you to add the app fimpl (com.danielZET.fimpl) to your "who is using it"  section. 

Thanks a lot

**Comment by Andrew-Quebe** [comment]
Some notes: first off, please link to your full Google Play Store listing URL (I had to find your app on the store). Second, I installed your app and, while it's listed in the about section, the intro didn't show up at all during my use of your app. I expected it to show first thing at launch. 

If it's hidden, or an update which adds it hasn't been released yet, please reopen this issue again or make a new one. Thanks!

Oh...and when I press the toggles in the nav drawer, your app crashes. I'm on a Nexus 5.

**Comment by Andrew-Quebe** [comment]
One other thing: it would make things even easier if your store listing screenshots showed use of the intro itself.
