### ISSUE TITLE
Fade Animation not working

### ISSUE THREAD

**Issue by FallenRiteMonk** [PaoloRotolo/AppIntro#98]
I tried to set fade animation using the setFadeAnimation method, but It seems to not work on my nexus 5 running android marshmallow. If i run the example in the https://play.google.com/store/apps/details?id=com.desarrollodroide.repos app then the fade animation works with no problems!

**Comment by Andrew-Quebe** [comment]
Please provide some code!

**Comment by Andrew-Quebe** [comment]
Closing this issue until code is provided. Please reopen when you've done so. Thanks :)
